L 10/25/2019 - 04:11:28: SourceMod error session started
L 10/25/2019 - 04:11:28: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 04:11:28: Error log file session closed.
L 10/25/2019 - 04:17:29: SourceMod error session started
L 10/25/2019 - 04:17:29: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 04:17:29: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 04:17:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 04:17:29: [SM] Call stack trace:
L 10/25/2019 - 04:17:29: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 04:17:29: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 04:17:29: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 04:17:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 04:17:29: [SM] Call stack trace:
L 10/25/2019 - 04:17:29: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 04:17:29: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 04:17:29: Error log file session closed.
L 10/25/2019 - 04:19:50: SourceMod error session started
L 10/25/2019 - 04:19:50: Info (map "c2m1_highway") (file "errors_20191025.log")
L 10/25/2019 - 04:19:50: [CRASH] Accelerator uploaded crash dump: Crash ID: KGAV-LOUN-XG6X
L 10/25/2019 - 18:48:26: Error log file session closed.
L 10/25/2019 - 18:48:29: SourceMod error session started
L 10/25/2019 - 18:48:29: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 18:48:29: [SM] Exception reported: Client 1 is not in game
L 10/25/2019 - 18:48:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 18:48:29: [SM] Call stack trace:
L 10/25/2019 - 18:48:29: [SM]   [0] GetClientTeam
L 10/25/2019 - 18:48:29: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 18:50:48: [SM] Exception reported: Client index 145 is invalid
L 10/25/2019 - 18:50:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 18:50:48: [SM] Call stack trace:
L 10/25/2019 - 18:50:48: [SM]   [0] IsClientInGame
L 10/25/2019 - 18:50:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 18:50:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 18:53:48: Error log file session closed.
L 10/25/2019 - 18:53:52: SourceMod error session started
L 10/25/2019 - 18:53:52: Info (map "c1m2_streets") (file "errors_20191025.log")
L 10/25/2019 - 18:53:52: [SM] Exception reported: Client 7 is not in game
L 10/25/2019 - 18:53:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 18:53:52: [SM] Call stack trace:
L 10/25/2019 - 18:53:52: [SM]   [0] GetClientTeam
L 10/25/2019 - 18:53:52: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 19:02:57: [SM] Exception reported: Client 3 is not in game
L 10/25/2019 - 19:02:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:02:57: [SM] Call stack trace:
L 10/25/2019 - 19:02:57: [SM]   [0] GetClientTeam
L 10/25/2019 - 19:02:57: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 19:04:21: [SM] Exception reported: Entity 9 (9) is invalid
L 10/25/2019 - 19:04:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:04:21: [SM] Call stack trace:
L 10/25/2019 - 19:04:21: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:04:21: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 19:04:21: Error log file session closed.
L 10/25/2019 - 19:09:12: SourceMod error session started
L 10/25/2019 - 19:09:12: Info (map "c1m3_mall") (file "errors_20191025.log")
L 10/25/2019 - 19:09:12: [SM] Exception reported: Entity 11 (11) is invalid
L 10/25/2019 - 19:09:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:09:12: [SM] Call stack trace:
L 10/25/2019 - 19:09:12: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:09:12: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 19:11:28: [SM] Exception reported: Entity 11 (11) is invalid
L 10/25/2019 - 19:11:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:11:28: [SM] Call stack trace:
L 10/25/2019 - 19:11:28: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:11:28: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 19:13:58: [SM] Exception reported: Entity 11 (11) is invalid
L 10/25/2019 - 19:13:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:13:58: [SM] Call stack trace:
L 10/25/2019 - 19:13:58: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:13:58: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 19:14:58: [SM] Exception reported: Client 1 is not in game
L 10/25/2019 - 19:14:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:14:58: [SM] Call stack trace:
L 10/25/2019 - 19:14:58: [SM]   [0] GetClientTeam
L 10/25/2019 - 19:14:58: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 19:14:58: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 19:14:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:14:58: [SM] Call stack trace:
L 10/25/2019 - 19:14:58: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:14:58: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 19:14:58: Error log file session closed.
L 10/25/2019 - 19:19:40: SourceMod error session started
L 10/25/2019 - 19:19:40: Info (map "c1m4_atrium") (file "errors_20191025.log")
L 10/25/2019 - 19:19:40: [SM] Exception reported: Client index 500 is invalid
L 10/25/2019 - 19:19:40: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 19:19:40: [SM] Call stack trace:
L 10/25/2019 - 19:19:40: [SM]   [0] IsClientInGame
L 10/25/2019 - 19:19:40: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 19:19:40: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 19:19:44: [SM] Exception reported: Client index 500 is invalid
L 10/25/2019 - 19:19:44: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 19:19:44: [SM] Call stack trace:
L 10/25/2019 - 19:19:44: [SM]   [0] IsClientInGame
L 10/25/2019 - 19:19:44: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 19:19:44: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 19:20:39: [SM] Exception reported: Entity 1 (1) is invalid
L 10/25/2019 - 19:20:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:20:39: [SM] Call stack trace:
L 10/25/2019 - 19:20:39: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:20:39: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 19:24:29: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 19:24:29: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 19:24:29: [SM] Call stack trace:
L 10/25/2019 - 19:24:29: [SM]   [0] SetEntProp
L 10/25/2019 - 19:24:29: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 19:25:20: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 19:25:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:25:20: [SM] Call stack trace:
L 10/25/2019 - 19:25:20: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:25:20: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 19:25:20: Error log file session closed.
L 10/25/2019 - 19:29:53: SourceMod error session started
L 10/25/2019 - 19:29:53: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 19:29:53: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 19:29:53: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 19:29:53: [SM] Call stack trace:
L 10/25/2019 - 19:29:53: [SM]   [0] SetEntProp
L 10/25/2019 - 19:29:53: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 19:30:43: Error log file session closed.
L 10/25/2019 - 19:32:54: SourceMod error session started
L 10/25/2019 - 19:32:54: Info (map "c1m2_streets") (file "errors_20191025.log")
L 10/25/2019 - 19:32:54: [SM] Exception reported: Client 3 is not in game
L 10/25/2019 - 19:32:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:32:54: [SM] Call stack trace:
L 10/25/2019 - 19:32:54: [SM]   [0] GetClientTeam
L 10/25/2019 - 19:32:54: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 19:36:26: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 19:36:26: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 19:36:26: [SM] Call stack trace:
L 10/25/2019 - 19:36:26: [SM]   [0] SetEntProp
L 10/25/2019 - 19:36:26: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 19:41:11: [SM] Exception reported: Entity 4 (4) is invalid
L 10/25/2019 - 19:41:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 19:41:11: [SM] Call stack trace:
L 10/25/2019 - 19:41:11: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 19:41:11: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 19:41:12: Error log file session closed.
L 10/25/2019 - 19:43:35: SourceMod error session started
L 10/25/2019 - 19:43:35: Info (map "c1m3_mall") (file "errors_20191025.log")
L 10/25/2019 - 19:43:35: [SM] Exception reported: Client index 346 is invalid
L 10/25/2019 - 19:43:35: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 19:43:35: [SM] Call stack trace:
L 10/25/2019 - 19:43:35: [SM]   [0] IsClientInGame
L 10/25/2019 - 19:43:35: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 19:43:35: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 19:51:42: [SM] Exception reported: Client index 335 is invalid
L 10/25/2019 - 19:51:42: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 19:51:42: [SM] Call stack trace:
L 10/25/2019 - 19:51:42: [SM]   [0] IsClientInGame
L 10/25/2019 - 19:51:42: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 19:51:42: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 19:59:50: Error log file session closed.
L 10/25/2019 - 20:01:36: SourceMod error session started
L 10/25/2019 - 20:01:36: Info (map "c1m4_atrium") (file "errors_20191025.log")
L 10/25/2019 - 20:01:36: [SM] Exception reported: Client index 511 is invalid
L 10/25/2019 - 20:01:36: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:01:36: [SM] Call stack trace:
L 10/25/2019 - 20:01:36: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:01:36: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:01:36: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:03:00: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 20:03:00: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 20:03:00: [SM] Call stack trace:
L 10/25/2019 - 20:03:00: [SM]   [0] SetEntProp
L 10/25/2019 - 20:03:00: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 20:05:02: [SM] Exception reported: Client index 305 is invalid
L 10/25/2019 - 20:05:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:05:02: [SM] Call stack trace:
L 10/25/2019 - 20:05:02: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:05:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:05:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:06:25: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/25/2019 - 20:06:25: [SM] Blaming: l4d2_playstats.smx
L 10/25/2019 - 20:06:25: [SM] Call stack trace:
L 10/25/2019 - 20:06:25: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/25/2019 - 20:06:25: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/25/2019 - 20:06:25: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/25/2019 - 20:06:25: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/25/2019 - 20:06:39: [SM] Exception reported: Entity 10 (10) is invalid
L 10/25/2019 - 20:06:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 20:06:39: [SM] Call stack trace:
L 10/25/2019 - 20:06:39: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 20:06:39: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 20:06:39: [SM] Exception reported: Entity 1 (1) is invalid
L 10/25/2019 - 20:06:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 20:06:39: [SM] Call stack trace:
L 10/25/2019 - 20:06:39: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 20:06:39: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 20:06:40: Error log file session closed.
L 10/25/2019 - 20:16:54: SourceMod error session started
L 10/25/2019 - 20:16:54: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 20:16:54: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/25/2019 - 20:16:54: [SM] Blaming: l4d2_playstats.smx
L 10/25/2019 - 20:16:54: [SM] Call stack trace:
L 10/25/2019 - 20:16:54: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/25/2019 - 20:16:54: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/25/2019 - 20:16:54: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/25/2019 - 20:16:54: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/25/2019 - 20:24:22: [SM] Exception reported: Client index 63 is invalid
L 10/25/2019 - 20:24:22: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:24:22: [SM] Call stack trace:
L 10/25/2019 - 20:24:22: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:24:22: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:24:22: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:24:26: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 20:24:26: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 20:24:26: [SM] Call stack trace:
L 10/25/2019 - 20:24:26: [SM]   [0] SetEntProp
L 10/25/2019 - 20:24:26: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 20:24:38: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/25/2019 - 20:24:38: [SM] Blaming: l4d2_playstats.smx
L 10/25/2019 - 20:24:38: [SM] Call stack trace:
L 10/25/2019 - 20:24:38: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/25/2019 - 20:24:38: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/25/2019 - 20:24:38: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/25/2019 - 20:24:38: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/25/2019 - 20:24:57: [SM] Exception reported: Entity 3 (3) is invalid
L 10/25/2019 - 20:24:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 20:24:57: [SM] Call stack trace:
L 10/25/2019 - 20:24:57: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 20:24:57: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 20:24:58: Error log file session closed.
L 10/25/2019 - 20:28:16: SourceMod error session started
L 10/25/2019 - 20:28:16: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 20:28:16: [SM] Exception reported: Client index 394 is invalid
L 10/25/2019 - 20:28:16: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:28:16: [SM] Call stack trace:
L 10/25/2019 - 20:28:16: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:28:16: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:28:16: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:28:17: [SM] Exception reported: Client index 394 is invalid
L 10/25/2019 - 20:28:17: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:28:17: [SM] Call stack trace:
L 10/25/2019 - 20:28:17: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:28:17: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:28:17: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:34:05: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/25/2019 - 20:34:05: [SM] Blaming: l4d2_playstats.smx
L 10/25/2019 - 20:34:05: [SM] Call stack trace:
L 10/25/2019 - 20:34:05: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/25/2019 - 20:34:05: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/25/2019 - 20:34:05: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/25/2019 - 20:34:05: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/25/2019 - 20:34:21: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 20:34:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 20:34:21: [SM] Call stack trace:
L 10/25/2019 - 20:34:21: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 20:34:21: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 20:35:50: [SM] Exception reported: Client index 70 is invalid
L 10/25/2019 - 20:35:50: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:35:50: [SM] Call stack trace:
L 10/25/2019 - 20:35:50: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:35:50: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:35:50: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:36:02: [SM] Exception reported: Client index 70 is invalid
L 10/25/2019 - 20:36:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:36:02: [SM] Call stack trace:
L 10/25/2019 - 20:36:02: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:36:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:36:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:36:03: [SM] Exception reported: Client index 70 is invalid
L 10/25/2019 - 20:36:03: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 20:36:03: [SM] Call stack trace:
L 10/25/2019 - 20:36:03: [SM]   [0] IsClientInGame
L 10/25/2019 - 20:36:03: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 20:36:03: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 20:37:21: [SM] Exception reported: Client 5 is not in game
L 10/25/2019 - 20:37:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 20:37:21: [SM] Call stack trace:
L 10/25/2019 - 20:37:21: [SM]   [0] GetClientTeam
L 10/25/2019 - 20:37:21: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 20:37:22: Error log file session closed.
L 10/25/2019 - 20:44:49: SourceMod error session started
L 10/25/2019 - 20:44:49: Info (map "c1m2_streets") (file "errors_20191025.log")
L 10/25/2019 - 20:44:49: [SM] Exception reported: Entity 7 (7) is invalid
L 10/25/2019 - 20:44:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 20:44:49: [SM] Call stack trace:
L 10/25/2019 - 20:44:49: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 20:44:49: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 20:51:44: Error log file session closed.
L 10/25/2019 - 21:04:54: SourceMod error session started
L 10/25/2019 - 21:04:54: Info (map "c1m3_mall") (file "errors_20191025.log")
L 10/25/2019 - 21:04:54: [SM] Exception reported: Client 6 is not in game
L 10/25/2019 - 21:04:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:04:54: [SM] Call stack trace:
L 10/25/2019 - 21:04:54: [SM]   [0] GetClientTeam
L 10/25/2019 - 21:04:54: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:05:34: [SM] Exception reported: Client 6 is not in game
L 10/25/2019 - 21:05:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:05:34: [SM] Call stack trace:
L 10/25/2019 - 21:05:34: [SM]   [0] GetClientTeam
L 10/25/2019 - 21:05:34: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:05:34: Error log file session closed.
L 10/25/2019 - 21:15:00: SourceMod error session started
L 10/25/2019 - 21:15:00: Info (map "c1m4_atrium") (file "errors_20191025.log")
L 10/25/2019 - 21:15:00: [SM] Exception reported: Client index 282 is invalid
L 10/25/2019 - 21:15:00: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 21:15:00: [SM] Call stack trace:
L 10/25/2019 - 21:15:00: [SM]   [0] IsClientInGame
L 10/25/2019 - 21:15:00: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 21:15:00: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 21:15:02: [SM] Exception reported: Client index 282 is invalid
L 10/25/2019 - 21:15:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 21:15:02: [SM] Call stack trace:
L 10/25/2019 - 21:15:02: [SM]   [0] IsClientInGame
L 10/25/2019 - 21:15:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 21:15:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 21:15:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 21:15:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 21:15:55: [SM] Call stack trace:
L 10/25/2019 - 21:15:55: [SM]   [0] SetEntProp
L 10/25/2019 - 21:15:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 21:17:13: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 21:17:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:17:13: [SM] Call stack trace:
L 10/25/2019 - 21:17:13: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 21:17:13: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:17:22: Error log file session closed.
L 10/25/2019 - 21:17:36: SourceMod error session started
L 10/25/2019 - 21:17:36: Info (map "c2m1_highway") (file "errors_20191025.log")
L 10/25/2019 - 21:17:36: [SM] Exception reported: Client 1 is not in game
L 10/25/2019 - 21:17:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:17:36: [SM] Call stack trace:
L 10/25/2019 - 21:17:36: [SM]   [0] GetClientTeam
L 10/25/2019 - 21:17:36: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:19:47: Error log file session closed.
L 10/25/2019 - 21:34:13: SourceMod error session started
L 10/25/2019 - 21:34:13: Info (map "c2m1_highway") (file "errors_20191025.log")
L 10/25/2019 - 21:34:13: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 21:34:13: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 21:34:13: [SM] Call stack trace:
L 10/25/2019 - 21:34:13: [SM]   [0] SetEntProp
L 10/25/2019 - 21:34:13: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 21:34:40: [SM] Exception reported: Entity 6 (6) is invalid
L 10/25/2019 - 21:34:40: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:34:40: [SM] Call stack trace:
L 10/25/2019 - 21:34:40: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 21:34:40: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:34:41: Error log file session closed.
L 10/25/2019 - 21:42:22: SourceMod error session started
L 10/25/2019 - 21:42:22: Info (map "c2m2_fairgrounds") (file "errors_20191025.log")
L 10/25/2019 - 21:42:22: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 21:42:22: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 21:42:22: [SM] Call stack trace:
L 10/25/2019 - 21:42:22: [SM]   [0] SetEntProp
L 10/25/2019 - 21:42:22: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 21:42:42: [SM] Exception reported: Entity 10 (10) is invalid
L 10/25/2019 - 21:42:42: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:42:42: [SM] Call stack trace:
L 10/25/2019 - 21:42:42: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 21:42:42: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 21:44:46: [SM] Exception reported: Client index 391 is invalid
L 10/25/2019 - 21:44:46: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 21:44:46: [SM] Call stack trace:
L 10/25/2019 - 21:44:46: [SM]   [0] IsClientInGame
L 10/25/2019 - 21:44:46: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 21:44:46: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 21:45:29: Error log file session closed.
L 10/25/2019 - 21:45:40: SourceMod error session started
L 10/25/2019 - 21:45:40: Info (map "c2m3_coaster") (file "errors_20191025.log")
L 10/25/2019 - 21:45:40: [SM] Exception reported: Client 5 is not in game
L 10/25/2019 - 21:45:40: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:45:40: [SM] Call stack trace:
L 10/25/2019 - 21:45:40: [SM]   [0] GetClientTeam
L 10/25/2019 - 21:45:40: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:56:23: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 21:56:23: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 21:56:23: [SM] Call stack trace:
L 10/25/2019 - 21:56:23: [SM]   [0] SetEntProp
L 10/25/2019 - 21:56:23: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 21:57:03: [SM] Exception reported: Entity 4 (4) is invalid
L 10/25/2019 - 21:57:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:57:03: [SM] Call stack trace:
L 10/25/2019 - 21:57:03: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 21:57:03: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 21:57:03: [SM] Exception reported: Client 4 is not in game
L 10/25/2019 - 21:57:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:57:03: [SM] Call stack trace:
L 10/25/2019 - 21:57:03: [SM]   [0] GetClientTeam
L 10/25/2019 - 21:57:03: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:57:04: Error log file session closed.
L 10/25/2019 - 21:57:12: SourceMod error session started
L 10/25/2019 - 21:57:12: Info (map "c2m4_barns") (file "errors_20191025.log")
L 10/25/2019 - 21:57:12: [SM] Exception reported: Client 2 is not in game
L 10/25/2019 - 21:57:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:57:12: [SM] Call stack trace:
L 10/25/2019 - 21:57:12: [SM]   [0] GetClientTeam
L 10/25/2019 - 21:57:12: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 21:58:50: [SM] Exception reported: Client 2 is not in game
L 10/25/2019 - 21:58:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 21:58:50: [SM] Call stack trace:
L 10/25/2019 - 21:58:50: [SM]   [0] GetClientTeam
L 10/25/2019 - 21:58:50: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 22:10:24: [SM] Exception reported: Entity 4 (4) is invalid
L 10/25/2019 - 22:10:24: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 22:10:24: [SM] Call stack trace:
L 10/25/2019 - 22:10:24: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 22:10:24: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 22:10:24: [SM] Exception reported: Entity 6 (6) is invalid
L 10/25/2019 - 22:10:24: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 22:10:24: [SM] Call stack trace:
L 10/25/2019 - 22:10:24: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 22:10:24: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 22:10:24: Error log file session closed.
L 10/25/2019 - 22:11:33: SourceMod error session started
L 10/25/2019 - 22:11:33: Info (map "c2m5_concert") (file "errors_20191025.log")
L 10/25/2019 - 22:11:33: [SM] Exception reported: Client index 292 is invalid
L 10/25/2019 - 22:11:33: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 22:11:33: [SM] Call stack trace:
L 10/25/2019 - 22:11:33: [SM]   [0] IsClientInGame
L 10/25/2019 - 22:11:33: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 22:11:33: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 22:16:29: [SM] Exception reported: Client index 476 is invalid
L 10/25/2019 - 22:16:29: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 22:16:29: [SM] Call stack trace:
L 10/25/2019 - 22:16:29: [SM]   [0] IsClientInGame
L 10/25/2019 - 22:16:29: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 22:16:29: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 22:17:17: [SM] Exception reported: Entity 3 (3) is invalid
L 10/25/2019 - 22:17:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 22:17:17: [SM] Call stack trace:
L 10/25/2019 - 22:17:17: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 22:17:17: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 22:17:18: Error log file session closed.
L 10/25/2019 - 22:22:19: SourceMod error session started
L 10/25/2019 - 22:22:19: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 22:22:19: [SM] Exception reported: Client 5 is not in game
L 10/25/2019 - 22:22:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 22:22:19: [SM] Call stack trace:
L 10/25/2019 - 22:22:19: [SM]   [0] GetClientTeam
L 10/25/2019 - 22:22:19: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 22:22:19: Error log file session closed.
L 10/25/2019 - 22:33:25: SourceMod error session started
L 10/25/2019 - 22:33:25: Info (map "c1m2_streets") (file "errors_20191025.log")
L 10/25/2019 - 22:33:25: [SM] Exception reported: Client index 89 is invalid
L 10/25/2019 - 22:33:25: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 22:33:25: [SM] Call stack trace:
L 10/25/2019 - 22:33:25: [SM]   [0] IsClientInGame
L 10/25/2019 - 22:33:25: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 22:33:25: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 22:33:27: [SM] Exception reported: Client index 89 is invalid
L 10/25/2019 - 22:33:27: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 22:33:27: [SM] Call stack trace:
L 10/25/2019 - 22:33:27: [SM]   [0] IsClientInGame
L 10/25/2019 - 22:33:27: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 22:33:27: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 22:35:24: Error log file session closed.
L 10/25/2019 - 22:49:10: SourceMod error session started
L 10/25/2019 - 22:49:10: Info (map "c1m3_mall") (file "errors_20191025.log")
L 10/25/2019 - 22:49:10: [SM] Exception reported: Entity 1 (1) is invalid
L 10/25/2019 - 22:49:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 22:49:10: [SM] Call stack trace:
L 10/25/2019 - 22:49:10: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 22:49:10: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 22:49:11: [SM] Exception reported: Client 1 is not in game
L 10/25/2019 - 22:49:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 22:49:11: [SM] Call stack trace:
L 10/25/2019 - 22:49:11: [SM]   [0] GetClientTeam
L 10/25/2019 - 22:49:11: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 22:49:11: Error log file session closed.
L 10/25/2019 - 23:07:44: SourceMod error session started
L 10/25/2019 - 23:07:44: Info (map "c2m1_highway") (file "errors_20191025.log")
L 10/25/2019 - 23:07:44: [SM] Exception reported: Client 2 is not in game
L 10/25/2019 - 23:07:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:07:44: [SM] Call stack trace:
L 10/25/2019 - 23:07:44: [SM]   [0] GetClientTeam
L 10/25/2019 - 23:07:44: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 23:08:11: [SM] Exception reported: Client 3 is not in game
L 10/25/2019 - 23:08:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:08:11: [SM] Call stack trace:
L 10/25/2019 - 23:08:11: [SM]   [0] GetClientTeam
L 10/25/2019 - 23:08:11: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 23:12:20: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 23:12:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:12:20: [SM] Call stack trace:
L 10/25/2019 - 23:12:20: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 23:12:20: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 23:12:21: Error log file session closed.
L 10/25/2019 - 23:16:30: SourceMod error session started
L 10/25/2019 - 23:16:30: Info (map "c2m2_fairgrounds") (file "errors_20191025.log")
L 10/25/2019 - 23:16:30: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 23:16:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:16:30: [SM] Call stack trace:
L 10/25/2019 - 23:16:30: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 23:16:30: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 23:20:55: Error log file session closed.
L 10/25/2019 - 23:33:45: SourceMod error session started
L 10/25/2019 - 23:33:45: Info (map "c2m4_barns") (file "errors_20191025.log")
L 10/25/2019 - 23:33:45: [SM] Exception reported: Entity 4 (4) is invalid
L 10/25/2019 - 23:33:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:33:45: [SM] Call stack trace:
L 10/25/2019 - 23:33:45: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 23:33:45: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 23:37:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 23:37:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 23:37:28: [SM] Call stack trace:
L 10/25/2019 - 23:37:28: [SM]   [0] SetEntProp
L 10/25/2019 - 23:37:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 23:42:26: Error log file session closed.
L 10/25/2019 - 23:43:56: SourceMod error session started
L 10/25/2019 - 23:43:56: Info (map "c2m5_concert") (file "errors_20191025.log")
L 10/25/2019 - 23:43:56: [SM] Exception reported: Client index 410 is invalid
L 10/25/2019 - 23:43:56: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 23:43:56: [SM] Call stack trace:
L 10/25/2019 - 23:43:56: [SM]   [0] IsClientInGame
L 10/25/2019 - 23:43:56: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 23:43:56: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 23:45:54: [SM] Exception reported: Client index 562 is invalid
L 10/25/2019 - 23:45:54: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/25/2019 - 23:45:54: [SM] Call stack trace:
L 10/25/2019 - 23:45:54: [SM]   [0] IsClientInGame
L 10/25/2019 - 23:45:54: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/25/2019 - 23:45:54: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/25/2019 - 23:47:02: [SM] Exception reported: Entity 2 (2) is invalid
L 10/25/2019 - 23:47:02: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:47:02: [SM] Call stack trace:
L 10/25/2019 - 23:47:02: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 23:47:02: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 23:47:02: [SM] Exception reported: Entity 4 (4) is invalid
L 10/25/2019 - 23:47:02: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:47:02: [SM] Call stack trace:
L 10/25/2019 - 23:47:02: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 23:47:02: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/25/2019 - 23:47:02: Error log file session closed.
L 10/25/2019 - 23:49:56: SourceMod error session started
L 10/25/2019 - 23:49:56: Info (map "c1m1_hotel") (file "errors_20191025.log")
L 10/25/2019 - 23:49:56: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 23:49:56: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 23:49:56: [SM] Call stack trace:
L 10/25/2019 - 23:49:56: [SM]   [0] SetEntProp
L 10/25/2019 - 23:49:56: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 23:50:45: [SM] Exception reported: Entity 7 (7) is invalid
L 10/25/2019 - 23:50:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/25/2019 - 23:50:45: [SM] Call stack trace:
L 10/25/2019 - 23:50:45: [SM]   [0] GetEntDataEnt2
L 10/25/2019 - 23:50:45: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/25/2019 - 23:51:49: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/25/2019 - 23:51:49: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/25/2019 - 23:51:49: [SM] Call stack trace:
L 10/25/2019 - 23:51:49: [SM]   [0] SetEntProp
L 10/25/2019 - 23:51:49: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/25/2019 - 23:52:20: Error log file session closed.
