L 11/04/2019 - 00:09:23: SourceMod error session started
L 11/04/2019 - 00:09:23: Info (map "c12m1_hilltop") (file "errors_20191104.log")
L 11/04/2019 - 00:09:23: Error log file session closed.
L 11/04/2019 - 00:11:31: SourceMod error session started
L 11/04/2019 - 00:11:31: Info (map "c2m1_highway") (file "errors_20191104.log")
L 11/04/2019 - 00:11:31: [CRASH] Accelerator uploaded crash dump: Crash ID: LHIR-OALR-OXYQ
L 11/04/2019 - 20:38:49: Error log file session closed.
L 11/04/2019 - 20:51:18: SourceMod error session started
L 11/04/2019 - 20:51:18: Info (map "c12m2_traintunnel") (file "errors_20191104.log")
L 11/04/2019 - 20:51:18: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:18: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:18: [SM] Call stack trace:
L 11/04/2019 - 20:51:18: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:18: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 11/04/2019 - 20:51:19: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:19: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:19: [SM] Call stack trace:
L 11/04/2019 - 20:51:19: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:19: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 11/04/2019 - 20:51:20: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:20: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:20: [SM] Call stack trace:
L 11/04/2019 - 20:51:20: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:20: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 11/04/2019 - 20:51:21: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:21: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:21: [SM] Call stack trace:
L 11/04/2019 - 20:51:21: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:21: [SM]   [1] Line 208, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::ResetJumpRockCooldown
L 11/04/2019 - 20:51:21: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:21: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:21: [SM] Call stack trace:
L 11/04/2019 - 20:51:21: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:21: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 11/04/2019 - 20:51:22: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:22: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:22: [SM] Call stack trace:
L 11/04/2019 - 20:51:22: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:22: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 11/04/2019 - 20:51:23: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:23: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:23: [SM] Call stack trace:
L 11/04/2019 - 20:51:23: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:23: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 11/04/2019 - 20:51:24: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 20:51:24: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 11/04/2019 - 20:51:24: [SM] Call stack trace:
L 11/04/2019 - 20:51:24: [SM]   [0] IsPlayerAlive
L 11/04/2019 - 20:51:24: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 11/04/2019 - 20:57:09: [SM] Exception reported: Client index 196 is invalid
L 11/04/2019 - 20:57:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 20:57:09: [SM] Call stack trace:
L 11/04/2019 - 20:57:09: [SM]   [0] IsClientInGame
L 11/04/2019 - 20:57:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 20:57:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 21:02:39: Error log file session closed.
L 11/04/2019 - 21:22:36: SourceMod error session started
L 11/04/2019 - 21:22:36: Info (map "c12m4_barn") (file "errors_20191104.log")
L 11/04/2019 - 21:22:36: [SM] Exception reported: Entity 2 (2) is invalid
L 11/04/2019 - 21:22:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 21:22:36: [SM] Call stack trace:
L 11/04/2019 - 21:22:36: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 21:22:36: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/04/2019 - 21:22:37: Error log file session closed.
L 11/04/2019 - 21:23:57: SourceMod error session started
L 11/04/2019 - 21:23:57: Info (map "c12m5_cornfield") (file "errors_20191104.log")
L 11/04/2019 - 21:23:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 21:23:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 21:23:57: [SM] Call stack trace:
L 11/04/2019 - 21:23:57: [SM]   [0] SetEntProp
L 11/04/2019 - 21:23:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 21:31:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 21:31:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 21:31:20: [SM] Call stack trace:
L 11/04/2019 - 21:31:20: [SM]   [0] SetEntProp
L 11/04/2019 - 21:31:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 21:36:30: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 21:36:30: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 21:36:30: [SM] Call stack trace:
L 11/04/2019 - 21:36:30: [SM]   [0] SetEntProp
L 11/04/2019 - 21:36:30: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 21:38:38: [SM] Exception reported: Entity 3 (3) is invalid
L 11/04/2019 - 21:38:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 21:38:38: [SM] Call stack trace:
L 11/04/2019 - 21:38:38: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 21:38:38: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 21:38:38: Error log file session closed.
L 11/04/2019 - 21:51:54: SourceMod error session started
L 11/04/2019 - 21:51:54: Info (map "c2m2_fairgrounds") (file "errors_20191104.log")
L 11/04/2019 - 21:51:54: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 21:51:54: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 21:51:54: [SM] Call stack trace:
L 11/04/2019 - 21:51:54: [SM]   [0] SetEntProp
L 11/04/2019 - 21:51:54: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:00:31: Error log file session closed.
L 11/04/2019 - 22:06:16: SourceMod error session started
L 11/04/2019 - 22:06:16: Info (map "c2m3_coaster") (file "errors_20191104.log")
L 11/04/2019 - 22:06:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:06:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:06:16: [SM] Call stack trace:
L 11/04/2019 - 22:06:16: [SM]   [0] SetEntProp
L 11/04/2019 - 22:06:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:07:02: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:07:02: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:07:02: [SM] Call stack trace:
L 11/04/2019 - 22:07:02: [SM]   [0] SetEntProp
L 11/04/2019 - 22:07:02: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:15:08: Error log file session closed.
L 11/04/2019 - 22:21:19: SourceMod error session started
L 11/04/2019 - 22:21:19: Info (map "c2m4_barns") (file "errors_20191104.log")
L 11/04/2019 - 22:21:19: [SM] Exception reported: Client index 164 is invalid
L 11/04/2019 - 22:21:19: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 22:21:19: [SM] Call stack trace:
L 11/04/2019 - 22:21:19: [SM]   [0] IsClientInGame
L 11/04/2019 - 22:21:19: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 22:21:19: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 22:21:22: [SM] Exception reported: Client index 164 is invalid
L 11/04/2019 - 22:21:22: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 22:21:22: [SM] Call stack trace:
L 11/04/2019 - 22:21:22: [SM]   [0] IsClientInGame
L 11/04/2019 - 22:21:22: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 22:21:22: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 22:21:26: [SM] Exception reported: Client index 164 is invalid
L 11/04/2019 - 22:21:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 22:21:26: [SM] Call stack trace:
L 11/04/2019 - 22:21:26: [SM]   [0] IsClientInGame
L 11/04/2019 - 22:21:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 22:21:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 22:22:04: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:22:04: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:22:04: [SM] Call stack trace:
L 11/04/2019 - 22:22:04: [SM]   [0] SetEntProp
L 11/04/2019 - 22:22:04: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:22:22: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:22:22: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:22:22: [SM] Call stack trace:
L 11/04/2019 - 22:22:22: [SM]   [0] SetEntProp
L 11/04/2019 - 22:22:22: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:26:25: [SM] Exception reported: Client 1 is not in game
L 11/04/2019 - 22:26:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:26:25: [SM] Call stack trace:
L 11/04/2019 - 22:26:25: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:26:25: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:27:09: Error log file session closed.
L 11/04/2019 - 22:28:22: SourceMod error session started
L 11/04/2019 - 22:28:22: Info (map "c2m5_concert") (file "errors_20191104.log")
L 11/04/2019 - 22:28:22: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:28:22: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:28:22: [SM] Call stack trace:
L 11/04/2019 - 22:28:22: [SM]   [0] SetEntProp
L 11/04/2019 - 22:28:22: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:30:15: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:30:15: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:30:15: [SM] Call stack trace:
L 11/04/2019 - 22:30:15: [SM]   [0] SetEntProp
L 11/04/2019 - 22:30:15: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:31:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:31:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:31:01: [SM] Call stack trace:
L 11/04/2019 - 22:31:01: [SM]   [0] SetEntProp
L 11/04/2019 - 22:31:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:31:17: [SM] Exception reported: Entity 3 (3) is invalid
L 11/04/2019 - 22:31:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:17: [SM] Call stack trace:
L 11/04/2019 - 22:31:17: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 22:31:17: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:18: Error log file session closed.
L 11/04/2019 - 22:31:22: SourceMod error session started
L 11/04/2019 - 22:31:22: Info (map "c2m1_highway") (file "errors_20191104.log")
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 1 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 2 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 3 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 4 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 6 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 7 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 8 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 9 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: [SM] Exception reported: Client 10 is not in game
L 11/04/2019 - 22:31:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:31:22: [SM] Call stack trace:
L 11/04/2019 - 22:31:22: [SM]   [0] GetClientTeam
L 11/04/2019 - 22:31:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:31:22: Error log file session closed.
L 11/04/2019 - 22:32:40: SourceMod error session started
L 11/04/2019 - 22:32:40: Info (map "c2m1_highway") (file "errors_20191104.log")
L 11/04/2019 - 22:32:40: [CRASH] Accelerator uploaded crash dump: Crash ID: 7UNB-NBUL-YM5O
L 11/04/2019 - 22:40:57: Error log file session closed.
L 11/04/2019 - 22:51:11: SourceMod error session started
L 11/04/2019 - 22:51:11: Info (map "c4m1_milltown_a") (file "errors_20191104.log")
L 11/04/2019 - 22:51:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 22:51:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 22:51:11: [SM] Call stack trace:
L 11/04/2019 - 22:51:11: [SM]   [0] SetEntProp
L 11/04/2019 - 22:51:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 22:51:34: [SM] Exception reported: Entity 1 (1) is invalid
L 11/04/2019 - 22:51:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 22:51:34: [SM] Call stack trace:
L 11/04/2019 - 22:51:34: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 22:51:34: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 22:51:36: Error log file session closed.
L 11/04/2019 - 23:00:55: SourceMod error session started
L 11/04/2019 - 23:00:55: Info (map "c4m2_sugarmill_a") (file "errors_20191104.log")
L 11/04/2019 - 23:00:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 23:00:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 23:00:55: [SM] Call stack trace:
L 11/04/2019 - 23:00:55: [SM]   [0] SetEntProp
L 11/04/2019 - 23:00:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 23:02:02: [SM] Exception reported: Entity 3 (3) is invalid
L 11/04/2019 - 23:02:02: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 23:02:02: [SM] Call stack trace:
L 11/04/2019 - 23:02:02: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 23:02:02: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 23:02:02: [SM] Exception reported: Entity 5 (5) is invalid
L 11/04/2019 - 23:02:02: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 23:02:02: [SM] Call stack trace:
L 11/04/2019 - 23:02:02: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 23:02:02: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 23:02:03: Error log file session closed.
L 11/04/2019 - 23:04:53: SourceMod error session started
L 11/04/2019 - 23:04:53: Info (map "c4m3_sugarmill_b") (file "errors_20191104.log")
L 11/04/2019 - 23:04:53: [SM] Exception reported: Client index 112 is invalid
L 11/04/2019 - 23:04:53: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:04:53: [SM] Call stack trace:
L 11/04/2019 - 23:04:53: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:04:53: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:04:53: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:04:53: [SM] Exception reported: Client index 112 is invalid
L 11/04/2019 - 23:04:53: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:04:53: [SM] Call stack trace:
L 11/04/2019 - 23:04:53: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:04:53: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:04:53: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:10:32: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 23:10:32: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 23:10:32: [SM] Call stack trace:
L 11/04/2019 - 23:10:32: [SM]   [0] SetEntProp
L 11/04/2019 - 23:10:32: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 23:11:27: [SM] Exception reported: Entity 1 (1) is invalid
L 11/04/2019 - 23:11:27: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 23:11:27: [SM] Call stack trace:
L 11/04/2019 - 23:11:27: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 23:11:27: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 23:11:27: [SM] Exception reported: Entity 7 (7) is invalid
L 11/04/2019 - 23:11:27: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 23:11:27: [SM] Call stack trace:
L 11/04/2019 - 23:11:27: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 23:11:27: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 23:11:31: Error log file session closed.
L 11/04/2019 - 23:14:03: SourceMod error session started
L 11/04/2019 - 23:14:03: Info (map "c4m4_milltown_b") (file "errors_20191104.log")
L 11/04/2019 - 23:14:03: [SM] Exception reported: Client index 141 is invalid
L 11/04/2019 - 23:14:03: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:14:03: [SM] Call stack trace:
L 11/04/2019 - 23:14:03: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:14:03: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:14:03: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:14:06: [SM] Exception reported: Client index 141 is invalid
L 11/04/2019 - 23:14:06: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:14:06: [SM] Call stack trace:
L 11/04/2019 - 23:14:06: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:14:06: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:14:06: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:14:06: [SM] Exception reported: Client index 141 is invalid
L 11/04/2019 - 23:14:06: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:14:06: [SM] Call stack trace:
L 11/04/2019 - 23:14:06: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:14:06: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:14:06: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:14:07: [SM] Exception reported: Client index 141 is invalid
L 11/04/2019 - 23:14:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:14:07: [SM] Call stack trace:
L 11/04/2019 - 23:14:07: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:14:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:14:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:14:07: [SM] Exception reported: Client index 141 is invalid
L 11/04/2019 - 23:14:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:14:07: [SM] Call stack trace:
L 11/04/2019 - 23:14:07: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:14:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:14:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:14:09: [SM] Exception reported: Client index 141 is invalid
L 11/04/2019 - 23:14:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:14:09: [SM] Call stack trace:
L 11/04/2019 - 23:14:09: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:14:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:14:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:20:10: [SM] Exception reported: Client index 102 is invalid
L 11/04/2019 - 23:20:10: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:20:10: [SM] Call stack trace:
L 11/04/2019 - 23:20:10: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:20:10: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:20:10: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:21:07: [SM] Exception reported: Client index 125 is invalid
L 11/04/2019 - 23:21:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:21:07: [SM] Call stack trace:
L 11/04/2019 - 23:21:07: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:21:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:21:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:21:07: [SM] Exception reported: Client index 125 is invalid
L 11/04/2019 - 23:21:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:21:07: [SM] Call stack trace:
L 11/04/2019 - 23:21:07: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:21:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:21:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:21:07: [SM] Exception reported: Client index 125 is invalid
L 11/04/2019 - 23:21:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:21:07: [SM] Call stack trace:
L 11/04/2019 - 23:21:07: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:21:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:21:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:21:07: [SM] Exception reported: Client index 125 is invalid
L 11/04/2019 - 23:21:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:21:07: [SM] Call stack trace:
L 11/04/2019 - 23:21:07: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:21:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:21:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:21:07: [SM] Exception reported: Client index 125 is invalid
L 11/04/2019 - 23:21:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/04/2019 - 23:21:07: [SM] Call stack trace:
L 11/04/2019 - 23:21:07: [SM]   [0] IsClientInGame
L 11/04/2019 - 23:21:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/04/2019 - 23:21:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/04/2019 - 23:21:12: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 23:21:12: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 23:21:12: [SM] Call stack trace:
L 11/04/2019 - 23:21:12: [SM]   [0] SetEntProp
L 11/04/2019 - 23:21:12: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 23:21:39: Error log file session closed.
L 11/04/2019 - 23:25:47: SourceMod error session started
L 11/04/2019 - 23:25:47: Info (map "c4m5_milltown_escape") (file "errors_20191104.log")
L 11/04/2019 - 23:25:47: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 23:25:47: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 23:25:47: [SM] Call stack trace:
L 11/04/2019 - 23:25:47: [SM]   [0] SetEntProp
L 11/04/2019 - 23:25:47: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 23:35:54: [SM] Exception reported: Entity 5 (5) is invalid
L 11/04/2019 - 23:35:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 23:35:54: [SM] Call stack trace:
L 11/04/2019 - 23:35:54: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 23:35:54: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 23:35:54: [SM] Exception reported: Entity 3 (3) is invalid
L 11/04/2019 - 23:35:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 23:35:54: [SM] Call stack trace:
L 11/04/2019 - 23:35:54: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 23:35:54: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/04/2019 - 23:35:55: Error log file session closed.
L 11/04/2019 - 23:45:14: SourceMod error session started
L 11/04/2019 - 23:45:14: Info (map "c5m1_waterfront") (file "errors_20191104.log")
L 11/04/2019 - 23:45:14: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/04/2019 - 23:45:14: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/04/2019 - 23:45:14: [SM] Call stack trace:
L 11/04/2019 - 23:45:14: [SM]   [0] SetEntProp
L 11/04/2019 - 23:45:14: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/04/2019 - 23:45:36: [SM] Exception reported: Entity 9 (9) is invalid
L 11/04/2019 - 23:45:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/04/2019 - 23:45:36: [SM] Call stack trace:
L 11/04/2019 - 23:45:36: [SM]   [0] GetEntDataEnt2
L 11/04/2019 - 23:45:36: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/04/2019 - 23:45:37: Error log file session closed.
L 11/04/2019 - 23:47:13: SourceMod error session started
L 11/04/2019 - 23:47:13: Info (map "c2m1_highway") (file "errors_20191104.log")
L 11/04/2019 - 23:47:13: [CRASH] Accelerator uploaded crash dump: Crash ID: 3L2V-MQLW-K77F
