L 10/19/2019 - 01:14:28: SourceMod error session started
L 10/19/2019 - 01:14:28: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 01:14:28: Error log file session closed.
L 10/19/2019 - 01:26:54: SourceMod error session started
L 10/19/2019 - 01:26:54: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 01:26:54: [SM] Exception reported: Client index 289 is invalid
L 10/19/2019 - 01:26:54: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 01:26:54: [SM] Call stack trace:
L 10/19/2019 - 01:26:54: [SM]   [0] IsClientInGame
L 10/19/2019 - 01:26:54: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 01:26:54: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 01:28:26: Error log file session closed.
L 10/19/2019 - 01:33:24: SourceMod error session started
L 10/19/2019 - 01:33:24: Info (map "c2m2_fairgrounds") (file "errors_20191019.log")
L 10/19/2019 - 01:33:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 01:33:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 01:33:24: [SM] Call stack trace:
L 10/19/2019 - 01:33:24: [SM]   [0] SetEntProp
L 10/19/2019 - 01:33:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 01:46:54: Error log file session closed.
L 10/19/2019 - 01:47:12: SourceMod error session started
L 10/19/2019 - 01:47:12: Info (map "c2m3_coaster") (file "errors_20191019.log")
L 10/19/2019 - 01:47:12: [SM] Exception reported: Client 6 is not in game
L 10/19/2019 - 01:47:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 01:47:12: [SM] Call stack trace:
L 10/19/2019 - 01:47:12: [SM]   [0] GetClientTeam
L 10/19/2019 - 01:47:12: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 01:49:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 01:49:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 01:49:41: [SM] Call stack trace:
L 10/19/2019 - 01:49:41: [SM]   [0] SetEntProp
L 10/19/2019 - 01:49:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 01:53:14: [SM] Exception reported: Client 5 is not in game
L 10/19/2019 - 01:53:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 01:53:14: [SM] Call stack trace:
L 10/19/2019 - 01:53:14: [SM]   [0] GetClientTeam
L 10/19/2019 - 01:53:14: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 01:53:15: [SM] Exception reported: Entity 5 (5) is invalid
L 10/19/2019 - 01:53:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 01:53:15: [SM] Call stack trace:
L 10/19/2019 - 01:53:15: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 01:53:15: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 01:53:15: Error log file session closed.
L 10/19/2019 - 01:53:29: SourceMod error session started
L 10/19/2019 - 01:53:29: Info (map "c2m4_barns") (file "errors_20191019.log")
L 10/19/2019 - 01:53:29: [SM] Exception reported: Client 6 is not in game
L 10/19/2019 - 01:53:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 01:53:29: [SM] Call stack trace:
L 10/19/2019 - 01:53:29: [SM]   [0] GetClientTeam
L 10/19/2019 - 01:53:29: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 01:57:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 01:57:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 01:57:28: [SM] Call stack trace:
L 10/19/2019 - 01:57:28: [SM]   [0] SetEntProp
L 10/19/2019 - 01:57:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 02:05:13: [SM] Exception reported: Client index 183 is invalid
L 10/19/2019 - 02:05:13: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 02:05:13: [SM] Call stack trace:
L 10/19/2019 - 02:05:13: [SM]   [0] IsClientInGame
L 10/19/2019 - 02:05:13: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 02:05:13: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 02:05:13: [SM] Exception reported: Client index 183 is invalid
L 10/19/2019 - 02:05:13: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 02:05:13: [SM] Call stack trace:
L 10/19/2019 - 02:05:13: [SM]   [0] IsClientInGame
L 10/19/2019 - 02:05:13: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 02:05:13: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 02:05:19: [SM] Exception reported: Client index 183 is invalid
L 10/19/2019 - 02:05:19: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 02:05:19: [SM] Call stack trace:
L 10/19/2019 - 02:05:19: [SM]   [0] IsClientInGame
L 10/19/2019 - 02:05:19: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 02:05:19: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 02:06:36: [SM] Exception reported: Client 3 is not in game
L 10/19/2019 - 02:06:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 02:06:36: [SM] Call stack trace:
L 10/19/2019 - 02:06:36: [SM]   [0] GetClientTeam
L 10/19/2019 - 02:06:36: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 02:06:44: [SM] Exception reported: Entity 3 (3) is invalid
L 10/19/2019 - 02:06:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 02:06:44: [SM] Call stack trace:
L 10/19/2019 - 02:06:44: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 02:06:44: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 02:06:45: Error log file session closed.
L 10/19/2019 - 02:09:57: SourceMod error session started
L 10/19/2019 - 02:09:57: Info (map "c2m5_concert") (file "errors_20191019.log")
L 10/19/2019 - 02:09:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 02:09:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 02:09:57: [SM] Call stack trace:
L 10/19/2019 - 02:09:57: [SM]   [0] SetEntProp
L 10/19/2019 - 02:09:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 02:10:08: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 02:10:08: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 02:10:08: [SM] Call stack trace:
L 10/19/2019 - 02:10:08: [SM]   [0] SetEntProp
L 10/19/2019 - 02:10:08: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 02:10:09: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 02:10:09: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 02:10:09: [SM] Call stack trace:
L 10/19/2019 - 02:10:09: [SM]   [0] SetEntProp
L 10/19/2019 - 02:10:09: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 02:16:38: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 02:16:38: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 02:16:38: [SM] Call stack trace:
L 10/19/2019 - 02:16:38: [SM]   [0] SetEntProp
L 10/19/2019 - 02:16:38: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 02:17:09: [SM] Exception reported: Entity 5 (5) is invalid
L 10/19/2019 - 02:17:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 02:17:09: [SM] Call stack trace:
L 10/19/2019 - 02:17:09: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 02:17:09: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 02:18:20: [SM] Exception reported: Client index 507 is invalid
L 10/19/2019 - 02:18:20: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 02:18:20: [SM] Call stack trace:
L 10/19/2019 - 02:18:20: [SM]   [0] IsClientInGame
L 10/19/2019 - 02:18:20: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 02:18:20: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 02:27:59: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 02:27:59: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 02:27:59: [SM] Call stack trace:
L 10/19/2019 - 02:27:59: [SM]   [0] SetEntProp
L 10/19/2019 - 02:27:59: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 02:28:29: [SM] Exception reported: Entity 2 (2) is invalid
L 10/19/2019 - 02:28:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 02:28:29: [SM] Call stack trace:
L 10/19/2019 - 02:28:29: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 02:28:29: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 02:28:29: [SM] Exception reported: Entity 4 (4) is invalid
L 10/19/2019 - 02:28:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 02:28:29: [SM] Call stack trace:
L 10/19/2019 - 02:28:29: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 02:28:29: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 02:28:30: Error log file session closed.
L 10/19/2019 - 02:35:41: SourceMod error session started
L 10/19/2019 - 02:35:41: Info (map "c1m1_hotel") (file "errors_20191019.log")
L 10/19/2019 - 02:35:41: [SM] Exception reported: Client index 59 is invalid
L 10/19/2019 - 02:35:41: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 02:35:41: [SM] Call stack trace:
L 10/19/2019 - 02:35:41: [SM]   [0] IsClientInGame
L 10/19/2019 - 02:35:41: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 02:35:41: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 02:35:50: [SM] Exception reported: Client index 59 is invalid
L 10/19/2019 - 02:35:50: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 02:35:50: [SM] Call stack trace:
L 10/19/2019 - 02:35:50: [SM]   [0] IsClientInGame
L 10/19/2019 - 02:35:50: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 02:35:50: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 02:37:19: [SM] Exception reported: Entity 3 (3) is invalid
L 10/19/2019 - 02:37:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 02:37:19: [SM] Call stack trace:
L 10/19/2019 - 02:37:19: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 02:37:19: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 02:37:19: [SM] Exception reported: Client 8 is not in game
L 10/19/2019 - 02:37:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 02:37:19: [SM] Call stack trace:
L 10/19/2019 - 02:37:19: [SM]   [0] GetClientTeam
L 10/19/2019 - 02:37:19: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 02:37:19: Error log file session closed.
L 10/19/2019 - 03:02:25: SourceMod error session started
L 10/19/2019 - 03:02:25: Info (map "c1m3_mall") (file "errors_20191019.log")
L 10/19/2019 - 03:02:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:02:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:02:25: [SM] Call stack trace:
L 10/19/2019 - 03:02:25: [SM]   [0] SetEntProp
L 10/19/2019 - 03:02:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:03:44: Error log file session closed.
L 10/19/2019 - 03:05:42: SourceMod error session started
L 10/19/2019 - 03:05:42: Info (map "c1m4_atrium") (file "errors_20191019.log")
L 10/19/2019 - 03:05:42: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:42: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:42: [SM] Call stack trace:
L 10/19/2019 - 03:05:42: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:42: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:42: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:47: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:47: [SM] Call stack trace:
L 10/19/2019 - 03:05:47: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:48: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:48: [SM] Call stack trace:
L 10/19/2019 - 03:05:48: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:05:48: [SM] Exception reported: Client index 273 is invalid
L 10/19/2019 - 03:05:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:05:48: [SM] Call stack trace:
L 10/19/2019 - 03:05:48: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:05:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:05:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:08:09: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:08:09: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:08:09: [SM] Call stack trace:
L 10/19/2019 - 03:08:09: [SM]   [0] SetEntProp
L 10/19/2019 - 03:08:09: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:08:42: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:08:42: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:08:42: [SM] Call stack trace:
L 10/19/2019 - 03:08:42: [SM]   [0] SetEntProp
L 10/19/2019 - 03:08:42: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:08:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:08:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:08:57: [SM] Call stack trace:
L 10/19/2019 - 03:08:57: [SM]   [0] SetEntProp
L 10/19/2019 - 03:08:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:13:16: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:16: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:16: [SM] Call stack trace:
L 10/19/2019 - 03:13:16: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:16: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:16: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:21: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:21: [SM] Call stack trace:
L 10/19/2019 - 03:13:21: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:26: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:26: [SM] Call stack trace:
L 10/19/2019 - 03:13:26: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:26: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:26: [SM] Call stack trace:
L 10/19/2019 - 03:13:26: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:26: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:26: [SM] Call stack trace:
L 10/19/2019 - 03:13:26: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:26: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:26: [SM] Call stack trace:
L 10/19/2019 - 03:13:26: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:26: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:26: [SM] Call stack trace:
L 10/19/2019 - 03:13:26: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:26: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:26: [SM] Call stack trace:
L 10/19/2019 - 03:13:26: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:13:26: [SM] Exception reported: Client index 151 is invalid
L 10/19/2019 - 03:13:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:13:26: [SM] Call stack trace:
L 10/19/2019 - 03:13:26: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:13:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:13:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:14:19: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:14:19: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:14:19: [SM] Call stack trace:
L 10/19/2019 - 03:14:19: [SM]   [0] SetEntProp
L 10/19/2019 - 03:14:19: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:15:01: [SM] Exception reported: Entity 1 (1) is invalid
L 10/19/2019 - 03:15:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 03:15:01: [SM] Call stack trace:
L 10/19/2019 - 03:15:01: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 03:15:01: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 03:15:02: Error log file session closed.
L 10/19/2019 - 03:20:20: SourceMod error session started
L 10/19/2019 - 03:20:20: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 03:20:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:20:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:20:20: [SM] Call stack trace:
L 10/19/2019 - 03:20:20: [SM]   [0] SetEntProp
L 10/19/2019 - 03:20:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:20:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:20:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:20:20: [SM] Call stack trace:
L 10/19/2019 - 03:20:20: [SM]   [0] SetEntProp
L 10/19/2019 - 03:20:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:23:53: [SM] Exception reported: Entity 3 (3) is invalid
L 10/19/2019 - 03:23:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 03:23:53: [SM] Call stack trace:
L 10/19/2019 - 03:23:53: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 03:23:53: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 03:23:54: Error log file session closed.
L 10/19/2019 - 03:30:05: SourceMod error session started
L 10/19/2019 - 03:30:05: Info (map "c2m2_fairgrounds") (file "errors_20191019.log")
L 10/19/2019 - 03:30:05: [SM] Exception reported: Client index 416 is invalid
L 10/19/2019 - 03:30:05: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 03:30:05: [SM] Call stack trace:
L 10/19/2019 - 03:30:05: [SM]   [0] IsClientInGame
L 10/19/2019 - 03:30:05: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 03:30:05: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 03:41:11: Error log file session closed.
L 10/19/2019 - 03:52:23: SourceMod error session started
L 10/19/2019 - 03:52:23: Info (map "c2m3_coaster") (file "errors_20191019.log")
L 10/19/2019 - 03:52:23: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:52:23: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:52:23: [SM] Call stack trace:
L 10/19/2019 - 03:52:23: [SM]   [0] SetEntProp
L 10/19/2019 - 03:52:23: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 03:53:07: Error log file session closed.
L 10/19/2019 - 03:53:09: SourceMod error session started
L 10/19/2019 - 03:53:09: Info (map "c2m4_barns") (file "errors_20191019.log")
L 10/19/2019 - 03:53:09: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:09: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:09: [SM] Call stack trace:
L 10/19/2019 - 03:53:09: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:09: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:10: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:10: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:10: [SM] Call stack trace:
L 10/19/2019 - 03:53:10: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:10: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:11: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:11: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:11: [SM] Call stack trace:
L 10/19/2019 - 03:53:11: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:11: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:12: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:12: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:12: [SM] Call stack trace:
L 10/19/2019 - 03:53:12: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:12: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:13: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:13: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:13: [SM] Call stack trace:
L 10/19/2019 - 03:53:13: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:13: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:14: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:14: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:14: [SM] Call stack trace:
L 10/19/2019 - 03:53:14: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:14: [SM]   [1] Line 208, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::ResetJumpRockCooldown
L 10/19/2019 - 03:53:14: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:14: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:14: [SM] Call stack trace:
L 10/19/2019 - 03:53:14: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:14: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:15: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:15: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:15: [SM] Call stack trace:
L 10/19/2019 - 03:53:15: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:15: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:16: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:16: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:16: [SM] Call stack trace:
L 10/19/2019 - 03:53:16: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:16: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:53:17: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 03:53:17: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/19/2019 - 03:53:17: [SM] Call stack trace:
L 10/19/2019 - 03:53:17: [SM]   [0] IsPlayerAlive
L 10/19/2019 - 03:53:17: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/19/2019 - 03:57:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 03:57:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 03:57:01: [SM] Call stack trace:
L 10/19/2019 - 03:57:01: [SM]   [0] SetEntProp
L 10/19/2019 - 03:57:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 04:03:28: [SM] Exception reported: Entity 3 (3) is invalid
L 10/19/2019 - 04:03:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:03:28: [SM] Call stack trace:
L 10/19/2019 - 04:03:28: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 04:03:28: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 04:03:29: Error log file session closed.
L 10/19/2019 - 04:05:09: SourceMod error session started
L 10/19/2019 - 04:05:09: Info (map "c2m5_concert") (file "errors_20191019.log")
L 10/19/2019 - 04:05:09: [SM] Exception reported: Client index 387 is invalid
L 10/19/2019 - 04:05:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 04:05:09: [SM] Call stack trace:
L 10/19/2019 - 04:05:09: [SM]   [0] IsClientInGame
L 10/19/2019 - 04:05:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 04:05:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 04:12:57: [SM] Exception reported: Entity 10 (10) is invalid
L 10/19/2019 - 04:12:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:12:57: [SM] Call stack trace:
L 10/19/2019 - 04:12:57: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 04:12:57: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 04:14:07: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 04:14:07: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 04:14:07: [SM] Call stack trace:
L 10/19/2019 - 04:14:07: [SM]   [0] SetEntProp
L 10/19/2019 - 04:14:07: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 04:21:58: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/19/2019 - 04:21:58: [SM] Blaming: l4d2_playstats.smx
L 10/19/2019 - 04:21:58: [SM] Call stack trace:
L 10/19/2019 - 04:21:58: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/19/2019 - 04:21:58: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/19/2019 - 04:21:58: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/19/2019 - 04:21:58: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/19/2019 - 04:22:13: Error log file session closed.
L 10/19/2019 - 04:22:16: SourceMod error session started
L 10/19/2019 - 04:22:16: Info (map "c1m1_hotel") (file "errors_20191019.log")
L 10/19/2019 - 04:22:16: [SM] Exception reported: Client 9 is not in game
L 10/19/2019 - 04:22:16: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:22:16: [SM] Call stack trace:
L 10/19/2019 - 04:22:16: [SM]   [0] GetClientTeam
L 10/19/2019 - 04:22:16: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 04:24:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 04:24:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 04:24:16: [SM] Call stack trace:
L 10/19/2019 - 04:24:16: [SM]   [0] SetEntProp
L 10/19/2019 - 04:24:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 04:24:32: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 04:24:32: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 04:24:32: [SM] Call stack trace:
L 10/19/2019 - 04:24:32: [SM]   [0] SetEntProp
L 10/19/2019 - 04:24:32: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 04:26:43: [SM] Exception reported: Client 8 is not in game
L 10/19/2019 - 04:26:43: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:26:43: [SM] Call stack trace:
L 10/19/2019 - 04:26:43: [SM]   [0] GetClientTeam
L 10/19/2019 - 04:26:43: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 04:27:18: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 04:27:18: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 04:27:18: [SM] Call stack trace:
L 10/19/2019 - 04:27:18: [SM]   [0] SetEntProp
L 10/19/2019 - 04:27:18: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 04:32:59: [SM] Exception reported: Entity 2 (2) is invalid
L 10/19/2019 - 04:32:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:32:59: [SM] Call stack trace:
L 10/19/2019 - 04:32:59: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 04:32:59: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 04:32:59: Error log file session closed.
L 10/19/2019 - 04:46:04: SourceMod error session started
L 10/19/2019 - 04:46:04: Info (map "c1m2_streets") (file "errors_20191019.log")
L 10/19/2019 - 04:46:04: [SM] Exception reported: Client 1 is not in game
L 10/19/2019 - 04:46:04: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:46:04: [SM] Call stack trace:
L 10/19/2019 - 04:46:04: [SM]   [0] GetClientTeam
L 10/19/2019 - 04:46:04: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 04:46:04: [SM] Exception reported: Entity 4 (4) is invalid
L 10/19/2019 - 04:46:04: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:46:04: [SM] Call stack trace:
L 10/19/2019 - 04:46:04: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 04:46:04: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 04:46:05: Error log file session closed.
L 10/19/2019 - 04:49:47: SourceMod error session started
L 10/19/2019 - 04:49:47: Info (map "c5m1_waterfront") (file "errors_20191019.log")
L 10/19/2019 - 04:49:47: [SM] Exception reported: Entity 6 (6) is invalid
L 10/19/2019 - 04:49:47: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 04:49:47: [SM] Call stack trace:
L 10/19/2019 - 04:49:47: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 04:49:47: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 04:50:31: SourceMod error session started
L 10/19/2019 - 04:50:31: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 04:50:31: [CRASH] Accelerator uploaded crash dump: Crash ID: 5XCD-OKVD-NJPW
L 10/19/2019 - 17:51:11: SourceMod error session started
L 10/19/2019 - 17:51:11: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 17:51:11: [SM] Exception reported: Client index 298 is invalid
L 10/19/2019 - 17:51:11: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 17:51:11: [SM] Call stack trace:
L 10/19/2019 - 17:51:11: [SM]   [0] IsClientInGame
L 10/19/2019 - 17:51:11: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 17:51:11: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 19:29:44: Error log file session closed.
L 10/19/2019 - 20:01:19: SourceMod error session started
L 10/19/2019 - 20:01:19: Info (map "c5m3_cemetery") (file "errors_20191019.log")
L 10/19/2019 - 20:01:19: [SM] Exception reported: Client 7 is not in game
L 10/19/2019 - 20:01:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:01:19: [SM] Call stack trace:
L 10/19/2019 - 20:01:19: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:01:19: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:10:20: [SM] Exception reported: Client index 161 is invalid
L 10/19/2019 - 20:10:20: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 20:10:20: [SM] Call stack trace:
L 10/19/2019 - 20:10:20: [SM]   [0] IsClientInGame
L 10/19/2019 - 20:10:20: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 20:10:20: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 20:10:20: [SM] Exception reported: Client index 161 is invalid
L 10/19/2019 - 20:10:20: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 20:10:20: [SM] Call stack trace:
L 10/19/2019 - 20:10:20: [SM]   [0] IsClientInGame
L 10/19/2019 - 20:10:20: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 20:10:20: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 20:13:36: [SM] Exception reported: Entity 1 (1) is invalid
L 10/19/2019 - 20:13:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:13:36: [SM] Call stack trace:
L 10/19/2019 - 20:13:36: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 20:13:36: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:13:36: [SM] Exception reported: Entity 2 (2) is invalid
L 10/19/2019 - 20:13:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:13:36: [SM] Call stack trace:
L 10/19/2019 - 20:13:36: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 20:13:36: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:13:36: [SM] Exception reported: Client 9 is not in game
L 10/19/2019 - 20:13:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:13:36: [SM] Call stack trace:
L 10/19/2019 - 20:13:36: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:13:36: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:13:37: Error log file session closed.
L 10/19/2019 - 20:17:52: SourceMod error session started
L 10/19/2019 - 20:17:52: Info (map "c5m4_quarter") (file "errors_20191019.log")
L 10/19/2019 - 20:17:52: [SM] Exception reported: Client 8 is not in game
L 10/19/2019 - 20:17:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:17:52: [SM] Call stack trace:
L 10/19/2019 - 20:17:52: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:17:52: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:18:05: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 20:18:05: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 20:18:05: [SM] Call stack trace:
L 10/19/2019 - 20:18:05: [SM]   [0] SetEntProp
L 10/19/2019 - 20:18:05: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 20:18:08: [SM] Exception reported: Client 6 is not in game
L 10/19/2019 - 20:18:08: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:18:08: [SM] Call stack trace:
L 10/19/2019 - 20:18:08: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:18:08: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:32:31: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/19/2019 - 20:32:31: [SM] Blaming: l4d2_playstats.smx
L 10/19/2019 - 20:32:31: [SM] Call stack trace:
L 10/19/2019 - 20:32:31: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/19/2019 - 20:32:31: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/19/2019 - 20:32:31: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/19/2019 - 20:32:31: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/19/2019 - 20:32:50: [SM] Exception reported: Entity 3 (3) is invalid
L 10/19/2019 - 20:32:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:32:50: [SM] Call stack trace:
L 10/19/2019 - 20:32:50: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 20:32:50: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:32:50: [SM] Exception reported: Entity 1 (1) is invalid
L 10/19/2019 - 20:32:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:32:50: [SM] Call stack trace:
L 10/19/2019 - 20:32:50: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 20:32:50: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:32:51: Error log file session closed.
L 10/19/2019 - 20:36:31: SourceMod error session started
L 10/19/2019 - 20:36:31: Info (map "c5m5_bridge") (file "errors_20191019.log")
L 10/19/2019 - 20:36:31: [SM] Exception reported: Client 6 is not in game
L 10/19/2019 - 20:36:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:36:31: [SM] Call stack trace:
L 10/19/2019 - 20:36:31: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:36:31: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:41:29: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 20:41:29: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 20:41:29: [SM] Call stack trace:
L 10/19/2019 - 20:41:29: [SM]   [0] SetEntProp
L 10/19/2019 - 20:41:29: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 20:42:09: [SM] Exception reported: Client 6 is not in game
L 10/19/2019 - 20:42:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:42:09: [SM] Call stack trace:
L 10/19/2019 - 20:42:09: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:42:09: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:42:09: [SM] Exception reported: Client 10 is not in game
L 10/19/2019 - 20:42:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:42:09: [SM] Call stack trace:
L 10/19/2019 - 20:42:09: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:42:09: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:42:10: Error log file session closed.
L 10/19/2019 - 20:47:47: SourceMod error session started
L 10/19/2019 - 20:47:47: Info (map "c3m1_plankcountry") (file "errors_20191019.log")
L 10/19/2019 - 20:47:47: [SM] Exception reported: Entity 10 (10) is invalid
L 10/19/2019 - 20:47:47: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:47:47: [SM] Call stack trace:
L 10/19/2019 - 20:47:47: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 20:47:47: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:48:14: [SM] Exception reported: Client 9 is not in game
L 10/19/2019 - 20:48:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:48:14: [SM] Call stack trace:
L 10/19/2019 - 20:48:14: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:48:14: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:53:25: [SM] Exception reported: Entity 3 (3) is invalid
L 10/19/2019 - 20:53:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:53:25: [SM] Call stack trace:
L 10/19/2019 - 20:53:25: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 20:53:25: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 20:53:25: [SM] Exception reported: Client 3 is not in game
L 10/19/2019 - 20:53:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:53:25: [SM] Call stack trace:
L 10/19/2019 - 20:53:25: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:53:25: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:53:25: [SM] Exception reported: Client 8 is not in game
L 10/19/2019 - 20:53:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 20:53:25: [SM] Call stack trace:
L 10/19/2019 - 20:53:25: [SM]   [0] GetClientTeam
L 10/19/2019 - 20:53:25: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 20:53:26: Error log file session closed.
L 10/19/2019 - 21:03:22: SourceMod error session started
L 10/19/2019 - 21:03:22: Info (map "c3m2_swamp") (file "errors_20191019.log")
L 10/19/2019 - 21:03:22: [SM] Exception reported: Client 5 is not in game
L 10/19/2019 - 21:03:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:03:22: [SM] Call stack trace:
L 10/19/2019 - 21:03:22: [SM]   [0] GetClientTeam
L 10/19/2019 - 21:03:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 21:03:23: Error log file session closed.
L 10/19/2019 - 21:07:13: SourceMod error session started
L 10/19/2019 - 21:07:13: Info (map "c3m3_shantytown") (file "errors_20191019.log")
L 10/19/2019 - 21:07:13: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 21:07:13: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 21:07:13: [SM] Call stack trace:
L 10/19/2019 - 21:07:13: [SM]   [0] SetEntProp
L 10/19/2019 - 21:07:13: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 21:11:06: [SM] Exception reported: Entity 10 (10) is invalid
L 10/19/2019 - 21:11:06: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:11:06: [SM] Call stack trace:
L 10/19/2019 - 21:11:06: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 21:11:06: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 21:11:21: Error log file session closed.
L 10/19/2019 - 21:22:31: SourceMod error session started
L 10/19/2019 - 21:22:31: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 21:22:31: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 21:22:31: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 21:22:31: [SM] Call stack trace:
L 10/19/2019 - 21:22:31: [SM]   [0] SetEntProp
L 10/19/2019 - 21:22:31: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 21:25:14: Error log file session closed.
L 10/19/2019 - 21:37:46: SourceMod error session started
L 10/19/2019 - 21:37:46: Info (map "c2m2_fairgrounds") (file "errors_20191019.log")
L 10/19/2019 - 21:37:46: [SM] Exception reported: Client index 339 is invalid
L 10/19/2019 - 21:37:46: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 21:37:46: [SM] Call stack trace:
L 10/19/2019 - 21:37:46: [SM]   [0] IsClientInGame
L 10/19/2019 - 21:37:46: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 21:37:46: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 21:38:47: [SM] Exception reported: Entity 9 (9) is invalid
L 10/19/2019 - 21:38:47: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:38:47: [SM] Call stack trace:
L 10/19/2019 - 21:38:47: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 21:38:47: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 21:38:54: [SM] Exception reported: Entity 8 (8) is invalid
L 10/19/2019 - 21:38:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:38:54: [SM] Call stack trace:
L 10/19/2019 - 21:38:54: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 21:38:54: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 21:38:54: [SM] Exception reported: Client 8 is not in game
L 10/19/2019 - 21:38:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:38:54: [SM] Call stack trace:
L 10/19/2019 - 21:38:54: [SM]   [0] GetClientTeam
L 10/19/2019 - 21:38:54: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 21:38:54: Error log file session closed.
L 10/19/2019 - 21:41:13: SourceMod error session started
L 10/19/2019 - 21:41:13: Info (map "c2m3_coaster") (file "errors_20191019.log")
L 10/19/2019 - 21:41:13: [SM] Exception reported: Entity 6 (6) is invalid
L 10/19/2019 - 21:41:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:41:13: [SM] Call stack trace:
L 10/19/2019 - 21:41:13: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 21:41:13: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/19/2019 - 21:43:23: [SM] Exception reported: Entity 5 (5) is invalid
L 10/19/2019 - 21:43:23: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:43:23: [SM] Call stack trace:
L 10/19/2019 - 21:43:23: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 21:43:23: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 21:43:35: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 21:43:35: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 21:43:35: [SM] Call stack trace:
L 10/19/2019 - 21:43:35: [SM]   [0] SetEntProp
L 10/19/2019 - 21:43:35: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 21:45:07: Error log file session closed.
L 10/19/2019 - 21:51:17: SourceMod error session started
L 10/19/2019 - 21:51:17: Info (map "c2m4_barns") (file "errors_20191019.log")
L 10/19/2019 - 21:51:17: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/19/2019 - 21:51:17: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/19/2019 - 21:51:17: [SM] Call stack trace:
L 10/19/2019 - 21:51:17: [SM]   [0] SetEntProp
L 10/19/2019 - 21:51:17: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/19/2019 - 21:53:12: [SM] Exception reported: Client index 169 is invalid
L 10/19/2019 - 21:53:12: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 21:53:12: [SM] Call stack trace:
L 10/19/2019 - 21:53:12: [SM]   [0] IsClientInGame
L 10/19/2019 - 21:53:12: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 21:53:12: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 21:55:24: Error log file session closed.
L 10/19/2019 - 21:57:14: SourceMod error session started
L 10/19/2019 - 21:57:14: Info (map "c2m5_concert") (file "errors_20191019.log")
L 10/19/2019 - 21:57:14: [SM] Exception reported: Client index 521 is invalid
L 10/19/2019 - 21:57:14: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 21:57:14: [SM] Call stack trace:
L 10/19/2019 - 21:57:14: [SM]   [0] IsClientInGame
L 10/19/2019 - 21:57:14: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 21:57:14: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 21:57:28: [SM] Exception reported: Client index 521 is invalid
L 10/19/2019 - 21:57:28: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/19/2019 - 21:57:28: [SM] Call stack trace:
L 10/19/2019 - 21:57:28: [SM]   [0] IsClientInGame
L 10/19/2019 - 21:57:28: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/19/2019 - 21:57:28: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/19/2019 - 21:59:46: [SM] Exception reported: Entity 3 (3) is invalid
L 10/19/2019 - 21:59:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 21:59:46: [SM] Call stack trace:
L 10/19/2019 - 21:59:46: [SM]   [0] GetEntDataEnt2
L 10/19/2019 - 21:59:46: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/19/2019 - 21:59:47: Error log file session closed.
L 10/19/2019 - 22:00:52: SourceMod error session started
L 10/19/2019 - 22:00:52: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 22:00:52: [CRASH] Accelerator uploaded crash dump: Crash ID: IURR-RVKS-ST3M
L 10/19/2019 - 23:48:38: Error log file session closed.
L 10/19/2019 - 23:56:45: SourceMod error session started
L 10/19/2019 - 23:56:45: Info (map "c2m1_highway") (file "errors_20191019.log")
L 10/19/2019 - 23:56:45: [SM] Exception reported: Client 8 is not in game
L 10/19/2019 - 23:56:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/19/2019 - 23:56:45: [SM] Call stack trace:
L 10/19/2019 - 23:56:45: [SM]   [0] GetClientTeam
L 10/19/2019 - 23:56:45: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
