L 10/28/2019 - 01:04:36: SourceMod error session started
L 10/28/2019 - 01:04:36: Info (map "c8m1_apartment") (file "errors_20191028.log")
L 10/28/2019 - 01:04:36: Error log file session closed.
L 10/28/2019 - 01:06:25: SourceMod error session started
L 10/28/2019 - 01:06:25: Info (map "c8m1_apartment") (file "errors_20191028.log")
L 10/28/2019 - 01:06:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 01:06:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 01:06:25: [SM] Call stack trace:
L 10/28/2019 - 01:06:25: [SM]   [0] SetEntProp
L 10/28/2019 - 01:06:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 01:08:59: Error log file session closed.
L 10/28/2019 - 01:17:02: SourceMod error session started
L 10/28/2019 - 01:17:02: Info (map "c2m1_highway") (file "errors_20191028.log")
L 10/28/2019 - 01:17:02: [CRASH] Accelerator uploaded crash dump: Crash ID: TESH-FIIO-4EG2
L 10/28/2019 - 14:07:22: Error log file session closed.
L 10/28/2019 - 14:07:25: SourceMod error session started
L 10/28/2019 - 14:07:25: Info (map "c2m1_highway") (file "errors_20191028.log")
L 10/28/2019 - 14:07:25: [SM] Exception reported: Client 1 is not in game
L 10/28/2019 - 14:07:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 14:07:25: [SM] Call stack trace:
L 10/28/2019 - 14:07:25: [SM]   [0] GetClientTeam
L 10/28/2019 - 14:07:25: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 14:17:48: [SM] Exception reported: Client index 256 is invalid
L 10/28/2019 - 14:17:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 14:17:48: [SM] Call stack trace:
L 10/28/2019 - 14:17:48: [SM]   [0] IsClientInGame
L 10/28/2019 - 14:17:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 14:17:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 14:21:26: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 14:21:26: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 14:21:26: [SM] Call stack trace:
L 10/28/2019 - 14:21:26: [SM]   [0] SetEntProp
L 10/28/2019 - 14:21:26: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 14:23:11: [SM] Exception reported: Entity 6 (6) is invalid
L 10/28/2019 - 14:23:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 14:23:11: [SM] Call stack trace:
L 10/28/2019 - 14:23:11: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 14:23:11: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 14:23:19: [SM] Exception reported: Entity 6 (6) is invalid
L 10/28/2019 - 14:23:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 14:23:19: [SM] Call stack trace:
L 10/28/2019 - 14:23:19: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 14:23:19: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 14:23:19: Error log file session closed.
L 10/28/2019 - 14:25:18: SourceMod error session started
L 10/28/2019 - 14:25:18: Info (map "c2m2_fairgrounds") (file "errors_20191028.log")
L 10/28/2019 - 14:25:18: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/28/2019 - 14:25:18: [SM] Blaming: l4d2_jockey_skeet.smx
L 10/28/2019 - 14:25:18: [SM] Call stack trace:
L 10/28/2019 - 14:25:18: [SM]   [0] GetEdictClassname
L 10/28/2019 - 14:25:18: [SM]   [1] Line 141, plugin/EUplugins/march/l4d2_jockey_skeet.sp::IsShotgun
L 10/28/2019 - 14:25:18: [SM]   [2] Line 73, plugin/EUplugins/march/l4d2_jockey_skeet.sp::OnTakeDamage
L 10/28/2019 - 14:27:21: [SM] Exception reported: Client 2 is not in game
L 10/28/2019 - 14:27:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 14:27:21: [SM] Call stack trace:
L 10/28/2019 - 14:27:21: [SM]   [0] GetClientTeam
L 10/28/2019 - 14:27:21: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 14:31:03: [SM] Exception reported: Client index 372 is invalid
L 10/28/2019 - 14:31:03: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 14:31:03: [SM] Call stack trace:
L 10/28/2019 - 14:31:03: [SM]   [0] IsClientInGame
L 10/28/2019 - 14:31:03: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 14:31:03: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 14:31:35: [SM] Exception reported: Entity 6 (6) is invalid
L 10/28/2019 - 14:31:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 14:31:35: [SM] Call stack trace:
L 10/28/2019 - 14:31:35: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 14:31:35: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 14:38:29: Error log file session closed.
L 10/28/2019 - 14:54:07: SourceMod error session started
L 10/28/2019 - 14:54:07: Info (map "c2m4_barns") (file "errors_20191028.log")
L 10/28/2019 - 14:54:07: [SM] Exception reported: Client index 582 is invalid
L 10/28/2019 - 14:54:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 14:54:07: [SM] Call stack trace:
L 10/28/2019 - 14:54:07: [SM]   [0] IsClientInGame
L 10/28/2019 - 14:54:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 14:54:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 15:00:45: [SM] Exception reported: Entity 8 (8) is invalid
L 10/28/2019 - 15:00:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:00:45: [SM] Call stack trace:
L 10/28/2019 - 15:00:45: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 15:00:45: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 15:00:46: Error log file session closed.
L 10/28/2019 - 15:01:45: SourceMod error session started
L 10/28/2019 - 15:01:45: Info (map "c2m5_concert") (file "errors_20191028.log")
L 10/28/2019 - 15:01:45: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 15:01:45: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 15:01:45: [SM] Call stack trace:
L 10/28/2019 - 15:01:45: [SM]   [0] SetEntProp
L 10/28/2019 - 15:01:45: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 15:07:44: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 15:07:44: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 15:07:44: [SM] Call stack trace:
L 10/28/2019 - 15:07:44: [SM]   [0] SetEntProp
L 10/28/2019 - 15:07:44: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 15:08:09: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 15:08:09: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 15:08:09: [SM] Call stack trace:
L 10/28/2019 - 15:08:09: [SM]   [0] SetEntProp
L 10/28/2019 - 15:08:09: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 15:08:44: [SM] Exception reported: Entity 10 (10) is invalid
L 10/28/2019 - 15:08:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:08:44: [SM] Call stack trace:
L 10/28/2019 - 15:08:44: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 15:08:44: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 15:08:46: [SM] Exception reported: Client 8 is not in game
L 10/28/2019 - 15:08:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:08:46: [SM] Call stack trace:
L 10/28/2019 - 15:08:46: [SM]   [0] GetClientTeam
L 10/28/2019 - 15:08:46: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 15:08:46: [SM] Exception reported: Entity 4 (4) is invalid
L 10/28/2019 - 15:08:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:08:46: [SM] Call stack trace:
L 10/28/2019 - 15:08:46: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 15:08:46: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 15:08:49: Error log file session closed.
L 10/28/2019 - 15:16:28: SourceMod error session started
L 10/28/2019 - 15:16:28: Info (map "c4m2_sugarmill_a") (file "errors_20191028.log")
L 10/28/2019 - 15:16:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 15:16:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 15:16:28: [SM] Call stack trace:
L 10/28/2019 - 15:16:28: [SM]   [0] SetEntProp
L 10/28/2019 - 15:16:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 15:22:45: [SM] Exception reported: Client index 49 is invalid
L 10/28/2019 - 15:22:45: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 15:22:45: [SM] Call stack trace:
L 10/28/2019 - 15:22:45: [SM]   [0] IsClientInGame
L 10/28/2019 - 15:22:45: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 15:22:45: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 15:25:14: [SM] Exception reported: Entity 3 (3) is invalid
L 10/28/2019 - 15:25:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:25:14: [SM] Call stack trace:
L 10/28/2019 - 15:25:14: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 15:25:14: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 15:25:14: [SM] Exception reported: Entity 4 (4) is invalid
L 10/28/2019 - 15:25:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:25:14: [SM] Call stack trace:
L 10/28/2019 - 15:25:14: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 15:25:14: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 15:25:15: Error log file session closed.
L 10/28/2019 - 15:28:55: SourceMod error session started
L 10/28/2019 - 15:28:55: Info (map "c4m3_sugarmill_b") (file "errors_20191028.log")
L 10/28/2019 - 15:28:55: [SM] Exception reported: Client index 123 is invalid
L 10/28/2019 - 15:28:55: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 15:28:55: [SM] Call stack trace:
L 10/28/2019 - 15:28:55: [SM]   [0] IsClientInGame
L 10/28/2019 - 15:28:55: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 15:28:55: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 15:30:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 15:30:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 15:30:55: [SM] Call stack trace:
L 10/28/2019 - 15:30:55: [SM]   [0] SetEntProp
L 10/28/2019 - 15:30:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 15:35:11: [SM] Exception reported: Entity 3 (3) is invalid
L 10/28/2019 - 15:35:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:35:11: [SM] Call stack trace:
L 10/28/2019 - 15:35:11: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 15:35:11: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 15:39:14: Error log file session closed.
L 10/28/2019 - 15:43:36: SourceMod error session started
L 10/28/2019 - 15:43:36: Info (map "c4m4_milltown_b") (file "errors_20191028.log")
L 10/28/2019 - 15:43:36: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 15:43:36: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 15:43:36: [SM] Call stack trace:
L 10/28/2019 - 15:43:36: [SM]   [0] SetEntProp
L 10/28/2019 - 15:43:36: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 15:48:10: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/28/2019 - 15:48:10: [SM] Blaming: l4d2_jockey_skeet.smx
L 10/28/2019 - 15:48:10: [SM] Call stack trace:
L 10/28/2019 - 15:48:10: [SM]   [0] GetEdictClassname
L 10/28/2019 - 15:48:10: [SM]   [1] Line 141, plugin/EUplugins/march/l4d2_jockey_skeet.sp::IsShotgun
L 10/28/2019 - 15:48:10: [SM]   [2] Line 73, plugin/EUplugins/march/l4d2_jockey_skeet.sp::OnTakeDamage
L 10/28/2019 - 15:53:28: [SM] Exception reported: Entity 1 (1) is invalid
L 10/28/2019 - 15:53:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:53:28: [SM] Call stack trace:
L 10/28/2019 - 15:53:28: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 15:53:28: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 15:53:28: [SM] Exception reported: Client 5 is not in game
L 10/28/2019 - 15:53:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 15:53:28: [SM] Call stack trace:
L 10/28/2019 - 15:53:28: [SM]   [0] GetClientTeam
L 10/28/2019 - 15:53:28: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 15:53:30: Error log file session closed.
L 10/28/2019 - 16:19:45: SourceMod error session started
L 10/28/2019 - 16:19:45: Info (map "c1m2_streets") (file "errors_20191028.log")
L 10/28/2019 - 16:19:45: [SM] Exception reported: Entity 6 (6) is invalid
L 10/28/2019 - 16:19:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:19:45: [SM] Call stack trace:
L 10/28/2019 - 16:19:45: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:19:45: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 16:19:45: [SM] Exception reported: Client 6 is not in game
L 10/28/2019 - 16:19:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:19:45: [SM] Call stack trace:
L 10/28/2019 - 16:19:45: [SM]   [0] GetClientTeam
L 10/28/2019 - 16:19:45: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 16:19:45: Error log file session closed.
L 10/28/2019 - 16:21:13: SourceMod error session started
L 10/28/2019 - 16:21:13: Info (map "c1m2_streets") (file "errors_20191028.log")
L 10/28/2019 - 16:21:13: [SM] Exception reported: Client index 268 is invalid
L 10/28/2019 - 16:21:13: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 16:21:13: [SM] Call stack trace:
L 10/28/2019 - 16:21:13: [SM]   [0] IsClientInGame
L 10/28/2019 - 16:21:13: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 16:21:13: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 16:28:54: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 16:28:54: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 16:28:54: [SM] Call stack trace:
L 10/28/2019 - 16:28:54: [SM]   [0] SetEntProp
L 10/28/2019 - 16:28:54: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 16:29:14: [SM] Exception reported: Entity 9 (9) is invalid
L 10/28/2019 - 16:29:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:29:14: [SM] Call stack trace:
L 10/28/2019 - 16:29:14: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:29:14: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 16:29:14: [SM] Exception reported: Entity 9 (9) is invalid
L 10/28/2019 - 16:29:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:29:14: [SM] Call stack trace:
L 10/28/2019 - 16:29:14: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:29:14: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 16:29:30: [SM] Exception reported: Entity 9 (9) is invalid
L 10/28/2019 - 16:29:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:29:30: [SM] Call stack trace:
L 10/28/2019 - 16:29:30: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:29:30: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 16:29:32: Error log file session closed.
L 10/28/2019 - 16:39:56: SourceMod error session started
L 10/28/2019 - 16:39:56: Info (map "c1m3_mall") (file "errors_20191028.log")
L 10/28/2019 - 16:39:56: [SM] Exception reported: Entity 12 (12) is invalid
L 10/28/2019 - 16:39:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:39:56: [SM] Call stack trace:
L 10/28/2019 - 16:39:56: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:39:56: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 16:39:56: [SM] Exception reported: Entity 12 (12) is invalid
L 10/28/2019 - 16:39:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:39:56: [SM] Call stack trace:
L 10/28/2019 - 16:39:56: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:39:56: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 16:40:50: Error log file session closed.
L 10/28/2019 - 16:43:50: SourceMod error session started
L 10/28/2019 - 16:43:50: Info (map "c1m4_atrium") (file "errors_20191028.log")
L 10/28/2019 - 16:43:50: [SM] Exception reported: Client index 415 is invalid
L 10/28/2019 - 16:43:50: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 16:43:50: [SM] Call stack trace:
L 10/28/2019 - 16:43:50: [SM]   [0] IsClientInGame
L 10/28/2019 - 16:43:50: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 16:43:50: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 16:43:50: [SM] Exception reported: Client index 415 is invalid
L 10/28/2019 - 16:43:50: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 16:43:50: [SM] Call stack trace:
L 10/28/2019 - 16:43:50: [SM]   [0] IsClientInGame
L 10/28/2019 - 16:43:50: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 16:43:50: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 16:44:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 16:44:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 16:44:28: [SM] Call stack trace:
L 10/28/2019 - 16:44:28: [SM]   [0] SetEntProp
L 10/28/2019 - 16:44:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 16:45:06: [SM] Exception reported: Entity 2 (2) is invalid
L 10/28/2019 - 16:45:06: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:45:06: [SM] Call stack trace:
L 10/28/2019 - 16:45:06: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:45:06: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 16:47:34: [SM] Exception reported: Entity 4 (4) is invalid
L 10/28/2019 - 16:47:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:47:34: [SM] Call stack trace:
L 10/28/2019 - 16:47:34: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 16:47:34: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 16:47:35: Error log file session closed.
L 10/28/2019 - 16:47:58: SourceMod error session started
L 10/28/2019 - 16:47:58: Info (map "c2m1_highway") (file "errors_20191028.log")
L 10/28/2019 - 16:47:58: [SM] Exception reported: Client 2 is not in game
L 10/28/2019 - 16:47:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 16:47:58: [SM] Call stack trace:
L 10/28/2019 - 16:47:58: [SM]   [0] GetClientTeam
L 10/28/2019 - 16:47:58: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 17:01:20: [SM] Exception reported: Entity 1 (1) is invalid
L 10/28/2019 - 17:01:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 17:01:20: [SM] Call stack trace:
L 10/28/2019 - 17:01:20: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 17:01:20: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 17:01:20: [SM] Exception reported: Client 1 is not in game
L 10/28/2019 - 17:01:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 17:01:20: [SM] Call stack trace:
L 10/28/2019 - 17:01:20: [SM]   [0] GetClientTeam
L 10/28/2019 - 17:01:20: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 17:01:21: Error log file session closed.
L 10/28/2019 - 17:10:38: SourceMod error session started
L 10/28/2019 - 17:10:38: Info (map "c2m2_fairgrounds") (file "errors_20191028.log")
L 10/28/2019 - 17:10:38: [SM] Exception reported: Client index 277 is invalid
L 10/28/2019 - 17:10:38: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 17:10:38: [SM] Call stack trace:
L 10/28/2019 - 17:10:38: [SM]   [0] IsClientInGame
L 10/28/2019 - 17:10:38: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 17:10:38: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 17:10:39: [SM] Exception reported: Client index 277 is invalid
L 10/28/2019 - 17:10:39: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/28/2019 - 17:10:39: [SM] Call stack trace:
L 10/28/2019 - 17:10:39: [SM]   [0] IsClientInGame
L 10/28/2019 - 17:10:39: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/28/2019 - 17:10:39: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/28/2019 - 17:17:52: [SM] Exception reported: Entity 8 (8) is invalid
L 10/28/2019 - 17:17:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 17:17:52: [SM] Call stack trace:
L 10/28/2019 - 17:17:52: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 17:17:52: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 17:17:52: [SM] Exception reported: Entity 5 (5) is invalid
L 10/28/2019 - 17:17:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 17:17:52: [SM] Call stack trace:
L 10/28/2019 - 17:17:52: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 17:17:52: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 17:17:53: Error log file session closed.
L 10/28/2019 - 17:24:10: SourceMod error session started
L 10/28/2019 - 17:24:10: Info (map "c2m3_coaster") (file "errors_20191028.log")
L 10/28/2019 - 17:24:10: [SM] Exception reported: Entity 7 (7) is invalid
L 10/28/2019 - 17:24:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 17:24:10: [SM] Call stack trace:
L 10/28/2019 - 17:24:10: [SM]   [0] GetEntDataEnt2
L 10/28/2019 - 17:24:10: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/28/2019 - 17:26:36: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 17:26:36: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 17:26:36: [SM] Call stack trace:
L 10/28/2019 - 17:26:36: [SM]   [0] SetEntProp
L 10/28/2019 - 17:26:36: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 17:26:52: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 17:26:52: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 17:26:52: [SM] Call stack trace:
L 10/28/2019 - 17:26:52: [SM]   [0] SetEntProp
L 10/28/2019 - 17:26:52: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 17:27:21: Error log file session closed.
L 10/28/2019 - 17:27:24: SourceMod error session started
L 10/28/2019 - 17:27:24: Info (map "c2m4_barns") (file "errors_20191028.log")
L 10/28/2019 - 17:27:24: [SM] Exception reported: Client 4 is not in game
L 10/28/2019 - 17:27:24: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/28/2019 - 17:27:24: [SM] Call stack trace:
L 10/28/2019 - 17:27:24: [SM]   [0] GetClientTeam
L 10/28/2019 - 17:27:24: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/28/2019 - 17:31:03: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/28/2019 - 17:31:03: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/28/2019 - 17:31:03: [SM] Call stack trace:
L 10/28/2019 - 17:31:03: [SM]   [0] SetEntProp
L 10/28/2019 - 17:31:03: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/28/2019 - 17:36:55: SourceMod error session started
L 10/28/2019 - 17:36:55: Info (map "c2m1_highway") (file "errors_20191028.log")
L 10/28/2019 - 17:36:55: [CRASH] Accelerator uploaded crash dump: Crash ID: 7HGZ-W4IR-34CU
