L 10/24/2019 - 01:02:12: SourceMod error session started
L 10/24/2019 - 01:02:12: Info (map "c2m1_highway") (file "errors_20191024.log")
L 10/24/2019 - 01:02:12: Error log file session closed.
L 10/24/2019 - 01:05:06: SourceMod error session started
L 10/24/2019 - 01:05:06: Info (map "c2m1_highway") (file "errors_20191024.log")
L 10/24/2019 - 01:05:06: [CRASH] Accelerator uploaded crash dump: Crash ID: KS6X-7K2D-MNLS
L 10/24/2019 - 19:11:00: Error log file session closed.
L 10/24/2019 - 19:15:54: SourceMod error session started
L 10/24/2019 - 19:15:54: Info (map "c2m1_highway") (file "errors_20191024.log")
L 10/24/2019 - 19:15:54: [CRASH] Accelerator uploaded crash dump: Crash ID: ULAZ-FYRK-HA65
L 10/24/2019 - 20:03:09: Error log file session closed.
L 10/24/2019 - 20:06:33: SourceMod error session started
L 10/24/2019 - 20:06:33: Info (map "c1m1_hotel") (file "errors_20191024.log")
L 10/24/2019 - 20:06:33: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 20:06:33: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 20:06:33: [SM] Call stack trace:
L 10/24/2019 - 20:06:33: [SM]   [0] SetEntProp
L 10/24/2019 - 20:06:33: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 20:10:20: [SM] Exception reported: Client 3 is not in game
L 10/24/2019 - 20:10:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 20:10:20: [SM] Call stack trace:
L 10/24/2019 - 20:10:20: [SM]   [0] GetClientTeam
L 10/24/2019 - 20:10:20: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 20:10:20: [SM] Exception reported: Client 8 is not in game
L 10/24/2019 - 20:10:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 20:10:20: [SM] Call stack trace:
L 10/24/2019 - 20:10:20: [SM]   [0] GetClientTeam
L 10/24/2019 - 20:10:20: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 20:10:20: Error log file session closed.
L 10/24/2019 - 20:12:48: SourceMod error session started
L 10/24/2019 - 20:12:48: Info (map "c1m2_streets") (file "errors_20191024.log")
L 10/24/2019 - 20:12:48: [SM] Exception reported: Client 11 is not in game
L 10/24/2019 - 20:12:48: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 20:12:48: [SM] Call stack trace:
L 10/24/2019 - 20:12:48: [SM]   [0] GetClientTeam
L 10/24/2019 - 20:12:48: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 20:12:53: [SM] Exception reported: Entity 11 (11) is invalid
L 10/24/2019 - 20:12:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 20:12:53: [SM] Call stack trace:
L 10/24/2019 - 20:12:53: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 20:12:53: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 20:13:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 20:13:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 20:13:16: [SM] Call stack trace:
L 10/24/2019 - 20:13:16: [SM]   [0] SetEntProp
L 10/24/2019 - 20:13:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 20:17:35: [SM] Exception reported: Client index 154 is invalid
L 10/24/2019 - 20:17:35: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/24/2019 - 20:17:35: [SM] Call stack trace:
L 10/24/2019 - 20:17:35: [SM]   [0] IsClientInGame
L 10/24/2019 - 20:17:35: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/24/2019 - 20:17:35: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/24/2019 - 20:31:59: [SM] Exception reported: Entity 9 (9) is invalid
L 10/24/2019 - 20:31:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 20:31:59: [SM] Call stack trace:
L 10/24/2019 - 20:31:59: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 20:31:59: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/24/2019 - 20:32:00: Error log file session closed.
L 10/24/2019 - 20:41:39: SourceMod error session started
L 10/24/2019 - 20:41:39: Info (map "c1m3_mall") (file "errors_20191024.log")
L 10/24/2019 - 20:41:39: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 20:41:39: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 20:41:39: [SM] Call stack trace:
L 10/24/2019 - 20:41:39: [SM]   [0] SetEntProp
L 10/24/2019 - 20:41:39: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 20:42:43: Error log file session closed.
L 10/24/2019 - 20:50:23: SourceMod error session started
L 10/24/2019 - 20:50:23: Info (map "c1m4_atrium") (file "errors_20191024.log")
L 10/24/2019 - 20:50:23: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/24/2019 - 20:50:23: [SM] Blaming: l4d2_jockey_skeet.smx
L 10/24/2019 - 20:50:23: [SM] Call stack trace:
L 10/24/2019 - 20:50:23: [SM]   [0] GetEdictClassname
L 10/24/2019 - 20:50:23: [SM]   [1] Line 141, plugin/EUplugins/march/l4d2_jockey_skeet.sp::IsShotgun
L 10/24/2019 - 20:50:23: [SM]   [2] Line 73, plugin/EUplugins/march/l4d2_jockey_skeet.sp::OnTakeDamage
L 10/24/2019 - 20:51:04: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 20:51:04: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 20:51:04: [SM] Call stack trace:
L 10/24/2019 - 20:51:04: [SM]   [0] SetEntProp
L 10/24/2019 - 20:51:04: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 20:58:21: [SM] Exception reported: Client 4 is not in game
L 10/24/2019 - 20:58:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 20:58:21: [SM] Call stack trace:
L 10/24/2019 - 20:58:21: [SM]   [0] GetClientTeam
L 10/24/2019 - 20:58:21: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 20:58:21: [SM] Exception reported: Entity 1 (1) is invalid
L 10/24/2019 - 20:58:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 20:58:21: [SM] Call stack trace:
L 10/24/2019 - 20:58:21: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 20:58:21: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 20:58:21: Error log file session closed.
L 10/24/2019 - 21:01:06: SourceMod error session started
L 10/24/2019 - 21:01:06: Info (map "c5m1_waterfront") (file "errors_20191024.log")
L 10/24/2019 - 21:01:06: [SM] Exception reported: Client 7 is not in game
L 10/24/2019 - 21:01:06: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 21:01:06: [SM] Call stack trace:
L 10/24/2019 - 21:01:06: [SM]   [0] GetClientTeam
L 10/24/2019 - 21:01:06: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 21:01:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 21:01:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 21:01:24: [SM] Call stack trace:
L 10/24/2019 - 21:01:24: [SM]   [0] SetEntProp
L 10/24/2019 - 21:01:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 21:01:35: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 21:01:35: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 21:01:35: [SM] Call stack trace:
L 10/24/2019 - 21:01:35: [SM]   [0] SetEntProp
L 10/24/2019 - 21:01:35: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 21:01:50: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 21:01:50: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 21:01:50: [SM] Call stack trace:
L 10/24/2019 - 21:01:50: [SM]   [0] SetEntProp
L 10/24/2019 - 21:01:50: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 21:04:15: Error log file session closed.
L 10/24/2019 - 21:14:18: SourceMod error session started
L 10/24/2019 - 21:14:18: Info (map "c5m2_park") (file "errors_20191024.log")
L 10/24/2019 - 21:14:18: [SM] Exception reported: Entity 4 (4) is invalid
L 10/24/2019 - 21:14:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 21:14:18: [SM] Call stack trace:
L 10/24/2019 - 21:14:18: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 21:14:18: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 21:20:17: Error log file session closed.
L 10/24/2019 - 21:22:18: SourceMod error session started
L 10/24/2019 - 21:22:18: Info (map "c5m3_cemetery") (file "errors_20191024.log")
L 10/24/2019 - 21:22:18: [SM] Exception reported: Entity 2 (2) is invalid
L 10/24/2019 - 21:22:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 21:22:18: [SM] Call stack trace:
L 10/24/2019 - 21:22:18: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 21:22:18: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/24/2019 - 21:29:15: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 21:29:15: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 21:29:15: [SM] Call stack trace:
L 10/24/2019 - 21:29:15: [SM]   [0] SetEntProp
L 10/24/2019 - 21:29:15: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 21:33:59: Error log file session closed.
L 10/24/2019 - 21:47:12: SourceMod error session started
L 10/24/2019 - 21:47:12: Info (map "c5m4_quarter") (file "errors_20191024.log")
L 10/24/2019 - 21:47:12: [SM] Exception reported: Entity 5 (5) is invalid
L 10/24/2019 - 21:47:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 21:47:12: [SM] Call stack trace:
L 10/24/2019 - 21:47:12: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 21:47:12: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 21:47:12: [SM] Exception reported: Entity 2 (2) is invalid
L 10/24/2019 - 21:47:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 21:47:12: [SM] Call stack trace:
L 10/24/2019 - 21:47:12: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 21:47:12: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 21:47:13: Error log file session closed.
L 10/24/2019 - 21:49:35: SourceMod error session started
L 10/24/2019 - 21:49:35: Info (map "c5m5_bridge") (file "errors_20191024.log")
L 10/24/2019 - 21:49:35: [SM] Exception reported: Entity 2 (2) is invalid
L 10/24/2019 - 21:49:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/24/2019 - 21:49:35: [SM] Call stack trace:
L 10/24/2019 - 21:49:35: [SM]   [0] GetEntDataEnt2
L 10/24/2019 - 21:49:35: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/24/2019 - 21:49:36: Error log file session closed.
L 10/24/2019 - 22:06:47: SourceMod error session started
L 10/24/2019 - 22:06:47: Info (map "c2m1_highway") (file "errors_20191024.log")
L 10/24/2019 - 22:06:47: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/24/2019 - 22:06:47: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/24/2019 - 22:06:47: [SM] Call stack trace:
L 10/24/2019 - 22:06:47: [SM]   [0] SetEntProp
L 10/24/2019 - 22:06:47: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/24/2019 - 22:11:22: SourceMod error session started
L 10/24/2019 - 22:11:22: Info (map "c2m1_highway") (file "errors_20191024.log")
L 10/24/2019 - 22:11:22: [CRASH] Accelerator uploaded crash dump: Crash ID: KCIV-T35Q-IN5C
