L 10/15/2019 - 00:38:02: SourceMod error session started
L 10/15/2019 - 00:38:02: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 00:38:02: [SM] Exception reported: Client 6 is not in game
L 10/15/2019 - 00:38:02: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 00:38:02: [SM] Call stack trace:
L 10/15/2019 - 00:38:02: [SM]   [0] GetClientTeam
L 10/15/2019 - 00:38:02: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 00:38:15: [SM] Exception reported: Client 6 is not in game
L 10/15/2019 - 00:38:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 00:38:15: [SM] Call stack trace:
L 10/15/2019 - 00:38:15: [SM]   [0] GetClientTeam
L 10/15/2019 - 00:38:15: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 13:58:59: Error log file session closed.
L 10/15/2019 - 14:12:52: SourceMod error session started
L 10/15/2019 - 14:12:52: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 14:12:52: [SM] Exception reported: Entity 2 (2) is invalid
L 10/15/2019 - 14:12:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 14:12:52: [SM] Call stack trace:
L 10/15/2019 - 14:12:52: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 14:12:52: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 14:12:52: Error log file session closed.
L 10/15/2019 - 14:34:52: SourceMod error session started
L 10/15/2019 - 14:34:52: Info (map "c2m3_coaster") (file "errors_20191015.log")
L 10/15/2019 - 14:34:52: [SM] Exception reported: Client 3 is not in game
L 10/15/2019 - 14:34:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 14:34:52: [SM] Call stack trace:
L 10/15/2019 - 14:34:52: [SM]   [0] GetClientTeam
L 10/15/2019 - 14:34:52: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 14:34:53: Error log file session closed.
L 10/15/2019 - 14:42:35: SourceMod error session started
L 10/15/2019 - 14:42:35: Info (map "c2m4_barns") (file "errors_20191015.log")
L 10/15/2019 - 14:42:35: [SM] Exception reported: Entity 12 (12) is invalid
L 10/15/2019 - 14:42:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 14:42:35: [SM] Call stack trace:
L 10/15/2019 - 14:42:35: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 14:42:35: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 14:42:36: Error log file session closed.
L 10/15/2019 - 14:44:42: SourceMod error session started
L 10/15/2019 - 14:44:42: Info (map "c2m5_concert") (file "errors_20191015.log")
L 10/15/2019 - 14:44:42: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 14:44:42: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 14:44:42: [SM] Call stack trace:
L 10/15/2019 - 14:44:42: [SM]   [0] SetEntProp
L 10/15/2019 - 14:44:42: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 14:45:55: [SM] Exception reported: Client index 469 is invalid
L 10/15/2019 - 14:45:55: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 14:45:55: [SM] Call stack trace:
L 10/15/2019 - 14:45:55: [SM]   [0] IsClientInGame
L 10/15/2019 - 14:45:55: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 14:45:55: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 14:45:58: [SM] Exception reported: Client index 469 is invalid
L 10/15/2019 - 14:45:58: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 14:45:58: [SM] Call stack trace:
L 10/15/2019 - 14:45:58: [SM]   [0] IsClientInGame
L 10/15/2019 - 14:45:58: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 14:45:58: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 14:46:40: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 14:46:40: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 14:46:40: [SM] Call stack trace:
L 10/15/2019 - 14:46:40: [SM]   [0] SetEntProp
L 10/15/2019 - 14:46:40: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 14:54:13: [SM] Exception reported: Entity 1 (1) is invalid
L 10/15/2019 - 14:54:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 14:54:13: [SM] Call stack trace:
L 10/15/2019 - 14:54:13: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 14:54:13: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 14:54:14: Error log file session closed.
L 10/15/2019 - 14:54:37: SourceMod error session started
L 10/15/2019 - 14:54:37: Info (map "c5m1_waterfront") (file "errors_20191015.log")
L 10/15/2019 - 14:54:37: [SM] Exception reported: Client 3 is not in game
L 10/15/2019 - 14:54:37: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 14:54:37: [SM] Call stack trace:
L 10/15/2019 - 14:54:37: [SM]   [0] GetClientTeam
L 10/15/2019 - 14:54:37: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 14:57:31: [SM] Exception reported: Client index 458 is invalid
L 10/15/2019 - 14:57:31: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 14:57:31: [SM] Call stack trace:
L 10/15/2019 - 14:57:31: [SM]   [0] IsClientInGame
L 10/15/2019 - 14:57:31: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 14:57:31: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 14:59:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 14:59:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 14:59:11: [SM] Call stack trace:
L 10/15/2019 - 14:59:11: [SM]   [0] SetEntProp
L 10/15/2019 - 14:59:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 14:59:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 14:59:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 14:59:20: [SM] Call stack trace:
L 10/15/2019 - 14:59:20: [SM]   [0] SetEntProp
L 10/15/2019 - 14:59:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 15:01:49: [SM] Exception reported: Client index 470 is invalid
L 10/15/2019 - 15:01:49: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:01:49: [SM] Call stack trace:
L 10/15/2019 - 15:01:49: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:01:49: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:01:49: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:01:59: [SM] Exception reported: Client index 470 is invalid
L 10/15/2019 - 15:01:59: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:01:59: [SM] Call stack trace:
L 10/15/2019 - 15:01:59: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:01:59: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:01:59: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:01:59: [SM] Exception reported: Client index 470 is invalid
L 10/15/2019 - 15:01:59: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:01:59: [SM] Call stack trace:
L 10/15/2019 - 15:01:59: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:01:59: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:01:59: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:01:59: [SM] Exception reported: Client index 470 is invalid
L 10/15/2019 - 15:01:59: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:01:59: [SM] Call stack trace:
L 10/15/2019 - 15:01:59: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:01:59: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:01:59: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:02:01: [SM] Exception reported: Client index 470 is invalid
L 10/15/2019 - 15:02:01: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:02:01: [SM] Call stack trace:
L 10/15/2019 - 15:02:01: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:02:01: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:02:01: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:02:03: [SM] Exception reported: Client index 470 is invalid
L 10/15/2019 - 15:02:03: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:02:03: [SM] Call stack trace:
L 10/15/2019 - 15:02:03: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:02:03: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:02:03: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:02:05: [SM] Exception reported: Client index 470 is invalid
L 10/15/2019 - 15:02:05: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:02:05: [SM] Call stack trace:
L 10/15/2019 - 15:02:05: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:02:05: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:02:05: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:03:12: [SM] Exception reported: Entity 6 (6) is invalid
L 10/15/2019 - 15:03:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 15:03:12: [SM] Call stack trace:
L 10/15/2019 - 15:03:12: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 15:03:12: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 15:03:12: Error log file session closed.
L 10/15/2019 - 15:05:30: SourceMod error session started
L 10/15/2019 - 15:05:30: Info (map "c5m2_park") (file "errors_20191015.log")
L 10/15/2019 - 15:05:30: [SM] Exception reported: Entity 6 (6) is invalid
L 10/15/2019 - 15:05:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 15:05:30: [SM] Call stack trace:
L 10/15/2019 - 15:05:30: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 15:05:30: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 15:13:22: [SM] Exception reported: Entity 1 (1) is invalid
L 10/15/2019 - 15:13:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 15:13:22: [SM] Call stack trace:
L 10/15/2019 - 15:13:22: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 15:13:22: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 15:13:22: Error log file session closed.
L 10/15/2019 - 15:24:26: SourceMod error session started
L 10/15/2019 - 15:24:26: Info (map "c5m3_cemetery") (file "errors_20191015.log")
L 10/15/2019 - 15:24:26: [SM] Exception reported: Client index 595 is invalid
L 10/15/2019 - 15:24:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:24:26: [SM] Call stack trace:
L 10/15/2019 - 15:24:26: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:24:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:24:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:24:26: [SM] Exception reported: Client index 595 is invalid
L 10/15/2019 - 15:24:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:24:26: [SM] Call stack trace:
L 10/15/2019 - 15:24:26: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:24:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:24:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:24:28: [SM] Exception reported: Client index 595 is invalid
L 10/15/2019 - 15:24:28: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:24:28: [SM] Call stack trace:
L 10/15/2019 - 15:24:28: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:24:28: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:24:28: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:24:32: [SM] Exception reported: Client index 595 is invalid
L 10/15/2019 - 15:24:32: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 15:24:32: [SM] Call stack trace:
L 10/15/2019 - 15:24:32: [SM]   [0] IsClientInGame
L 10/15/2019 - 15:24:32: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 15:24:32: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 15:33:28: [SM] Exception reported: Entity 8 (8) is invalid
L 10/15/2019 - 15:33:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 15:33:28: [SM] Call stack trace:
L 10/15/2019 - 15:33:28: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 15:33:28: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 15:33:29: Error log file session closed.
L 10/15/2019 - 15:37:01: SourceMod error session started
L 10/15/2019 - 15:37:01: Info (map "c5m4_quarter") (file "errors_20191015.log")
L 10/15/2019 - 15:37:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 15:37:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 15:37:01: [SM] Call stack trace:
L 10/15/2019 - 15:37:01: [SM]   [0] SetEntProp
L 10/15/2019 - 15:37:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 15:37:07: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 15:37:07: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 15:37:07: [SM] Call stack trace:
L 10/15/2019 - 15:37:07: [SM]   [0] SetEntProp
L 10/15/2019 - 15:37:07: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 15:48:45: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 15:48:45: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 15:48:45: [SM] Call stack trace:
L 10/15/2019 - 15:48:45: [SM]   [0] SetEntProp
L 10/15/2019 - 15:48:45: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 15:49:19: [SM] Exception reported: Entity 2 (2) is invalid
L 10/15/2019 - 15:49:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 15:49:19: [SM] Call stack trace:
L 10/15/2019 - 15:49:19: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 15:49:19: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 15:49:20: Error log file session closed.
L 10/15/2019 - 15:50:47: SourceMod error session started
L 10/15/2019 - 15:50:47: Info (map "c5m5_bridge") (file "errors_20191015.log")
L 10/15/2019 - 15:50:47: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 15:50:47: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 15:50:47: [SM] Call stack trace:
L 10/15/2019 - 15:50:47: [SM]   [0] SetEntProp
L 10/15/2019 - 15:50:47: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 15:53:23: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/15/2019 - 15:53:23: [SM] Blaming: l4d2_playstats.smx
L 10/15/2019 - 15:53:23: [SM] Call stack trace:
L 10/15/2019 - 15:53:23: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/15/2019 - 15:53:23: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/15/2019 - 15:53:23: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/15/2019 - 15:53:23: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/15/2019 - 15:53:38: Error log file session closed.
L 10/15/2019 - 15:53:44: SourceMod error session started
L 10/15/2019 - 15:53:44: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 15:53:44: [SM] Exception reported: Client 8 is not in game
L 10/15/2019 - 15:53:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 15:53:44: [SM] Call stack trace:
L 10/15/2019 - 15:53:44: [SM]   [0] GetClientTeam
L 10/15/2019 - 15:53:44: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 15:58:23: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/15/2019 - 15:58:23: [SM] Blaming: l4d2_playstats.smx
L 10/15/2019 - 15:58:23: [SM] Call stack trace:
L 10/15/2019 - 15:58:23: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/15/2019 - 15:58:23: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/15/2019 - 15:58:23: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/15/2019 - 15:58:23: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/15/2019 - 16:01:14: [SM] Exception reported: Client 6 is not in game
L 10/15/2019 - 16:01:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:01:14: [SM] Call stack trace:
L 10/15/2019 - 16:01:14: [SM]   [0] GetClientTeam
L 10/15/2019 - 16:01:14: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 16:01:14: Error log file session closed.
L 10/15/2019 - 16:04:41: SourceMod error session started
L 10/15/2019 - 16:04:41: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 16:04:41: [SM] Exception reported: Entity 9 (9) is invalid
L 10/15/2019 - 16:04:41: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:04:41: [SM] Call stack trace:
L 10/15/2019 - 16:04:41: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 16:04:41: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 16:06:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 16:06:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 16:06:28: [SM] Call stack trace:
L 10/15/2019 - 16:06:28: [SM]   [0] SetEntProp
L 10/15/2019 - 16:06:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 16:07:47: [SM] Exception reported: Entity 11 (11) is invalid
L 10/15/2019 - 16:07:47: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:07:47: [SM] Call stack trace:
L 10/15/2019 - 16:07:47: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 16:07:47: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 16:07:48: Error log file session closed.
L 10/15/2019 - 16:09:36: SourceMod error session started
L 10/15/2019 - 16:09:36: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 16:09:36: [CRASH] Accelerator uploaded crash dump: Crash ID: KA2U-T7PA-UAOZ
L 10/15/2019 - 16:27:06: Error log file session closed.
L 10/15/2019 - 16:32:01: SourceMod error session started
L 10/15/2019 - 16:32:01: Info (map "c8m1_apartment") (file "errors_20191015.log")
L 10/15/2019 - 16:32:01: [SM] Exception reported: Client index 506 is invalid
L 10/15/2019 - 16:32:01: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:32:01: [SM] Call stack trace:
L 10/15/2019 - 16:32:01: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:32:01: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:32:01: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:33:43: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 16:33:43: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:33:43: [SM] Call stack trace:
L 10/15/2019 - 16:33:43: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 16:33:43: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 16:35:48: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:48: [SM] Call stack trace:
L 10/15/2019 - 16:35:48: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:48: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:48: [SM] Call stack trace:
L 10/15/2019 - 16:35:48: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:48: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:48: [SM] Call stack trace:
L 10/15/2019 - 16:35:48: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:48: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:48: [SM] Call stack trace:
L 10/15/2019 - 16:35:48: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:48: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:48: [SM] Call stack trace:
L 10/15/2019 - 16:35:48: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:49: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:49: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:49: [SM] Call stack trace:
L 10/15/2019 - 16:35:49: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:49: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:49: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:49: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:49: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:49: [SM] Call stack trace:
L 10/15/2019 - 16:35:49: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:49: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:49: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:49: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:49: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:49: [SM] Call stack trace:
L 10/15/2019 - 16:35:49: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:49: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:49: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:35:49: [SM] Exception reported: Client index 255 is invalid
L 10/15/2019 - 16:35:49: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:35:49: [SM] Call stack trace:
L 10/15/2019 - 16:35:49: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:35:49: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:35:49: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:36:29: [SM] Exception reported: Client index 205 is invalid
L 10/15/2019 - 16:36:29: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:36:29: [SM] Call stack trace:
L 10/15/2019 - 16:36:29: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:36:29: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:36:29: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:36:36: [SM] Exception reported: Client index 205 is invalid
L 10/15/2019 - 16:36:36: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:36:36: [SM] Call stack trace:
L 10/15/2019 - 16:36:36: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:36:36: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:36:36: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 16:36:56: [SM] Exception reported: Entity 2 (2) is invalid
L 10/15/2019 - 16:36:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:36:56: [SM] Call stack trace:
L 10/15/2019 - 16:36:56: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 16:36:56: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 16:37:32: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 16:37:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:37:32: [SM] Call stack trace:
L 10/15/2019 - 16:37:32: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 16:37:32: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 16:37:32: [SM] Exception reported: Client 6 is not in game
L 10/15/2019 - 16:37:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:37:32: [SM] Call stack trace:
L 10/15/2019 - 16:37:32: [SM]   [0] GetClientTeam
L 10/15/2019 - 16:37:32: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 16:37:33: Error log file session closed.
L 10/15/2019 - 16:47:21: SourceMod error session started
L 10/15/2019 - 16:47:21: Info (map "c8m2_subway") (file "errors_20191015.log")
L 10/15/2019 - 16:47:21: [SM] Exception reported: Entity 7 (7) is invalid
L 10/15/2019 - 16:47:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:47:21: [SM] Call stack trace:
L 10/15/2019 - 16:47:21: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 16:47:21: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 16:50:09: Error log file session closed.
L 10/15/2019 - 16:50:35: SourceMod error session started
L 10/15/2019 - 16:50:35: Info (map "c8m3_sewers") (file "errors_20191015.log")
L 10/15/2019 - 16:50:35: [SM] Exception reported: Client 10 is not in game
L 10/15/2019 - 16:50:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 16:50:35: [SM] Call stack trace:
L 10/15/2019 - 16:50:35: [SM]   [0] GetClientTeam
L 10/15/2019 - 16:50:35: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 16:53:19: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 16:53:19: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 16:53:19: [SM] Call stack trace:
L 10/15/2019 - 16:53:19: [SM]   [0] SetEntProp
L 10/15/2019 - 16:53:19: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 16:57:25: [SM] Exception reported: Client index 260 is invalid
L 10/15/2019 - 16:57:25: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 16:57:25: [SM] Call stack trace:
L 10/15/2019 - 16:57:25: [SM]   [0] IsClientInGame
L 10/15/2019 - 16:57:25: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 16:57:25: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 17:00:18: [SM] Exception reported: Entity 8 (8) is invalid
L 10/15/2019 - 17:00:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:00:18: [SM] Call stack trace:
L 10/15/2019 - 17:00:18: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 17:00:18: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 17:02:49: Error log file session closed.
L 10/15/2019 - 17:13:55: SourceMod error session started
L 10/15/2019 - 17:13:55: Info (map "c8m4_interior") (file "errors_20191015.log")
L 10/15/2019 - 17:13:55: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 17:13:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:13:55: [SM] Call stack trace:
L 10/15/2019 - 17:13:55: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 17:13:55: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 17:13:55: [SM] Exception reported: Entity 10 (10) is invalid
L 10/15/2019 - 17:13:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:13:55: [SM] Call stack trace:
L 10/15/2019 - 17:13:55: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 17:13:55: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 17:13:55: [SM] Exception reported: Client 5 is not in game
L 10/15/2019 - 17:13:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:13:55: [SM] Call stack trace:
L 10/15/2019 - 17:13:55: [SM]   [0] GetClientTeam
L 10/15/2019 - 17:13:55: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 17:13:56: Error log file session closed.
L 10/15/2019 - 17:14:25: SourceMod error session started
L 10/15/2019 - 17:14:25: Info (map "c8m5_rooftop") (file "errors_20191015.log")
L 10/15/2019 - 17:14:25: [SM] Exception reported: Client 8 is not in game
L 10/15/2019 - 17:14:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:14:25: [SM] Call stack trace:
L 10/15/2019 - 17:14:25: [SM]   [0] GetClientTeam
L 10/15/2019 - 17:14:25: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 17:17:46: [SM] Exception reported: Client 8 is not in game
L 10/15/2019 - 17:17:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:17:46: [SM] Call stack trace:
L 10/15/2019 - 17:17:46: [SM]   [0] GetClientTeam
L 10/15/2019 - 17:17:46: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 17:18:32: [SM] Exception reported: Entity 2 (2) is invalid
L 10/15/2019 - 17:18:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:18:32: [SM] Call stack trace:
L 10/15/2019 - 17:18:32: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 17:18:32: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 17:18:33: Error log file session closed.
L 10/15/2019 - 17:18:35: SourceMod error session started
L 10/15/2019 - 17:18:35: Info (map "c12m1_hilltop") (file "errors_20191015.log")
L 10/15/2019 - 17:18:35: [SM] Exception reported: Entity 2 (2) is invalid
L 10/15/2019 - 17:18:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:18:35: [SM] Call stack trace:
L 10/15/2019 - 17:18:35: [SM]   [0] GetEntProp
L 10/15/2019 - 17:18:35: [SM]   [1] Line 371, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::IsPlayingGetUpAnimation
L 10/15/2019 - 17:18:35: [SM]   [2] Line 211, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::BlueMoonCaseCheck
L 10/15/2019 - 17:22:51: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 17:22:51: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 17:22:51: [SM] Call stack trace:
L 10/15/2019 - 17:22:51: [SM]   [0] SetEntProp
L 10/15/2019 - 17:22:51: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 17:27:02: Error log file session closed.
L 10/15/2019 - 17:38:32: SourceMod error session started
L 10/15/2019 - 17:38:32: Info (map "c12m3_bridge") (file "errors_20191015.log")
L 10/15/2019 - 17:38:32: [SM] Exception reported: Entity 10 (10) is invalid
L 10/15/2019 - 17:38:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:38:32: [SM] Call stack trace:
L 10/15/2019 - 17:38:32: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 17:38:32: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 17:38:32: [SM] Exception reported: Entity 10 (10) is invalid
L 10/15/2019 - 17:38:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 17:38:32: [SM] Call stack trace:
L 10/15/2019 - 17:38:32: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 17:38:32: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 17:38:33: Error log file session closed.
L 10/15/2019 - 17:41:11: SourceMod error session started
L 10/15/2019 - 17:41:11: Info (map "c12m4_barn") (file "errors_20191015.log")
L 10/15/2019 - 17:41:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 17:41:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 17:41:11: [SM] Call stack trace:
L 10/15/2019 - 17:41:11: [SM]   [0] SetEntProp
L 10/15/2019 - 17:41:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 17:50:02: Error log file session closed.
L 10/15/2019 - 18:00:01: SourceMod error session started
L 10/15/2019 - 18:00:01: Info (map "c12m5_cornfield") (file "errors_20191015.log")
L 10/15/2019 - 18:00:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 18:00:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 18:00:01: [SM] Call stack trace:
L 10/15/2019 - 18:00:01: [SM]   [0] SetEntProp
L 10/15/2019 - 18:00:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 18:03:10: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 18:03:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:03:10: [SM] Call stack trace:
L 10/15/2019 - 18:03:10: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 18:03:10: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 18:03:10: Error log file session closed.
L 10/15/2019 - 18:12:15: SourceMod error session started
L 10/15/2019 - 18:12:15: Info (map "c1m1_hotel") (file "errors_20191015.log")
L 10/15/2019 - 18:12:15: [SM] Exception reported: Entity 10 (10) is invalid
L 10/15/2019 - 18:12:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:12:15: [SM] Call stack trace:
L 10/15/2019 - 18:12:15: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 18:12:15: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 18:12:15: [SM] Exception reported: Client 4 is not in game
L 10/15/2019 - 18:12:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:12:15: [SM] Call stack trace:
L 10/15/2019 - 18:12:15: [SM]   [0] GetClientTeam
L 10/15/2019 - 18:12:15: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 18:12:15: Error log file session closed.
L 10/15/2019 - 18:17:18: SourceMod error session started
L 10/15/2019 - 18:17:18: Info (map "c1m2_streets") (file "errors_20191015.log")
L 10/15/2019 - 18:17:18: [SM] Exception reported: Client index 97 is invalid
L 10/15/2019 - 18:17:18: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:17:18: [SM] Call stack trace:
L 10/15/2019 - 18:17:18: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:17:18: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:17:18: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:17:18: [SM] Exception reported: Client index 97 is invalid
L 10/15/2019 - 18:17:18: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:17:18: [SM] Call stack trace:
L 10/15/2019 - 18:17:18: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:17:18: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:17:18: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:17:20: [SM] Exception reported: Client index 97 is invalid
L 10/15/2019 - 18:17:20: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:17:20: [SM] Call stack trace:
L 10/15/2019 - 18:17:20: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:17:20: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:17:20: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:17:21: [SM] Exception reported: Client index 97 is invalid
L 10/15/2019 - 18:17:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:17:21: [SM] Call stack trace:
L 10/15/2019 - 18:17:21: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:17:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:17:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:17:25: [SM] Exception reported: Client index 97 is invalid
L 10/15/2019 - 18:17:25: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:17:25: [SM] Call stack trace:
L 10/15/2019 - 18:17:25: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:17:25: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:17:25: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:17:25: [SM] Exception reported: Client index 97 is invalid
L 10/15/2019 - 18:17:25: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:17:25: [SM] Call stack trace:
L 10/15/2019 - 18:17:25: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:17:25: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:17:25: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:23:56: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/15/2019 - 18:23:56: [SM] Blaming: l4d2_playstats.smx
L 10/15/2019 - 18:23:56: [SM] Call stack trace:
L 10/15/2019 - 18:23:56: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/15/2019 - 18:23:56: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/15/2019 - 18:23:56: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/15/2019 - 18:23:56: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/15/2019 - 18:24:15: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 18:24:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:24:15: [SM] Call stack trace:
L 10/15/2019 - 18:24:15: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 18:24:15: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 18:24:15: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 18:24:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:24:15: [SM] Call stack trace:
L 10/15/2019 - 18:24:15: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 18:24:15: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 18:24:16: Error log file session closed.
L 10/15/2019 - 18:31:37: SourceMod error session started
L 10/15/2019 - 18:31:37: Info (map "c1m3_mall") (file "errors_20191015.log")
L 10/15/2019 - 18:31:37: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 18:31:37: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:31:37: [SM] Call stack trace:
L 10/15/2019 - 18:31:37: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 18:31:37: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 18:35:25: [SM] Exception reported: Entity 7 (7) is invalid
L 10/15/2019 - 18:35:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:35:25: [SM] Call stack trace:
L 10/15/2019 - 18:35:25: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 18:35:25: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 18:35:31: [SM] Exception reported: Entity 7 (7) is invalid
L 10/15/2019 - 18:35:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:35:31: [SM] Call stack trace:
L 10/15/2019 - 18:35:31: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 18:35:31: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 18:35:31: [SM] Exception reported: Client 7 is not in game
L 10/15/2019 - 18:35:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 18:35:31: [SM] Call stack trace:
L 10/15/2019 - 18:35:31: [SM]   [0] GetClientTeam
L 10/15/2019 - 18:35:31: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 18:35:31: Error log file session closed.
L 10/15/2019 - 18:38:37: SourceMod error session started
L 10/15/2019 - 18:38:37: Info (map "c1m4_atrium") (file "errors_20191015.log")
L 10/15/2019 - 18:38:37: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 18:38:37: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 18:38:37: [SM] Call stack trace:
L 10/15/2019 - 18:38:37: [SM]   [0] SetEntProp
L 10/15/2019 - 18:38:37: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 18:41:44: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 18:41:44: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 18:41:44: [SM] Call stack trace:
L 10/15/2019 - 18:41:44: [SM]   [0] SetEntProp
L 10/15/2019 - 18:41:44: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 18:41:56: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 18:41:56: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 18:41:56: [SM] Call stack trace:
L 10/15/2019 - 18:41:56: [SM]   [0] SetEntProp
L 10/15/2019 - 18:41:56: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 18:45:18: [SM] Exception reported: Client index 283 is invalid
L 10/15/2019 - 18:45:18: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:45:18: [SM] Call stack trace:
L 10/15/2019 - 18:45:18: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:45:18: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:45:18: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:46:19: Error log file session closed.
L 10/15/2019 - 18:49:22: SourceMod error session started
L 10/15/2019 - 18:49:22: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 18:49:22: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 18:49:22: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 18:49:22: [SM] Call stack trace:
L 10/15/2019 - 18:49:22: [SM]   [0] SetEntProp
L 10/15/2019 - 18:49:22: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 18:57:03: Error log file session closed.
L 10/15/2019 - 18:59:24: SourceMod error session started
L 10/15/2019 - 18:59:24: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 18:59:24: [SM] Exception reported: Client index 268 is invalid
L 10/15/2019 - 18:59:24: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:59:24: [SM] Call stack trace:
L 10/15/2019 - 18:59:24: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:59:24: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:59:24: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 18:59:24: [SM] Exception reported: Client index 268 is invalid
L 10/15/2019 - 18:59:24: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 18:59:24: [SM] Call stack trace:
L 10/15/2019 - 18:59:24: [SM]   [0] IsClientInGame
L 10/15/2019 - 18:59:24: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 18:59:24: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 19:02:46: [SM] Exception reported: Client 3 is not in game
L 10/15/2019 - 19:02:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 19:02:46: [SM] Call stack trace:
L 10/15/2019 - 19:02:46: [SM]   [0] GetClientTeam
L 10/15/2019 - 19:02:46: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 19:08:36: [SM] Exception reported: Entity 7 (7) is invalid
L 10/15/2019 - 19:08:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 19:08:36: [SM] Call stack trace:
L 10/15/2019 - 19:08:36: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 19:08:36: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 19:09:19: [SM] Exception reported: Client index 269 is invalid
L 10/15/2019 - 19:09:19: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 19:09:19: [SM] Call stack trace:
L 10/15/2019 - 19:09:19: [SM]   [0] IsClientInGame
L 10/15/2019 - 19:09:19: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 19:09:19: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 19:09:25: [SM] Exception reported: Client index 269 is invalid
L 10/15/2019 - 19:09:25: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 19:09:25: [SM] Call stack trace:
L 10/15/2019 - 19:09:25: [SM]   [0] IsClientInGame
L 10/15/2019 - 19:09:25: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 19:09:25: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 19:09:27: [SM] Exception reported: Client index 269 is invalid
L 10/15/2019 - 19:09:27: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 19:09:27: [SM] Call stack trace:
L 10/15/2019 - 19:09:27: [SM]   [0] IsClientInGame
L 10/15/2019 - 19:09:27: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 19:09:27: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 19:11:46: [SM] Exception reported: Client 10 is not in game
L 10/15/2019 - 19:11:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 19:11:46: [SM] Call stack trace:
L 10/15/2019 - 19:11:46: [SM]   [0] GetClientTeam
L 10/15/2019 - 19:11:46: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 19:11:47: Error log file session closed.
L 10/15/2019 - 19:21:12: SourceMod error session started
L 10/15/2019 - 19:21:12: Info (map "c2m2_fairgrounds") (file "errors_20191015.log")
L 10/15/2019 - 19:21:12: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 19:21:12: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 19:21:12: [SM] Call stack trace:
L 10/15/2019 - 19:21:12: [SM]   [0] SetEntProp
L 10/15/2019 - 19:21:12: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 19:27:13: [SM] Exception reported: Entity 4 (4) is invalid
L 10/15/2019 - 19:27:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 19:27:13: [SM] Call stack trace:
L 10/15/2019 - 19:27:13: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 19:27:13: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 19:27:13: Error log file session closed.
L 10/15/2019 - 19:34:54: SourceMod error session started
L 10/15/2019 - 19:34:54: Info (map "c5m1_waterfront") (file "errors_20191015.log")
L 10/15/2019 - 19:34:54: [SM] Exception reported: Client index 444 is invalid
L 10/15/2019 - 19:34:54: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 19:34:54: [SM] Call stack trace:
L 10/15/2019 - 19:34:54: [SM]   [0] IsClientInGame
L 10/15/2019 - 19:34:54: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 19:34:54: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 19:35:23: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 19:35:23: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 19:35:23: [SM] Call stack trace:
L 10/15/2019 - 19:35:23: [SM]   [0] SetEntProp
L 10/15/2019 - 19:35:23: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 19:35:27: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 19:35:27: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 19:35:27: [SM] Call stack trace:
L 10/15/2019 - 19:35:27: [SM]   [0] SetEntProp
L 10/15/2019 - 19:35:27: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 19:35:49: [SM] Exception reported: Entity 10 (10) is invalid
L 10/15/2019 - 19:35:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 19:35:49: [SM] Call stack trace:
L 10/15/2019 - 19:35:49: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 19:35:49: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 19:35:49: Error log file session closed.
L 10/15/2019 - 20:06:45: SourceMod error session started
L 10/15/2019 - 20:06:45: Info (map "c5m4_quarter") (file "errors_20191015.log")
L 10/15/2019 - 20:06:45: [SM] Exception reported: Entity 2 (2) is invalid
L 10/15/2019 - 20:06:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 20:06:45: [SM] Call stack trace:
L 10/15/2019 - 20:06:45: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 20:06:45: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/15/2019 - 20:13:04: Error log file session closed.
L 10/15/2019 - 20:14:51: SourceMod error session started
L 10/15/2019 - 20:14:51: Info (map "c5m5_bridge") (file "errors_20191015.log")
L 10/15/2019 - 20:14:51: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:14:51: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:14:51: [SM] Call stack trace:
L 10/15/2019 - 20:14:51: [SM]   [0] SetEntProp
L 10/15/2019 - 20:14:51: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 20:21:32: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:21:32: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:21:32: [SM] Call stack trace:
L 10/15/2019 - 20:21:32: [SM]   [0] SetEntProp
L 10/15/2019 - 20:21:32: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 20:21:33: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:21:33: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:21:33: [SM] Call stack trace:
L 10/15/2019 - 20:21:33: [SM]   [0] SetEntProp
L 10/15/2019 - 20:21:33: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 20:25:11: [SM] Exception reported: Entity 1 (1) is invalid
L 10/15/2019 - 20:25:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 20:25:11: [SM] Call stack trace:
L 10/15/2019 - 20:25:11: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 20:25:11: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 20:25:12: Error log file session closed.
L 10/15/2019 - 20:27:03: SourceMod error session started
L 10/15/2019 - 20:27:03: Info (map "c1m1_hotel") (file "errors_20191015.log")
L 10/15/2019 - 20:27:03: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:27:03: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:27:03: [SM] Call stack trace:
L 10/15/2019 - 20:27:03: [SM]   [0] SetEntProp
L 10/15/2019 - 20:27:03: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 20:33:17: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 20:33:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 20:33:17: [SM] Call stack trace:
L 10/15/2019 - 20:33:17: [SM]   [0] GetClientTeam
L 10/15/2019 - 20:33:17: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 20:33:17: Error log file session closed.
L 10/15/2019 - 20:36:25: SourceMod error session started
L 10/15/2019 - 20:36:25: Info (map "c1m2_streets") (file "errors_20191015.log")
L 10/15/2019 - 20:36:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:36:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:36:25: [SM] Call stack trace:
L 10/15/2019 - 20:36:25: [SM]   [0] SetEntProp
L 10/15/2019 - 20:36:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 20:36:34: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:36:34: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:36:34: [SM] Call stack trace:
L 10/15/2019 - 20:36:34: [SM]   [0] SetEntProp
L 10/15/2019 - 20:36:34: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 20:36:34: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:36:34: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:36:34: [SM] Call stack trace:
L 10/15/2019 - 20:36:34: [SM]   [0] SetEntProp
L 10/15/2019 - 20:36:34: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 20:38:12: [SM] Exception reported: Client index 262 is invalid
L 10/15/2019 - 20:38:12: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 20:38:12: [SM] Call stack trace:
L 10/15/2019 - 20:38:12: [SM]   [0] IsClientInGame
L 10/15/2019 - 20:38:12: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 20:38:12: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 20:42:52: [SM] Exception reported: Client 1 is not in game
L 10/15/2019 - 20:42:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 20:42:52: [SM] Call stack trace:
L 10/15/2019 - 20:42:52: [SM]   [0] GetClientTeam
L 10/15/2019 - 20:42:52: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 20:44:07: [SM] Exception reported: Client 1 is not in game
L 10/15/2019 - 20:44:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 20:44:07: [SM] Call stack trace:
L 10/15/2019 - 20:44:07: [SM]   [0] GetClientTeam
L 10/15/2019 - 20:44:07: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 20:47:31: Error log file session closed.
L 10/15/2019 - 20:48:00: SourceMod error session started
L 10/15/2019 - 20:48:00: Info (map "c1m3_mall") (file "errors_20191015.log")
L 10/15/2019 - 20:48:00: [SM] Exception reported: Client 6 is not in game
L 10/15/2019 - 20:48:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 20:48:00: [SM] Call stack trace:
L 10/15/2019 - 20:48:00: [SM]   [0] GetClientTeam
L 10/15/2019 - 20:48:00: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 20:53:39: [SM] Exception reported: Entity 2 (2) is invalid
L 10/15/2019 - 20:53:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 20:53:39: [SM] Call stack trace:
L 10/15/2019 - 20:53:39: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 20:53:39: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 20:53:40: Error log file session closed.
L 10/15/2019 - 20:57:24: SourceMod error session started
L 10/15/2019 - 20:57:24: Info (map "c10m1_caves") (file "errors_20191015.log")
L 10/15/2019 - 20:57:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 20:57:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 20:57:24: [SM] Call stack trace:
L 10/15/2019 - 20:57:24: [SM]   [0] SetEntProp
L 10/15/2019 - 20:57:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 21:05:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 21:05:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 21:05:24: [SM] Call stack trace:
L 10/15/2019 - 21:05:24: [SM]   [0] SetEntProp
L 10/15/2019 - 21:05:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 21:05:52: Error log file session closed.
L 10/15/2019 - 21:20:08: SourceMod error session started
L 10/15/2019 - 21:20:08: Info (map "c10m3_ranchhouse") (file "errors_20191015.log")
L 10/15/2019 - 21:20:08: [SM] Exception reported: Client index 211 is invalid
L 10/15/2019 - 21:20:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 21:20:08: [SM] Call stack trace:
L 10/15/2019 - 21:20:08: [SM]   [0] IsClientInGame
L 10/15/2019 - 21:20:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 21:20:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 21:22:49: Error log file session closed.
L 10/15/2019 - 21:42:11: SourceMod error session started
L 10/15/2019 - 21:42:11: Info (map "c10m5_houseboat") (file "errors_20191015.log")
L 10/15/2019 - 21:42:11: [SM] Exception reported: Entity 1 (1) is invalid
L 10/15/2019 - 21:42:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 21:42:11: [SM] Call stack trace:
L 10/15/2019 - 21:42:11: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 21:42:11: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 21:42:13: Error log file session closed.
L 10/15/2019 - 21:54:52: SourceMod error session started
L 10/15/2019 - 21:54:52: Info (map "c4m2_sugarmill_a") (file "errors_20191015.log")
L 10/15/2019 - 21:54:52: [SM] Exception reported: Client index 216 is invalid
L 10/15/2019 - 21:54:52: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 21:54:52: [SM] Call stack trace:
L 10/15/2019 - 21:54:52: [SM]   [0] IsClientInGame
L 10/15/2019 - 21:54:52: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 21:54:52: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 22:01:32: Error log file session closed.
L 10/15/2019 - 22:02:50: SourceMod error session started
L 10/15/2019 - 22:02:50: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 22:02:50: [CRASH] Accelerator uploaded crash dump: Crash ID: R7NR-HUNY-WNRG
L 10/15/2019 - 22:43:52: Error log file session closed.
L 10/15/2019 - 22:48:19: SourceMod error session started
L 10/15/2019 - 22:48:19: Info (map "c11m1_greenhouse") (file "errors_20191015.log")
L 10/15/2019 - 22:48:19: [SM] Exception reported: Client index 195 is invalid
L 10/15/2019 - 22:48:19: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 22:48:19: [SM] Call stack trace:
L 10/15/2019 - 22:48:19: [SM]   [0] IsClientInGame
L 10/15/2019 - 22:48:19: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 22:48:19: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 22:48:21: [SM] Exception reported: Client index 195 is invalid
L 10/15/2019 - 22:48:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 22:48:21: [SM] Call stack trace:
L 10/15/2019 - 22:48:21: [SM]   [0] IsClientInGame
L 10/15/2019 - 22:48:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 22:48:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 22:50:15: Error log file session closed.
L 10/15/2019 - 22:56:03: SourceMod error session started
L 10/15/2019 - 22:56:03: Info (map "c11m2_offices") (file "errors_20191015.log")
L 10/15/2019 - 22:56:03: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 22:56:03: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 22:56:03: [SM] Call stack trace:
L 10/15/2019 - 22:56:03: [SM]   [0] SetEntProp
L 10/15/2019 - 22:56:03: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 22:56:23: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 22:56:23: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 22:56:23: [SM] Call stack trace:
L 10/15/2019 - 22:56:23: [SM]   [0] SetEntProp
L 10/15/2019 - 22:56:23: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 23:04:48: [SM] Exception reported: Client index 323 is invalid
L 10/15/2019 - 23:04:48: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 23:04:48: [SM] Call stack trace:
L 10/15/2019 - 23:04:48: [SM]   [0] IsClientInGame
L 10/15/2019 - 23:04:48: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 23:04:48: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 23:05:46: Error log file session closed.
L 10/15/2019 - 23:17:16: SourceMod error session started
L 10/15/2019 - 23:17:16: Info (map "c11m3_garage") (file "errors_20191015.log")
L 10/15/2019 - 23:17:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 23:17:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 23:17:16: [SM] Call stack trace:
L 10/15/2019 - 23:17:16: [SM]   [0] SetEntProp
L 10/15/2019 - 23:17:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 23:20:22: Error log file session closed.
L 10/15/2019 - 23:21:51: SourceMod error session started
L 10/15/2019 - 23:21:51: Info (map "c11m4_terminal") (file "errors_20191015.log")
L 10/15/2019 - 23:21:51: [SM] Exception reported: Client index 174 is invalid
L 10/15/2019 - 23:21:51: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 23:21:51: [SM] Call stack trace:
L 10/15/2019 - 23:21:51: [SM]   [0] IsClientInGame
L 10/15/2019 - 23:21:51: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 23:21:51: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 23:21:52: [SM] Exception reported: Client index 174 is invalid
L 10/15/2019 - 23:21:52: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/15/2019 - 23:21:52: [SM] Call stack trace:
L 10/15/2019 - 23:21:52: [SM]   [0] IsClientInGame
L 10/15/2019 - 23:21:52: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/15/2019 - 23:21:52: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/15/2019 - 23:28:57: Error log file session closed.
L 10/15/2019 - 23:28:59: SourceMod error session started
L 10/15/2019 - 23:28:59: Info (map "c11m5_runway") (file "errors_20191015.log")
L 10/15/2019 - 23:28:59: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 23:28:59: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/15/2019 - 23:28:59: [SM] Call stack trace:
L 10/15/2019 - 23:28:59: [SM]   [0] IsPlayerAlive
L 10/15/2019 - 23:28:59: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/15/2019 - 23:29:00: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 23:29:00: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/15/2019 - 23:29:00: [SM] Call stack trace:
L 10/15/2019 - 23:29:00: [SM]   [0] IsPlayerAlive
L 10/15/2019 - 23:29:00: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/15/2019 - 23:29:01: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 23:29:01: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/15/2019 - 23:29:01: [SM] Call stack trace:
L 10/15/2019 - 23:29:01: [SM]   [0] IsPlayerAlive
L 10/15/2019 - 23:29:01: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/15/2019 - 23:29:02: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 23:29:02: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/15/2019 - 23:29:02: [SM] Call stack trace:
L 10/15/2019 - 23:29:02: [SM]   [0] IsPlayerAlive
L 10/15/2019 - 23:29:02: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/15/2019 - 23:29:03: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 23:29:03: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/15/2019 - 23:29:03: [SM] Call stack trace:
L 10/15/2019 - 23:29:03: [SM]   [0] IsPlayerAlive
L 10/15/2019 - 23:29:03: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/15/2019 - 23:29:04: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 23:29:04: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/15/2019 - 23:29:04: [SM] Call stack trace:
L 10/15/2019 - 23:29:04: [SM]   [0] IsPlayerAlive
L 10/15/2019 - 23:29:04: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/15/2019 - 23:37:36: Error log file session closed.
L 10/15/2019 - 23:39:27: SourceMod error session started
L 10/15/2019 - 23:39:27: Info (map "c2m1_highway") (file "errors_20191015.log")
L 10/15/2019 - 23:39:27: [CRASH] Accelerator uploaded crash dump: Crash ID: YT3S-277C-AXOS
L 10/15/2019 - 23:39:34: Error log file session closed.
L 10/15/2019 - 23:40:49: SourceMod error session started
L 10/15/2019 - 23:40:49: Info (map "c8m1_apartment") (file "errors_20191015.log")
L 10/15/2019 - 23:40:49: [SM] Exception reported: Client 9 is not in game
L 10/15/2019 - 23:40:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 23:40:49: [SM] Call stack trace:
L 10/15/2019 - 23:40:49: [SM]   [0] GetClientTeam
L 10/15/2019 - 23:40:49: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 23:41:33: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/15/2019 - 23:41:33: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/15/2019 - 23:41:33: [SM] Call stack trace:
L 10/15/2019 - 23:41:33: [SM]   [0] SetEntProp
L 10/15/2019 - 23:41:33: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/15/2019 - 23:46:23: Error log file session closed.
L 10/15/2019 - 23:52:34: SourceMod error session started
L 10/15/2019 - 23:52:34: Info (map "c8m2_subway") (file "errors_20191015.log")
L 10/15/2019 - 23:52:34: [SM] Exception reported: Entity 5 (5) is invalid
L 10/15/2019 - 23:52:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 23:52:34: [SM] Call stack trace:
L 10/15/2019 - 23:52:34: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 23:52:34: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 23:52:34: [SM] Exception reported: Entity 4 (4) is invalid
L 10/15/2019 - 23:52:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 23:52:34: [SM] Call stack trace:
L 10/15/2019 - 23:52:34: [SM]   [0] GetEntDataEnt2
L 10/15/2019 - 23:52:34: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/15/2019 - 23:52:35: Error log file session closed.
L 10/15/2019 - 23:54:49: SourceMod error session started
L 10/15/2019 - 23:54:49: Info (map "c8m3_sewers") (file "errors_20191015.log")
L 10/15/2019 - 23:54:49: [SM] Exception reported: Client 7 is not in game
L 10/15/2019 - 23:54:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/15/2019 - 23:54:49: [SM] Call stack trace:
L 10/15/2019 - 23:54:49: [SM]   [0] GetClientTeam
L 10/15/2019 - 23:54:49: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
