L 10/17/2019 - 14:01:23: SourceMod error session started
L 10/17/2019 - 14:01:23: Info (map "c2m1_highway") (file "errors_20191017.log")
L 10/17/2019 - 14:01:23: [SM] Exception reported: Entity 1 (1) is invalid
L 10/17/2019 - 14:01:23: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 14:01:23: [SM] Call stack trace:
L 10/17/2019 - 14:01:23: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 14:01:23: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 14:01:25: Error log file session closed.
L 10/17/2019 - 17:11:08: SourceMod error session started
L 10/17/2019 - 17:11:08: Info (map "c2m1_highway") (file "errors_20191017.log")
L 10/17/2019 - 17:11:08: [CRASH] Accelerator uploaded crash dump: Crash ID: TKNS-NT76-JVDP
L 10/17/2019 - 19:57:02: Error log file session closed.
L 10/17/2019 - 20:01:35: SourceMod error session started
L 10/17/2019 - 20:01:35: Info (map "c8m1_apartment") (file "errors_20191017.log")
L 10/17/2019 - 20:01:35: [SM] Exception reported: Entity 6 (6) is invalid
L 10/17/2019 - 20:01:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:01:35: [SM] Call stack trace:
L 10/17/2019 - 20:01:35: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 20:01:35: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/17/2019 - 20:02:51: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 20:02:51: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 20:02:51: [SM] Call stack trace:
L 10/17/2019 - 20:02:51: [SM]   [0] SetEntProp
L 10/17/2019 - 20:02:51: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 20:02:51: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 20:02:51: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 20:02:51: [SM] Call stack trace:
L 10/17/2019 - 20:02:51: [SM]   [0] SetEntProp
L 10/17/2019 - 20:02:51: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 20:03:09: [SM] Exception reported: Client index 166 is invalid
L 10/17/2019 - 20:03:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 20:03:09: [SM] Call stack trace:
L 10/17/2019 - 20:03:09: [SM]   [0] IsClientInGame
L 10/17/2019 - 20:03:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 20:03:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 20:03:39: [SM] Exception reported: Client 8 is not in game
L 10/17/2019 - 20:03:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:03:39: [SM] Call stack trace:
L 10/17/2019 - 20:03:39: [SM]   [0] GetClientTeam
L 10/17/2019 - 20:03:39: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 20:03:41: Error log file session closed.
L 10/17/2019 - 20:07:41: SourceMod error session started
L 10/17/2019 - 20:07:41: Info (map "c8m2_subway") (file "errors_20191017.log")
L 10/17/2019 - 20:07:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 20:07:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 20:07:41: [SM] Call stack trace:
L 10/17/2019 - 20:07:41: [SM]   [0] SetEntProp
L 10/17/2019 - 20:07:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 20:18:01: [SM] Exception reported: Entity 8 (8) is invalid
L 10/17/2019 - 20:18:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:18:01: [SM] Call stack trace:
L 10/17/2019 - 20:18:01: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 20:18:01: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/17/2019 - 20:18:02: Error log file session closed.
L 10/17/2019 - 20:19:14: SourceMod error session started
L 10/17/2019 - 20:19:14: Info (map "c8m3_sewers") (file "errors_20191017.log")
L 10/17/2019 - 20:19:14: [SM] Exception reported: Client 5 is not in game
L 10/17/2019 - 20:19:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:19:14: [SM] Call stack trace:
L 10/17/2019 - 20:19:14: [SM]   [0] GetClientTeam
L 10/17/2019 - 20:19:14: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 20:19:14: Error log file session closed.
L 10/17/2019 - 20:24:53: SourceMod error session started
L 10/17/2019 - 20:24:53: Info (map "c2m1_highway") (file "errors_20191017.log")
L 10/17/2019 - 20:24:53: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 20:24:53: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 20:24:53: [SM] Call stack trace:
L 10/17/2019 - 20:24:53: [SM]   [0] SetEntProp
L 10/17/2019 - 20:24:53: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 20:34:36: [SM] Exception reported: Client 3 is not in game
L 10/17/2019 - 20:34:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:34:36: [SM] Call stack trace:
L 10/17/2019 - 20:34:36: [SM]   [0] GetClientTeam
L 10/17/2019 - 20:34:36: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 20:34:36: [SM] Exception reported: Entity 1 (1) is invalid
L 10/17/2019 - 20:34:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:34:36: [SM] Call stack trace:
L 10/17/2019 - 20:34:36: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 20:34:36: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 20:34:36: Error log file session closed.
L 10/17/2019 - 20:35:56: SourceMod error session started
L 10/17/2019 - 20:35:56: Info (map "c2m2_fairgrounds") (file "errors_20191017.log")
L 10/17/2019 - 20:35:56: [SM] Exception reported: Client index 370 is invalid
L 10/17/2019 - 20:35:56: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 20:35:56: [SM] Call stack trace:
L 10/17/2019 - 20:35:56: [SM]   [0] IsClientInGame
L 10/17/2019 - 20:35:56: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 20:35:56: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 20:36:00: [SM] Exception reported: Client index 370 is invalid
L 10/17/2019 - 20:36:00: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 20:36:00: [SM] Call stack trace:
L 10/17/2019 - 20:36:00: [SM]   [0] IsClientInGame
L 10/17/2019 - 20:36:00: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 20:36:00: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 20:38:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 20:38:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 20:38:41: [SM] Call stack trace:
L 10/17/2019 - 20:38:41: [SM]   [0] SetEntProp
L 10/17/2019 - 20:38:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 20:50:29: [SM] Exception reported: Entity 9 (9) is invalid
L 10/17/2019 - 20:50:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:50:29: [SM] Call stack trace:
L 10/17/2019 - 20:50:29: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 20:50:29: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/17/2019 - 20:50:29: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 20:50:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 20:50:29: [SM] Call stack trace:
L 10/17/2019 - 20:50:29: [SM]   [0] GetClientTeam
L 10/17/2019 - 20:50:29: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 20:50:30: Error log file session closed.
L 10/17/2019 - 20:53:43: SourceMod error session started
L 10/17/2019 - 20:53:43: Info (map "c2m3_coaster") (file "errors_20191017.log")
L 10/17/2019 - 20:53:43: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 20:53:43: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 20:53:43: [SM] Call stack trace:
L 10/17/2019 - 20:53:43: [SM]   [0] SetEntProp
L 10/17/2019 - 20:53:43: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 21:01:39: Error log file session closed.
L 10/17/2019 - 21:03:11: SourceMod error session started
L 10/17/2019 - 21:03:11: Info (map "c2m4_barns") (file "errors_20191017.log")
L 10/17/2019 - 21:03:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 21:03:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 21:03:11: [SM] Call stack trace:
L 10/17/2019 - 21:03:11: [SM]   [0] SetEntProp
L 10/17/2019 - 21:03:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 21:10:16: Error log file session closed.
L 10/17/2019 - 21:10:57: SourceMod error session started
L 10/17/2019 - 21:10:57: Info (map "c2m5_concert") (file "errors_20191017.log")
L 10/17/2019 - 21:10:57: [SM] Exception reported: Client index 529 is invalid
L 10/17/2019 - 21:10:57: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 21:10:57: [SM] Call stack trace:
L 10/17/2019 - 21:10:57: [SM]   [0] IsClientInGame
L 10/17/2019 - 21:10:57: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 21:10:57: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 21:11:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 21:11:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 21:11:20: [SM] Call stack trace:
L 10/17/2019 - 21:11:20: [SM]   [0] SetEntProp
L 10/17/2019 - 21:11:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 21:11:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 21:11:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 21:11:28: [SM] Call stack trace:
L 10/17/2019 - 21:11:28: [SM]   [0] SetEntProp
L 10/17/2019 - 21:11:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 21:13:38: [SM] Exception reported: Client index 450 is invalid
L 10/17/2019 - 21:13:38: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 21:13:38: [SM] Call stack trace:
L 10/17/2019 - 21:13:38: [SM]   [0] IsClientInGame
L 10/17/2019 - 21:13:38: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 21:13:38: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 21:13:53: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 21:13:53: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 21:13:53: [SM] Call stack trace:
L 10/17/2019 - 21:13:53: [SM]   [0] SetEntProp
L 10/17/2019 - 21:13:53: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 21:23:28: [SM] Exception reported: Entity 2 (2) is invalid
L 10/17/2019 - 21:23:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 21:23:28: [SM] Call stack trace:
L 10/17/2019 - 21:23:28: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 21:23:28: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 21:23:29: [SM] Exception reported: Entity 3 (3) is invalid
L 10/17/2019 - 21:23:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 21:23:29: [SM] Call stack trace:
L 10/17/2019 - 21:23:29: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 21:23:29: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 21:23:29: Error log file session closed.
L 10/17/2019 - 21:28:45: SourceMod error session started
L 10/17/2019 - 21:28:45: Info (map "c1m1_hotel") (file "errors_20191017.log")
L 10/17/2019 - 21:28:45: [SM] Exception reported: Client index 285 is invalid
L 10/17/2019 - 21:28:45: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 21:28:45: [SM] Call stack trace:
L 10/17/2019 - 21:28:45: [SM]   [0] IsClientInGame
L 10/17/2019 - 21:28:45: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 21:28:45: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 21:31:58: [SM] Exception reported: Entity 2 (2) is invalid
L 10/17/2019 - 21:31:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 21:31:58: [SM] Call stack trace:
L 10/17/2019 - 21:31:58: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 21:31:58: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/17/2019 - 21:40:09: [SM] Exception reported: Client 5 is not in game
L 10/17/2019 - 21:40:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 21:40:09: [SM] Call stack trace:
L 10/17/2019 - 21:40:09: [SM]   [0] GetClientTeam
L 10/17/2019 - 21:40:09: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 21:40:09: [SM] Exception reported: Entity 1 (1) is invalid
L 10/17/2019 - 21:40:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 21:40:09: [SM] Call stack trace:
L 10/17/2019 - 21:40:09: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 21:40:09: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 21:40:09: [SM] Exception reported: Entity 5 (5) is invalid
L 10/17/2019 - 21:40:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 21:40:09: [SM] Call stack trace:
L 10/17/2019 - 21:40:09: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 21:40:09: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 21:40:09: Error log file session closed.
L 10/17/2019 - 21:54:16: SourceMod error session started
L 10/17/2019 - 21:54:16: Info (map "c1m2_streets") (file "errors_20191017.log")
L 10/17/2019 - 21:54:16: [SM] Exception reported: Client index 520 is invalid
L 10/17/2019 - 21:54:16: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 21:54:16: [SM] Call stack trace:
L 10/17/2019 - 21:54:16: [SM]   [0] IsClientInGame
L 10/17/2019 - 21:54:16: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 21:54:16: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 21:58:34: Error log file session closed.
L 10/17/2019 - 22:13:23: SourceMod error session started
L 10/17/2019 - 22:13:23: Info (map "c1m4_atrium") (file "errors_20191017.log")
L 10/17/2019 - 22:13:23: [SM] Exception reported: Client index 427 is invalid
L 10/17/2019 - 22:13:23: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 22:13:23: [SM] Call stack trace:
L 10/17/2019 - 22:13:23: [SM]   [0] IsClientInGame
L 10/17/2019 - 22:13:23: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 22:13:23: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 22:14:58: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 22:14:58: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 22:14:58: [SM] Call stack trace:
L 10/17/2019 - 22:14:58: [SM]   [0] SetEntProp
L 10/17/2019 - 22:14:58: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 22:18:38: [SM] Exception reported: Client 4 is not in game
L 10/17/2019 - 22:18:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 22:18:38: [SM] Call stack trace:
L 10/17/2019 - 22:18:38: [SM]   [0] GetClientTeam
L 10/17/2019 - 22:18:38: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 22:18:38: [SM] Exception reported: Entity 1 (1) is invalid
L 10/17/2019 - 22:18:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 22:18:38: [SM] Call stack trace:
L 10/17/2019 - 22:18:38: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 22:18:38: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 22:18:38: Error log file session closed.
L 10/17/2019 - 22:33:55: SourceMod error session started
L 10/17/2019 - 22:33:55: Info (map "c2m1_highway") (file "errors_20191017.log")
L 10/17/2019 - 22:33:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 22:33:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 22:33:55: [SM] Call stack trace:
L 10/17/2019 - 22:33:55: [SM]   [0] SetEntProp
L 10/17/2019 - 22:33:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 22:34:22: Error log file session closed.
L 10/17/2019 - 22:48:20: SourceMod error session started
L 10/17/2019 - 22:48:20: Info (map "c2m2_fairgrounds") (file "errors_20191017.log")
L 10/17/2019 - 22:48:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 22:48:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 22:48:20: [SM] Call stack trace:
L 10/17/2019 - 22:48:20: [SM]   [0] SetEntProp
L 10/17/2019 - 22:48:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 22:49:07: [SM] Exception reported: Entity 6 (6) is invalid
L 10/17/2019 - 22:49:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 22:49:07: [SM] Call stack trace:
L 10/17/2019 - 22:49:07: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 22:49:07: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/17/2019 - 22:49:08: Error log file session closed.
L 10/17/2019 - 22:49:09: SourceMod error session started
L 10/17/2019 - 22:49:09: Info (map "c2m3_coaster") (file "errors_20191017.log")
L 10/17/2019 - 22:49:09: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 22:49:09: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/17/2019 - 22:49:09: [SM] Call stack trace:
L 10/17/2019 - 22:49:09: [SM]   [0] IsPlayerAlive
L 10/17/2019 - 22:49:09: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/17/2019 - 22:49:10: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 22:49:10: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/17/2019 - 22:49:10: [SM] Call stack trace:
L 10/17/2019 - 22:49:10: [SM]   [0] IsPlayerAlive
L 10/17/2019 - 22:49:10: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/17/2019 - 22:49:11: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 22:49:11: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/17/2019 - 22:49:11: [SM] Call stack trace:
L 10/17/2019 - 22:49:11: [SM]   [0] IsPlayerAlive
L 10/17/2019 - 22:49:11: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/17/2019 - 22:49:12: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 22:49:12: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/17/2019 - 22:49:12: [SM] Call stack trace:
L 10/17/2019 - 22:49:12: [SM]   [0] IsPlayerAlive
L 10/17/2019 - 22:49:12: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/17/2019 - 22:49:13: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 22:49:13: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/17/2019 - 22:49:13: [SM] Call stack trace:
L 10/17/2019 - 22:49:13: [SM]   [0] IsPlayerAlive
L 10/17/2019 - 22:49:13: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/17/2019 - 22:49:14: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 22:49:14: [SM] Blaming: l4d2_tank_attack_control_nextmod.smx
L 10/17/2019 - 22:49:14: [SM] Call stack trace:
L 10/17/2019 - 22:49:14: [SM]   [0] IsPlayerAlive
L 10/17/2019 - 22:49:14: [SM]   [1] Line 220, C:\Users\Trevor_2\Desktop\New Desktop Mass Storage Lmfao\scripting\l4d2_tank_attack_control_nextmod.sp::Timer_Countdown
L 10/17/2019 - 22:53:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 22:53:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 22:53:16: [SM] Call stack trace:
L 10/17/2019 - 22:53:16: [SM]   [0] SetEntProp
L 10/17/2019 - 22:53:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 22:53:22: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 22:53:22: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 22:53:22: [SM] Call stack trace:
L 10/17/2019 - 22:53:22: [SM]   [0] SetEntProp
L 10/17/2019 - 22:53:22: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:09:57: Error log file session closed.
L 10/17/2019 - 23:21:17: SourceMod error session started
L 10/17/2019 - 23:21:17: Info (map "c2m5_concert") (file "errors_20191017.log")
L 10/17/2019 - 23:21:17: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 23:21:17: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 23:21:17: [SM] Call stack trace:
L 10/17/2019 - 23:21:17: [SM]   [0] SetEntProp
L 10/17/2019 - 23:21:17: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:27:35: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 23:27:35: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 23:27:35: [SM] Call stack trace:
L 10/17/2019 - 23:27:35: [SM]   [0] SetEntProp
L 10/17/2019 - 23:27:35: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:28:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 23:28:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 23:28:57: [SM] Call stack trace:
L 10/17/2019 - 23:28:57: [SM]   [0] SetEntProp
L 10/17/2019 - 23:28:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:31:08: [SM] Exception reported: Client 11 is not in game
L 10/17/2019 - 23:31:08: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:31:08: [SM] Call stack trace:
L 10/17/2019 - 23:31:08: [SM]   [0] GetClientTeam
L 10/17/2019 - 23:31:08: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:31:09: Error log file session closed.
L 10/17/2019 - 23:37:55: SourceMod error session started
L 10/17/2019 - 23:37:55: Info (map "c5m1_waterfront") (file "errors_20191017.log")
L 10/17/2019 - 23:37:55: [SM] Exception reported: Client 2 is not in game
L 10/17/2019 - 23:37:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:37:55: [SM] Call stack trace:
L 10/17/2019 - 23:37:55: [SM]   [0] GetClientTeam
L 10/17/2019 - 23:37:55: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:38:06: [SM] Exception reported: Client 11 is not in game
L 10/17/2019 - 23:38:06: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:38:06: [SM] Call stack trace:
L 10/17/2019 - 23:38:06: [SM]   [0] GetClientTeam
L 10/17/2019 - 23:38:06: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:38:25: [SM] Exception reported: Client 2 is not in game
L 10/17/2019 - 23:38:25: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:38:25: [SM] Call stack trace:
L 10/17/2019 - 23:38:25: [SM]   [0] GetClientTeam
L 10/17/2019 - 23:38:25: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:43:39: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 23:43:39: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 23:43:39: [SM] Call stack trace:
L 10/17/2019 - 23:43:39: [SM]   [0] SetEntProp
L 10/17/2019 - 23:43:39: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:43:44: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 23:43:44: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 23:43:44: [SM] Call stack trace:
L 10/17/2019 - 23:43:44: [SM]   [0] SetEntProp
L 10/17/2019 - 23:43:44: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:46:39: [SM] Exception reported: Entity 3 (3) is invalid
L 10/17/2019 - 23:46:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:46:39: [SM] Call stack trace:
L 10/17/2019 - 23:46:39: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 23:46:39: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:46:39: [SM] Exception reported: Entity 5 (5) is invalid
L 10/17/2019 - 23:46:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:46:39: [SM] Call stack trace:
L 10/17/2019 - 23:46:39: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 23:46:39: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:46:39: [SM] Exception reported: Entity 9 (9) is invalid
L 10/17/2019 - 23:46:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:46:39: [SM] Call stack trace:
L 10/17/2019 - 23:46:39: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 23:46:39: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:46:40: Error log file session closed.
L 10/17/2019 - 23:50:16: SourceMod error session started
L 10/17/2019 - 23:50:16: Info (map "c5m2_park") (file "errors_20191017.log")
L 10/17/2019 - 23:50:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 23:50:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 23:50:16: [SM] Call stack trace:
L 10/17/2019 - 23:50:16: [SM]   [0] SetEntProp
L 10/17/2019 - 23:50:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:50:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/17/2019 - 23:50:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/17/2019 - 23:50:28: [SM] Call stack trace:
L 10/17/2019 - 23:50:28: [SM]   [0] SetEntProp
L 10/17/2019 - 23:50:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/17/2019 - 23:55:17: [SM] Exception reported: Client 5 is not in game
L 10/17/2019 - 23:55:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:55:17: [SM] Call stack trace:
L 10/17/2019 - 23:55:17: [SM]   [0] GetClientTeam
L 10/17/2019 - 23:55:17: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:58:07: [SM] Exception reported: Client index 463 is invalid
L 10/17/2019 - 23:58:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 23:58:07: [SM] Call stack trace:
L 10/17/2019 - 23:58:07: [SM]   [0] IsClientInGame
L 10/17/2019 - 23:58:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 23:58:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 23:58:08: [SM] Exception reported: Client index 463 is invalid
L 10/17/2019 - 23:58:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/17/2019 - 23:58:08: [SM] Call stack trace:
L 10/17/2019 - 23:58:08: [SM]   [0] IsClientInGame
L 10/17/2019 - 23:58:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/17/2019 - 23:58:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/17/2019 - 23:59:30: [SM] Exception reported: Client 6 is not in game
L 10/17/2019 - 23:59:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:59:30: [SM] Call stack trace:
L 10/17/2019 - 23:59:30: [SM]   [0] GetClientTeam
L 10/17/2019 - 23:59:30: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:59:30: [SM] Exception reported: Entity 4 (4) is invalid
L 10/17/2019 - 23:59:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:59:30: [SM] Call stack trace:
L 10/17/2019 - 23:59:30: [SM]   [0] GetEntDataEnt2
L 10/17/2019 - 23:59:30: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:59:30: [SM] Exception reported: Client 9 is not in game
L 10/17/2019 - 23:59:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/17/2019 - 23:59:30: [SM] Call stack trace:
L 10/17/2019 - 23:59:30: [SM]   [0] GetClientTeam
L 10/17/2019 - 23:59:30: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/17/2019 - 23:59:32: Error log file session closed.
