L 11/05/2019 - 01:17:20: SourceMod error session started
L 11/05/2019 - 01:17:20: Info (map "c2m1_highway") (file "errors_20191105.log")
L 11/05/2019 - 01:17:20: [SM] Exception reported: Entity 7 (7) is invalid
L 11/05/2019 - 01:17:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 01:17:20: [SM] Call stack trace:
L 11/05/2019 - 01:17:20: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 01:17:20: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 01:17:22: Error log file session closed.
L 11/05/2019 - 01:36:42: SourceMod error session started
L 11/05/2019 - 01:36:42: Info (map "c8m2_subway") (file "errors_20191105.log")
L 11/05/2019 - 01:36:42: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 01:36:42: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 01:36:42: [SM] Call stack trace:
L 11/05/2019 - 01:36:42: [SM]   [0] SetEntProp
L 11/05/2019 - 01:36:42: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 01:42:51: Error log file session closed.
L 11/05/2019 - 01:48:38: SourceMod error session started
L 11/05/2019 - 01:48:38: Info (map "c8m3_sewers") (file "errors_20191105.log")
L 11/05/2019 - 01:48:38: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 01:48:38: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 01:48:38: [SM] Call stack trace:
L 11/05/2019 - 01:48:38: [SM]   [0] SetEntProp
L 11/05/2019 - 01:48:38: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 02:00:54: [SM] Exception reported: Entity 2 (2) is invalid
L 11/05/2019 - 02:00:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:00:54: [SM] Call stack trace:
L 11/05/2019 - 02:00:54: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 02:00:54: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 02:00:56: Error log file session closed.
L 11/05/2019 - 02:14:17: SourceMod error session started
L 11/05/2019 - 02:14:17: Info (map "c8m4_interior") (file "errors_20191105.log")
L 11/05/2019 - 02:14:17: [SM] Exception reported: Client 4 is not in game
L 11/05/2019 - 02:14:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:14:17: [SM] Call stack trace:
L 11/05/2019 - 02:14:17: [SM]   [0] GetClientTeam
L 11/05/2019 - 02:14:17: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 02:16:44: [SM] Exception reported: Entity 9 (9) is invalid
L 11/05/2019 - 02:16:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:16:44: [SM] Call stack trace:
L 11/05/2019 - 02:16:44: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 02:16:44: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 02:16:45: Error log file session closed.
L 11/05/2019 - 02:20:58: SourceMod error session started
L 11/05/2019 - 02:20:58: Info (map "c8m5_rooftop") (file "errors_20191105.log")
L 11/05/2019 - 02:20:58: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 02:20:58: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 02:20:58: [SM] Call stack trace:
L 11/05/2019 - 02:20:58: [SM]   [0] SetEntProp
L 11/05/2019 - 02:20:58: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 02:22:54: [SM] Exception reported: Entity 2 (2) is invalid
L 11/05/2019 - 02:22:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:22:54: [SM] Call stack trace:
L 11/05/2019 - 02:22:54: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 02:22:54: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 02:22:54: [SM] Exception reported: Entity 5 (5) is invalid
L 11/05/2019 - 02:22:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:22:54: [SM] Call stack trace:
L 11/05/2019 - 02:22:54: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 02:22:54: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 02:22:54: Error log file session closed.
L 11/05/2019 - 02:22:56: SourceMod error session started
L 11/05/2019 - 02:22:56: Info (map "c10m1_caves") (file "errors_20191105.log")
L 11/05/2019 - 02:22:56: [SM] Exception reported: Client 6 is not in game
L 11/05/2019 - 02:22:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:22:56: [SM] Call stack trace:
L 11/05/2019 - 02:22:56: [SM]   [0] GetClientTeam
L 11/05/2019 - 02:22:56: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 02:25:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 02:25:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 02:25:41: [SM] Call stack trace:
L 11/05/2019 - 02:25:41: [SM]   [0] SetEntProp
L 11/05/2019 - 02:25:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 02:33:13: Error log file session closed.
L 11/05/2019 - 02:33:16: SourceMod error session started
L 11/05/2019 - 02:33:16: Info (map "c10m2_drainage") (file "errors_20191105.log")
L 11/05/2019 - 02:33:16: [SM] Exception reported: Client 8 is not in game
L 11/05/2019 - 02:33:16: [SM] Blaming: si_fire_immunity.smx
L 11/05/2019 - 02:33:16: [SM] Call stack trace:
L 11/05/2019 - 02:33:16: [SM]   [0] ExtinguishEntity
L 11/05/2019 - 02:33:16: [SM]   [1] Line 56, crash/si_fire_immunity.sp::Extinguish
L 11/05/2019 - 02:35:04: [SM] Exception reported: Client index 267 is invalid
L 11/05/2019 - 02:35:04: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 02:35:04: [SM] Call stack trace:
L 11/05/2019 - 02:35:04: [SM]   [0] IsClientInGame
L 11/05/2019 - 02:35:04: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 02:35:04: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 02:37:03: [SM] Exception reported: Entity 9 (9) is invalid
L 11/05/2019 - 02:37:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:37:03: [SM] Call stack trace:
L 11/05/2019 - 02:37:03: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 02:37:03: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 02:42:09: [SM] Exception reported: Entity 4 (4) is invalid
L 11/05/2019 - 02:42:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 02:42:09: [SM] Call stack trace:
L 11/05/2019 - 02:42:09: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 02:42:09: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 02:42:10: Error log file session closed.
L 11/05/2019 - 03:06:00: SourceMod error session started
L 11/05/2019 - 03:06:00: Info (map "c10m4_mainstreet") (file "errors_20191105.log")
L 11/05/2019 - 03:06:00: [SM] Exception reported: Client 8 is not in game
L 11/05/2019 - 03:06:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 03:06:00: [SM] Call stack trace:
L 11/05/2019 - 03:06:00: [SM]   [0] GetClientTeam
L 11/05/2019 - 03:06:00: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 03:06:01: Error log file session closed.
L 11/05/2019 - 03:22:32: SourceMod error session started
L 11/05/2019 - 03:22:32: Info (map "c10m5_houseboat") (file "errors_20191105.log")
L 11/05/2019 - 03:22:32: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 03:22:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 03:22:32: [SM] Call stack trace:
L 11/05/2019 - 03:22:32: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 03:22:32: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 03:22:33: Error log file session closed.
L 11/05/2019 - 03:27:28: SourceMod error session started
L 11/05/2019 - 03:27:28: Info (map "c11m1_greenhouse") (file "errors_20191105.log")
L 11/05/2019 - 03:27:28: [SM] Exception reported: Client index 244 is invalid
L 11/05/2019 - 03:27:28: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 03:27:28: [SM] Call stack trace:
L 11/05/2019 - 03:27:28: [SM]   [0] IsClientInGame
L 11/05/2019 - 03:27:28: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 03:27:28: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 03:27:28: [SM] Exception reported: Client index 244 is invalid
L 11/05/2019 - 03:27:28: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 03:27:28: [SM] Call stack trace:
L 11/05/2019 - 03:27:28: [SM]   [0] IsClientInGame
L 11/05/2019 - 03:27:28: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 03:27:28: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 03:27:30: [SM] Exception reported: Client index 244 is invalid
L 11/05/2019 - 03:27:30: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 03:27:30: [SM] Call stack trace:
L 11/05/2019 - 03:27:30: [SM]   [0] IsClientInGame
L 11/05/2019 - 03:27:30: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 03:27:30: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 03:27:31: [SM] Exception reported: Client index 244 is invalid
L 11/05/2019 - 03:27:31: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 03:27:31: [SM] Call stack trace:
L 11/05/2019 - 03:27:31: [SM]   [0] IsClientInGame
L 11/05/2019 - 03:27:31: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 03:27:31: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 03:29:50: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 03:29:50: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 03:29:50: [SM] Call stack trace:
L 11/05/2019 - 03:29:50: [SM]   [0] SetEntProp
L 11/05/2019 - 03:29:50: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 03:31:20: Error log file session closed.
L 11/05/2019 - 03:38:10: SourceMod error session started
L 11/05/2019 - 03:38:10: Info (map "c11m2_offices") (file "errors_20191105.log")
L 11/05/2019 - 03:38:10: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 03:38:10: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 03:38:10: [SM] Call stack trace:
L 11/05/2019 - 03:38:10: [SM]   [0] SetEntProp
L 11/05/2019 - 03:38:10: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 03:46:11: [SM] Exception reported: Client 1 is not in game
L 11/05/2019 - 03:46:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 03:46:11: [SM] Call stack trace:
L 11/05/2019 - 03:46:11: [SM]   [0] GetClientTeam
L 11/05/2019 - 03:46:11: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 03:48:54: SourceMod error session started
L 11/05/2019 - 03:48:54: Info (map "c2m1_highway") (file "errors_20191105.log")
L 11/05/2019 - 03:48:54: [CRASH] Accelerator uploaded crash dump: Crash ID: DU2Y-VSEK-AKOR
L 11/05/2019 - 13:34:26: Error log file session closed.
L 11/05/2019 - 13:45:10: SourceMod error session started
L 11/05/2019 - 13:45:10: Info (map "c2m1_highway") (file "errors_20191105.log")
L 11/05/2019 - 13:45:10: [SM] Exception reported: Entity 7 (7) is invalid
L 11/05/2019 - 13:45:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 13:45:10: [SM] Call stack trace:
L 11/05/2019 - 13:45:10: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 13:45:10: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 13:47:01: Error log file session closed.
L 11/05/2019 - 13:52:38: SourceMod error session started
L 11/05/2019 - 13:52:38: Info (map "c2m1_highway") (file "errors_20191105.log")
L 11/05/2019 - 13:52:38: [SM] Exception reported: Client 4 is not in game
L 11/05/2019 - 13:52:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 13:52:38: [SM] Call stack trace:
L 11/05/2019 - 13:52:38: [SM]   [0] GetClientTeam
L 11/05/2019 - 13:52:38: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 13:52:38: [SM] Exception reported: Entity 5 (5) is invalid
L 11/05/2019 - 13:52:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 13:52:38: [SM] Call stack trace:
L 11/05/2019 - 13:52:38: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 13:52:38: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 13:52:39: Error log file session closed.
L 11/05/2019 - 14:02:12: SourceMod error session started
L 11/05/2019 - 14:02:12: Info (map "c2m2_fairgrounds") (file "errors_20191105.log")
L 11/05/2019 - 14:02:12: [SM] Exception reported: Entity 4 (4) is invalid
L 11/05/2019 - 14:02:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 14:02:12: [SM] Call stack trace:
L 11/05/2019 - 14:02:12: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 14:02:12: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 14:11:19: [SM] Exception reported: Entity 6 (6) is invalid
L 11/05/2019 - 14:11:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 14:11:19: [SM] Call stack trace:
L 11/05/2019 - 14:11:19: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 14:11:19: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 14:11:19: [SM] Exception reported: Client 6 is not in game
L 11/05/2019 - 14:11:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 14:11:19: [SM] Call stack trace:
L 11/05/2019 - 14:11:19: [SM]   [0] GetClientTeam
L 11/05/2019 - 14:11:19: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 14:11:20: Error log file session closed.
L 11/05/2019 - 14:16:39: SourceMod error session started
L 11/05/2019 - 14:16:39: Info (map "c2m3_coaster") (file "errors_20191105.log")
L 11/05/2019 - 14:16:39: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 14:16:39: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 14:16:39: [SM] Call stack trace:
L 11/05/2019 - 14:16:39: [SM]   [0] SetEntProp
L 11/05/2019 - 14:16:39: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 14:17:59: Error log file session closed.
L 11/05/2019 - 14:23:28: SourceMod error session started
L 11/05/2019 - 14:23:28: Info (map "c2m4_barns") (file "errors_20191105.log")
L 11/05/2019 - 14:23:28: [SM] Exception reported: Client index 214 is invalid
L 11/05/2019 - 14:23:28: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 14:23:28: [SM] Call stack trace:
L 11/05/2019 - 14:23:28: [SM]   [0] IsClientInGame
L 11/05/2019 - 14:23:28: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 14:23:28: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 14:35:18: [SM] Exception reported: Client index 369 is invalid
L 11/05/2019 - 14:35:18: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 14:35:18: [SM] Call stack trace:
L 11/05/2019 - 14:35:18: [SM]   [0] IsClientInGame
L 11/05/2019 - 14:35:18: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 14:35:18: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 14:37:47: Error log file session closed.
L 11/05/2019 - 14:40:11: SourceMod error session started
L 11/05/2019 - 14:40:11: Info (map "c2m5_concert") (file "errors_20191105.log")
L 11/05/2019 - 14:40:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 14:40:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 14:40:11: [SM] Call stack trace:
L 11/05/2019 - 14:40:11: [SM]   [0] SetEntProp
L 11/05/2019 - 14:40:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 14:41:23: [SM] Exception reported: Client index 502 is invalid
L 11/05/2019 - 14:41:23: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 14:41:23: [SM] Call stack trace:
L 11/05/2019 - 14:41:23: [SM]   [0] IsClientInGame
L 11/05/2019 - 14:41:23: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 14:41:23: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 14:41:25: [SM] Exception reported: Client index 502 is invalid
L 11/05/2019 - 14:41:25: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 14:41:25: [SM] Call stack trace:
L 11/05/2019 - 14:41:25: [SM]   [0] IsClientInGame
L 11/05/2019 - 14:41:25: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 14:41:25: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 14:41:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 14:41:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 14:41:28: [SM] Call stack trace:
L 11/05/2019 - 14:41:28: [SM]   [0] SetEntProp
L 11/05/2019 - 14:41:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 14:42:15: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 14:42:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 14:42:15: [SM] Call stack trace:
L 11/05/2019 - 14:42:15: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 14:42:15: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 14:42:15: [SM] Exception reported: Entity 2 (2) is invalid
L 11/05/2019 - 14:42:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 14:42:15: [SM] Call stack trace:
L 11/05/2019 - 14:42:15: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 14:42:15: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 14:42:15: Error log file session closed.
L 11/05/2019 - 14:46:09: SourceMod error session started
L 11/05/2019 - 14:46:09: Info (map "c5m1_waterfront") (file "errors_20191105.log")
L 11/05/2019 - 14:46:09: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 14:46:09: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 14:46:09: [SM] Call stack trace:
L 11/05/2019 - 14:46:09: [SM]   [0] SetEntProp
L 11/05/2019 - 14:46:09: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 14:46:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 14:46:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 14:46:28: [SM] Call stack trace:
L 11/05/2019 - 14:46:28: [SM]   [0] SetEntProp
L 11/05/2019 - 14:46:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 14:49:34: [SM] Exception reported: Client index 312 is invalid
L 11/05/2019 - 14:49:34: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 14:49:34: [SM] Call stack trace:
L 11/05/2019 - 14:49:34: [SM]   [0] IsClientInGame
L 11/05/2019 - 14:49:34: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 14:49:34: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 14:49:36: [SM] Exception reported: Client index 312 is invalid
L 11/05/2019 - 14:49:36: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 14:49:36: [SM] Call stack trace:
L 11/05/2019 - 14:49:36: [SM]   [0] IsClientInGame
L 11/05/2019 - 14:49:36: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 14:49:36: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 14:56:07: Error log file session closed.
L 11/05/2019 - 15:00:41: SourceMod error session started
L 11/05/2019 - 15:00:41: Info (map "c5m2_park") (file "errors_20191105.log")
L 11/05/2019 - 15:00:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 15:00:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 15:00:41: [SM] Call stack trace:
L 11/05/2019 - 15:00:41: [SM]   [0] SetEntProp
L 11/05/2019 - 15:00:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 15:03:50: SourceMod error session started
L 11/05/2019 - 15:03:50: Info (map "c2m1_highway") (file "errors_20191105.log")
L 11/05/2019 - 15:03:50: [UPDATER] --- BEGIN ERRORS FROM AUTOMATIC UPDATER ---
L 11/05/2019 - 15:03:50: [UPDATER] Could not download "http://update.sourcemod.net/update/"
L 11/05/2019 - 15:03:50: [UPDATER] Error: Couldn't resolve host 'update.sourcemod.net'
L 11/05/2019 - 15:03:50: [UPDATER] --- END ERRORS FROM AUTOMATIC UPDATER ---
L 11/05/2019 - 15:03:59: Error log file session closed.
L 11/05/2019 - 15:23:22: SourceMod error session started
L 11/05/2019 - 15:23:22: Info (map "c4m2_sugarmill_a") (file "errors_20191105.log")
L 11/05/2019 - 15:23:22: [SM] Exception reported: Entity 11 (11) is invalid
L 11/05/2019 - 15:23:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 15:23:22: [SM] Call stack trace:
L 11/05/2019 - 15:23:22: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 15:23:22: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 15:28:18: [SM] Exception reported: Client index 113 is invalid
L 11/05/2019 - 15:28:18: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 15:28:18: [SM] Call stack trace:
L 11/05/2019 - 15:28:18: [SM]   [0] IsClientInGame
L 11/05/2019 - 15:28:18: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 15:28:18: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 15:33:14: [SM] Exception reported: Entity 11 (11) is invalid
L 11/05/2019 - 15:33:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 15:33:14: [SM] Call stack trace:
L 11/05/2019 - 15:33:14: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 15:33:14: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 15:37:56: Error log file session closed.
L 11/05/2019 - 15:42:46: SourceMod error session started
L 11/05/2019 - 15:42:46: Info (map "c4m3_sugarmill_b") (file "errors_20191105.log")
L 11/05/2019 - 15:42:46: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 15:42:46: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 15:42:46: [SM] Call stack trace:
L 11/05/2019 - 15:42:46: [SM]   [0] SetEntProp
L 11/05/2019 - 15:42:46: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 15:52:45: [SM] Exception reported: Entity 7 (7) is invalid
L 11/05/2019 - 15:52:45: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 15:52:45: [SM] Call stack trace:
L 11/05/2019 - 15:52:45: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 15:52:45: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 15:52:46: Error log file session closed.
L 11/05/2019 - 15:52:57: SourceMod error session started
L 11/05/2019 - 15:52:57: Info (map "c4m4_milltown_b") (file "errors_20191105.log")
L 11/05/2019 - 15:52:57: [SM] Exception reported: Client 1 is not in game
L 11/05/2019 - 15:52:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 15:52:57: [SM] Call stack trace:
L 11/05/2019 - 15:52:57: [SM]   [0] GetClientTeam
L 11/05/2019 - 15:52:57: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 15:58:27: [SM] Exception reported: Client index 159 is invalid
L 11/05/2019 - 15:58:27: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 15:58:27: [SM] Call stack trace:
L 11/05/2019 - 15:58:27: [SM]   [0] IsClientInGame
L 11/05/2019 - 15:58:27: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 15:58:27: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 15:59:55: Error log file session closed.
L 11/05/2019 - 16:06:06: SourceMod error session started
L 11/05/2019 - 16:06:06: Info (map "c4m5_milltown_escape") (file "errors_20191105.log")
L 11/05/2019 - 16:06:06: [SM] Exception reported: Entity 6 (6) is invalid
L 11/05/2019 - 16:06:06: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 16:06:06: [SM] Call stack trace:
L 11/05/2019 - 16:06:06: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 16:06:06: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 16:09:36: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 16:09:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 16:09:36: [SM] Call stack trace:
L 11/05/2019 - 16:09:36: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 16:09:36: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 16:09:36: Error log file session closed.
L 11/05/2019 - 16:17:12: SourceMod error session started
L 11/05/2019 - 16:17:12: Info (map "c5m1_waterfront") (file "errors_20191105.log")
L 11/05/2019 - 16:17:12: [SM] Exception reported: Entity 6 (6) is invalid
L 11/05/2019 - 16:17:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 16:17:12: [SM] Call stack trace:
L 11/05/2019 - 16:17:12: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 16:17:12: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 16:17:13: Error log file session closed.
L 11/05/2019 - 16:17:19: SourceMod error session started
L 11/05/2019 - 16:17:19: Info (map "c5m2_park") (file "errors_20191105.log")
L 11/05/2019 - 16:17:19: [SM] Exception reported: Client 3 is not in game
L 11/05/2019 - 16:17:19: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 16:17:19: [SM] Call stack trace:
L 11/05/2019 - 16:17:19: [SM]   [0] GetClientTeam
L 11/05/2019 - 16:17:19: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 16:25:17: Error log file session closed.
L 11/05/2019 - 16:30:25: SourceMod error session started
L 11/05/2019 - 16:30:25: Info (map "c5m3_cemetery") (file "errors_20191105.log")
L 11/05/2019 - 16:30:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 16:30:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 16:30:25: [SM] Call stack trace:
L 11/05/2019 - 16:30:25: [SM]   [0] SetEntProp
L 11/05/2019 - 16:30:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 16:30:56: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 16:30:56: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 16:30:56: [SM] Call stack trace:
L 11/05/2019 - 16:30:56: [SM]   [0] SetEntProp
L 11/05/2019 - 16:30:56: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 16:38:08: [SM] Exception reported: Entity 7 (7) is invalid
L 11/05/2019 - 16:38:08: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 16:38:08: [SM] Call stack trace:
L 11/05/2019 - 16:38:08: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 16:38:08: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 16:40:20: [SM] Exception reported: Client 1 is not in game
L 11/05/2019 - 16:40:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 16:40:20: [SM] Call stack trace:
L 11/05/2019 - 16:40:20: [SM]   [0] GetClientTeam
L 11/05/2019 - 16:40:20: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 16:40:22: Error log file session closed.
L 11/05/2019 - 16:45:56: SourceMod error session started
L 11/05/2019 - 16:45:56: Info (map "c5m4_quarter") (file "errors_20191105.log")
L 11/05/2019 - 16:45:56: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 16:45:56: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 16:45:56: [SM] Call stack trace:
L 11/05/2019 - 16:45:56: [SM]   [0] SetEntProp
L 11/05/2019 - 16:45:56: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 16:52:59: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 11/05/2019 - 16:52:59: [SM] Blaming: l4d2_playstats.smx
L 11/05/2019 - 16:52:59: [SM] Call stack trace:
L 11/05/2019 - 16:52:59: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 11/05/2019 - 16:52:59: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 11/05/2019 - 16:52:59: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 11/05/2019 - 16:52:59: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 11/05/2019 - 16:53:19: Error log file session closed.
L 11/05/2019 - 16:54:58: SourceMod error session started
L 11/05/2019 - 16:54:58: Info (map "c5m5_bridge") (file "errors_20191105.log")
L 11/05/2019 - 16:54:58: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 16:54:58: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 16:54:58: [SM] Call stack trace:
L 11/05/2019 - 16:54:58: [SM]   [0] SetEntProp
L 11/05/2019 - 16:54:58: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 16:57:57: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 16:57:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 16:57:57: [SM] Call stack trace:
L 11/05/2019 - 16:57:57: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 16:57:57: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 16:57:58: Error log file session closed.
L 11/05/2019 - 17:00:56: SourceMod error session started
L 11/05/2019 - 17:00:56: Info (map "c2m1_highway") (file "errors_20191105.log")
L 11/05/2019 - 17:00:56: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:00:56: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:00:56: [SM] Call stack trace:
L 11/05/2019 - 17:00:56: [SM]   [0] SetEntProp
L 11/05/2019 - 17:00:56: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:05:09: [SM] Exception reported: Entity 8 (8) is invalid
L 11/05/2019 - 17:05:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 17:05:09: [SM] Call stack trace:
L 11/05/2019 - 17:05:09: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 17:05:09: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 17:09:11: Error log file session closed.
L 11/05/2019 - 17:12:22: SourceMod error session started
L 11/05/2019 - 17:12:22: Info (map "c2m2_fairgrounds") (file "errors_20191105.log")
L 11/05/2019 - 17:12:22: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:12:22: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:12:22: [SM] Call stack trace:
L 11/05/2019 - 17:12:22: [SM]   [0] SetEntProp
L 11/05/2019 - 17:12:22: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:12:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:12:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:12:24: [SM] Call stack trace:
L 11/05/2019 - 17:12:24: [SM]   [0] SetEntProp
L 11/05/2019 - 17:12:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:15:06: [SM] Exception reported: Client index 361 is invalid
L 11/05/2019 - 17:15:06: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 17:15:06: [SM] Call stack trace:
L 11/05/2019 - 17:15:06: [SM]   [0] IsClientInGame
L 11/05/2019 - 17:15:06: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 17:15:06: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 17:15:07: [SM] Exception reported: Client index 361 is invalid
L 11/05/2019 - 17:15:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 17:15:07: [SM] Call stack trace:
L 11/05/2019 - 17:15:07: [SM]   [0] IsClientInGame
L 11/05/2019 - 17:15:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 17:15:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 17:15:08: [SM] Exception reported: Client index 361 is invalid
L 11/05/2019 - 17:15:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 17:15:08: [SM] Call stack trace:
L 11/05/2019 - 17:15:08: [SM]   [0] IsClientInGame
L 11/05/2019 - 17:15:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 17:15:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 17:18:53: Error log file session closed.
L 11/05/2019 - 17:23:12: SourceMod error session started
L 11/05/2019 - 17:23:12: Info (map "c2m3_coaster") (file "errors_20191105.log")
L 11/05/2019 - 17:23:12: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:23:12: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:23:12: [SM] Call stack trace:
L 11/05/2019 - 17:23:12: [SM]   [0] SetEntProp
L 11/05/2019 - 17:23:12: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:23:17: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:23:17: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:23:17: [SM] Call stack trace:
L 11/05/2019 - 17:23:17: [SM]   [0] SetEntProp
L 11/05/2019 - 17:23:17: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:26:54: Error log file session closed.
L 11/05/2019 - 17:31:51: SourceMod error session started
L 11/05/2019 - 17:31:51: Info (map "c2m4_barns") (file "errors_20191105.log")
L 11/05/2019 - 17:31:51: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:31:51: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:31:51: [SM] Call stack trace:
L 11/05/2019 - 17:31:51: [SM]   [0] SetEntProp
L 11/05/2019 - 17:31:51: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:38:14: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:38:14: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:38:14: [SM] Call stack trace:
L 11/05/2019 - 17:38:14: [SM]   [0] SetEntProp
L 11/05/2019 - 17:38:14: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:38:55: [SM] Exception reported: Entity 2 (2) is invalid
L 11/05/2019 - 17:38:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 17:38:55: [SM] Call stack trace:
L 11/05/2019 - 17:38:55: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 17:38:55: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 17:38:55: [SM] Exception reported: Client 2 is not in game
L 11/05/2019 - 17:38:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 17:38:55: [SM] Call stack trace:
L 11/05/2019 - 17:38:55: [SM]   [0] GetClientTeam
L 11/05/2019 - 17:38:55: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 17:38:56: Error log file session closed.
L 11/05/2019 - 17:50:44: SourceMod error session started
L 11/05/2019 - 17:50:44: Info (map "c4m1_milltown_a") (file "errors_20191105.log")
L 11/05/2019 - 17:50:44: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 17:50:44: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 17:50:44: [SM] Call stack trace:
L 11/05/2019 - 17:50:44: [SM]   [0] SetEntProp
L 11/05/2019 - 17:50:44: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 17:51:15: [SM] Exception reported: Entity 5 (5) is invalid
L 11/05/2019 - 17:51:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 17:51:15: [SM] Call stack trace:
L 11/05/2019 - 17:51:15: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 17:51:15: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 17:51:16: Error log file session closed.
L 11/05/2019 - 17:55:02: SourceMod error session started
L 11/05/2019 - 17:55:02: Info (map "c4m2_sugarmill_a") (file "errors_20191105.log")
L 11/05/2019 - 17:55:02: [SM] Exception reported: Entity 5 (5) is invalid
L 11/05/2019 - 17:55:02: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 17:55:02: [SM] Call stack trace:
L 11/05/2019 - 17:55:02: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 17:55:02: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 18:00:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 18:00:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 18:00:11: [SM] Call stack trace:
L 11/05/2019 - 18:00:11: [SM]   [0] SetEntProp
L 11/05/2019 - 18:00:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 18:00:37: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 18:00:37: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:00:37: [SM] Call stack trace:
L 11/05/2019 - 18:00:37: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:00:37: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 18:00:37: [SM] Exception reported: Entity 6 (6) is invalid
L 11/05/2019 - 18:00:37: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:00:37: [SM] Call stack trace:
L 11/05/2019 - 18:00:37: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:00:37: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 18:00:37: Error log file session closed.
L 11/05/2019 - 18:06:16: SourceMod error session started
L 11/05/2019 - 18:06:16: Info (map "c4m3_sugarmill_b") (file "errors_20191105.log")
L 11/05/2019 - 18:06:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 18:06:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 18:06:16: [SM] Call stack trace:
L 11/05/2019 - 18:06:16: [SM]   [0] SetEntProp
L 11/05/2019 - 18:06:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 18:06:32: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 18:06:32: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 18:06:32: [SM] Call stack trace:
L 11/05/2019 - 18:06:32: [SM]   [0] SetEntProp
L 11/05/2019 - 18:06:32: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 18:07:35: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 18:07:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:07:35: [SM] Call stack trace:
L 11/05/2019 - 18:07:35: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:07:35: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 18:10:13: [sbpp_comms.smx] Lost connection to DB. Reconnect after delay.
L 11/05/2019 - 18:10:13: [sbpp_comms.smx] Query_VerifyBlock failed: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:10:16: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:10:59: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:13:45: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 18:13:45: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 18:13:45: [SM] Call stack trace:
L 11/05/2019 - 18:13:45: [SM]   [0] SetEntProp
L 11/05/2019 - 18:13:45: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 18:13:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 18:13:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 18:13:55: [SM] Call stack trace:
L 11/05/2019 - 18:13:55: [SM]   [0] SetEntProp
L 11/05/2019 - 18:13:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 18:14:19: Error log file session closed.
L 11/05/2019 - 18:15:02: SourceMod error session started
L 11/05/2019 - 18:15:02: Info (map "c4m4_milltown_b") (file "errors_20191105.log")
L 11/05/2019 - 18:15:02: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:08: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:12: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:15: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:18: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:21: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:48: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:51: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:15:55: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:19:22: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:19:26: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:22:24: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:22:27: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:23:06: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:23:09: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:24:01: [SM] Exception reported: Entity 7 (7) is invalid
L 11/05/2019 - 18:24:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:24:01: [SM] Call stack trace:
L 11/05/2019 - 18:24:01: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:24:01: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/05/2019 - 18:24:01: [SM] Exception reported: Entity 7 (7) is invalid
L 11/05/2019 - 18:24:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:24:01: [SM] Call stack trace:
L 11/05/2019 - 18:24:01: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:24:01: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 18:24:02: Error log file session closed.
L 11/05/2019 - 18:24:35: SourceMod error session started
L 11/05/2019 - 18:24:35: Info (map "c4m5_milltown_escape") (file "errors_20191105.log")
L 11/05/2019 - 18:24:35: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:24:42: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:24:45: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:24:48: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:24:51: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:25:18: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 18:25:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:25:18: [SM] Call stack trace:
L 11/05/2019 - 18:25:18: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:25:18: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 18:25:20: Error log file session closed.
L 11/05/2019 - 18:25:52: SourceMod error session started
L 11/05/2019 - 18:25:52: Info (map "c1m1_hotel") (file "errors_20191105.log")
L 11/05/2019 - 18:25:52: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:25:55: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:05: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:08: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:11: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:14: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:17: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:23: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:38: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:41: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:26:45: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:27:09: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:27:28: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:27:49: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:27:52: [sbpp_sleuth.smx] SourceSleuth: Database query error: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 18:28:08: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:08: [SM] Call stack trace:
L 11/05/2019 - 18:28:08: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:08: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:08: [SM] Call stack trace:
L 11/05/2019 - 18:28:08: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:08: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:08: [SM] Call stack trace:
L 11/05/2019 - 18:28:08: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:08: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:08: [SM] Call stack trace:
L 11/05/2019 - 18:28:08: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:08: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:08: [SM] Call stack trace:
L 11/05/2019 - 18:28:08: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:08: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:08: [SM] Call stack trace:
L 11/05/2019 - 18:28:08: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:09: [SM] Exception reported: Client index 177 is invalid
L 11/05/2019 - 18:28:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/05/2019 - 18:28:09: [SM] Call stack trace:
L 11/05/2019 - 18:28:09: [SM]   [0] IsClientInGame
L 11/05/2019 - 18:28:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/05/2019 - 18:28:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/05/2019 - 18:28:29: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/05/2019 - 18:28:29: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/05/2019 - 18:28:29: [SM] Call stack trace:
L 11/05/2019 - 18:28:29: [SM]   [0] SetEntProp
L 11/05/2019 - 18:28:29: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/05/2019 - 18:28:32: [SM] Exception reported: Entity 1 (1) is invalid
L 11/05/2019 - 18:28:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:28:32: [SM] Call stack trace:
L 11/05/2019 - 18:28:32: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:28:32: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 18:28:32: [SM] Exception reported: Entity 6 (6) is invalid
L 11/05/2019 - 18:28:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/05/2019 - 18:28:32: [SM] Call stack trace:
L 11/05/2019 - 18:28:32: [SM]   [0] GetEntDataEnt2
L 11/05/2019 - 18:28:32: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/05/2019 - 18:28:34: Error log file session closed.
L 11/05/2019 - 23:50:37: SourceMod error session started
L 11/05/2019 - 23:50:37: Info (map "c2m1_highway") (file "errors_20191105.log")
L 11/05/2019 - 23:50:37: [sbpp_sleuth.smx] SourceSleuth: Database connection error: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 23:50:37: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 23:50:37: [SM] Exception reported: Failed to connect to SourceBans DB, [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/05/2019 - 23:50:37: [SM] Blaming: sbpp_checker.smx
L 11/05/2019 - 23:50:37: [SM] Call stack trace:
L 11/05/2019 - 23:50:37: [SM]   [0] SetFailState
L 11/05/2019 - 23:50:37: [SM]   [1] Line 75, .\sbpp_checker.sp::OnDatabaseConnected
L 11/05/2019 - 23:52:01: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/05/2019 - 23:52:01: [SM] Blaming: sbpp_sleuth.smx
L 11/05/2019 - 23:52:01: [SM] Call stack trace:
L 11/05/2019 - 23:52:01: [SM]   [0] SQL_TQuery
L 11/05/2019 - 23:52:01: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/05/2019 - 23:52:04: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
