L 11/06/2019 - 00:22:53: SourceMod error session started
L 11/06/2019 - 00:22:53: Info (map "c12m1_hilltop") (file "errors_20191106.log")
L 11/06/2019 - 00:22:53: Error log file session closed.
L 11/06/2019 - 00:22:56: SourceMod error session started
L 11/06/2019 - 00:22:56: Info (map "c12m1_hilltop") (file "errors_20191106.log")
L 11/06/2019 - 00:22:56: [SM] Exception reported: Failed to connect to SourceBans DB, [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:22:56: [SM] Blaming: sbpp_checker.smx
L 11/06/2019 - 00:22:56: [SM] Call stack trace:
L 11/06/2019 - 00:22:56: [SM]   [0] SetFailState
L 11/06/2019 - 00:22:56: [SM]   [1] Line 75, .\sbpp_checker.sp::OnDatabaseConnected
L 11/06/2019 - 00:23:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:00: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:00: [SM] Call stack trace:
L 11/06/2019 - 00:23:00: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:02: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:23:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:05: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:05: [SM] Call stack trace:
L 11/06/2019 - 00:23:05: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:05: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:05: [SM] Call stack trace:
L 11/06/2019 - 00:23:05: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:08: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:23:12: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:12: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:12: [SM] Call stack trace:
L 11/06/2019 - 00:23:12: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:12: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:15: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:23:15: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:15: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:15: [SM] Call stack trace:
L 11/06/2019 - 00:23:15: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:15: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:18: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:18: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:18: [SM] Call stack trace:
L 11/06/2019 - 00:23:18: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:18: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:18: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:23:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:21: [SM] Call stack trace:
L 11/06/2019 - 00:23:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:24: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:23:31: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:23:31: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:23:31: [SM] Call stack trace:
L 11/06/2019 - 00:23:31: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:23:31: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:23:34: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:25:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:25:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:25:21: [SM] Call stack trace:
L 11/06/2019 - 00:25:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:25:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:25:24: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:26:12: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:26:12: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:26:12: [SM] Call stack trace:
L 11/06/2019 - 00:26:12: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:26:12: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:26:15: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:29:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:29:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:29:21: [SM] Call stack trace:
L 11/06/2019 - 00:29:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:29:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:29:24: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/06/2019 - 00:32:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:32:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:32:21: [SM] Call stack trace:
L 11/06/2019 - 00:32:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:32:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:37:10: [SM] Exception reported: Entity 7 (7) is invalid
L 11/06/2019 - 00:37:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 00:37:10: [SM] Call stack trace:
L 11/06/2019 - 00:37:10: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 00:37:10: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 00:37:12: Error log file session closed.
L 11/06/2019 - 00:37:19: SourceMod error session started
L 11/06/2019 - 00:37:19: Info (map "c12m2_traintunnel") (file "errors_20191106.log")
L 11/06/2019 - 00:37:19: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:37:19: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:37:19: [SM] Call stack trace:
L 11/06/2019 - 00:37:19: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:37:19: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:37:19: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:37:19: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:37:19: [SM] Call stack trace:
L 11/06/2019 - 00:37:19: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:37:19: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:37:19: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:37:19: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:37:19: [SM] Call stack trace:
L 11/06/2019 - 00:37:19: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:37:19: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:37:20: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:37:20: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:37:20: [SM] Call stack trace:
L 11/06/2019 - 00:37:20: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:37:20: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:37:24: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:37:24: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:37:24: [SM] Call stack trace:
L 11/06/2019 - 00:37:24: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:37:24: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:37:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:37:26: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:37:26: [SM] Call stack trace:
L 11/06/2019 - 00:37:26: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:37:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:39:25: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:39:25: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:39:25: [SM] Call stack trace:
L 11/06/2019 - 00:39:25: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:39:25: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:40:08: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:40:08: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:40:08: [SM] Call stack trace:
L 11/06/2019 - 00:40:08: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:40:08: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:42:14: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:42:14: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:42:14: [SM] Call stack trace:
L 11/06/2019 - 00:42:14: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:42:14: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:44:38: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:44:38: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:44:38: [SM] Call stack trace:
L 11/06/2019 - 00:44:38: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:44:38: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:46:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:46:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:46:04: [SM] Call stack trace:
L 11/06/2019 - 00:46:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:46:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:46:15: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:46:15: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:46:15: [SM] Call stack trace:
L 11/06/2019 - 00:46:15: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:46:15: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:47:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:47:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:47:32: [SM] Call stack trace:
L 11/06/2019 - 00:47:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:47:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:48:20: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:48:20: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:48:20: [SM] Call stack trace:
L 11/06/2019 - 00:48:20: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:48:20: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:51:03: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:51:03: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:51:03: [SM] Call stack trace:
L 11/06/2019 - 00:51:03: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:51:03: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:00: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:00: [SM] Call stack trace:
L 11/06/2019 - 00:53:00: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:37: Error log file session closed.
L 11/06/2019 - 00:53:42: SourceMod error session started
L 11/06/2019 - 00:53:42: Info (map "c12m3_bridge") (file "errors_20191106.log")
L 11/06/2019 - 00:53:42: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:42: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:42: [SM] Call stack trace:
L 11/06/2019 - 00:53:42: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:42: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:43: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:43: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:43: [SM] Call stack trace:
L 11/06/2019 - 00:53:43: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:43: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:43: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:43: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:43: [SM] Call stack trace:
L 11/06/2019 - 00:53:43: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:43: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:44: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:44: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:44: [SM] Call stack trace:
L 11/06/2019 - 00:53:44: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:44: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:46: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:46: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:46: [SM] Call stack trace:
L 11/06/2019 - 00:53:46: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:46: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:47: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:47: [SM] Call stack trace:
L 11/06/2019 - 00:53:47: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:47: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:47: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:47: [SM] Call stack trace:
L 11/06/2019 - 00:53:47: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:47: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:53:50: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:53:50: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:53:50: [SM] Call stack trace:
L 11/06/2019 - 00:53:50: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:53:50: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:55:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:55:22: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:55:22: [SM] Call stack trace:
L 11/06/2019 - 00:55:22: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:55:22: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:55:37: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:55:37: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:55:37: [SM] Call stack trace:
L 11/06/2019 - 00:55:37: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:55:37: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:56:18: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 00:56:18: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 00:56:18: [SM] Call stack trace:
L 11/06/2019 - 00:56:18: [SM]   [0] SetEntProp
L 11/06/2019 - 00:56:18: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 00:58:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:58:29: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:58:29: [SM] Call stack trace:
L 11/06/2019 - 00:58:29: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:58:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:58:55: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 00:58:55: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 00:58:55: [SM] Call stack trace:
L 11/06/2019 - 00:58:55: [SM]   [0] SQL_TQuery
L 11/06/2019 - 00:58:55: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 00:59:51: [SM] Exception reported: Client index 363 is invalid
L 11/06/2019 - 00:59:51: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 00:59:51: [SM] Call stack trace:
L 11/06/2019 - 00:59:51: [SM]   [0] IsClientInGame
L 11/06/2019 - 00:59:51: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 00:59:51: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 01:01:57: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:01:57: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:01:57: [SM] Call stack trace:
L 11/06/2019 - 01:01:57: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:01:57: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:20: Error log file session closed.
L 11/06/2019 - 01:06:27: SourceMod error session started
L 11/06/2019 - 01:06:27: Info (map "c12m4_barn") (file "errors_20191106.log")
L 11/06/2019 - 01:06:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:27: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:27: [SM] Call stack trace:
L 11/06/2019 - 01:06:27: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:27: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:27: [SM] Call stack trace:
L 11/06/2019 - 01:06:27: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:28: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:28: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:28: [SM] Call stack trace:
L 11/06/2019 - 01:06:28: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:28: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:28: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:28: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:28: [SM] Call stack trace:
L 11/06/2019 - 01:06:28: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:28: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:32: [SM] Call stack trace:
L 11/06/2019 - 01:06:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:32: [SM] Call stack trace:
L 11/06/2019 - 01:06:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:32: [SM] Call stack trace:
L 11/06/2019 - 01:06:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:33: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:33: [SM] Call stack trace:
L 11/06/2019 - 01:06:33: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:33: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:06:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:06:35: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:06:35: [SM] Call stack trace:
L 11/06/2019 - 01:06:35: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:06:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:08:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:08:35: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:08:35: [SM] Call stack trace:
L 11/06/2019 - 01:08:35: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:08:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:09:01: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:09:01: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:09:01: [SM] Call stack trace:
L 11/06/2019 - 01:09:01: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:09:01: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:10:58: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 01:10:58: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 01:10:58: [SM] Call stack trace:
L 11/06/2019 - 01:10:58: [SM]   [0] SetEntProp
L 11/06/2019 - 01:10:58: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 01:12:41: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:12:41: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:12:41: [SM] Call stack trace:
L 11/06/2019 - 01:12:41: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:12:41: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:15:31: [SM] Exception reported: Client index 441 is invalid
L 11/06/2019 - 01:15:31: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 01:15:31: [SM] Call stack trace:
L 11/06/2019 - 01:15:31: [SM]   [0] IsClientInGame
L 11/06/2019 - 01:15:31: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 01:15:31: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 01:16:07: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:16:07: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:16:07: [SM] Call stack trace:
L 11/06/2019 - 01:16:07: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:16:07: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:17:57: [SM] Exception reported: Entity 2 (2) is invalid
L 11/06/2019 - 01:17:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 01:17:57: [SM] Call stack trace:
L 11/06/2019 - 01:17:57: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 01:17:57: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 01:17:59: Error log file session closed.
L 11/06/2019 - 01:18:06: SourceMod error session started
L 11/06/2019 - 01:18:06: Info (map "c12m5_cornfield") (file "errors_20191106.log")
L 11/06/2019 - 01:18:06: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:18:06: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:18:06: [SM] Call stack trace:
L 11/06/2019 - 01:18:06: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:18:06: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:18:06: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:18:06: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:18:06: [SM] Call stack trace:
L 11/06/2019 - 01:18:06: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:18:06: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:18:07: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:18:07: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:18:07: [SM] Call stack trace:
L 11/06/2019 - 01:18:07: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:18:07: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:18:10: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:18:10: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:18:10: [SM] Call stack trace:
L 11/06/2019 - 01:18:10: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:18:10: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:18:11: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:18:11: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:18:11: [SM] Call stack trace:
L 11/06/2019 - 01:18:11: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:18:11: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:18:14: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:18:14: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:18:14: [SM] Call stack trace:
L 11/06/2019 - 01:18:14: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:18:14: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:19:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:19:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:19:04: [SM] Call stack trace:
L 11/06/2019 - 01:19:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:19:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:19:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:19:33: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:19:33: [SM] Call stack trace:
L 11/06/2019 - 01:19:33: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:19:33: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:20:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:20:27: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:20:27: [SM] Call stack trace:
L 11/06/2019 - 01:20:27: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:20:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:11: [SM] Exception reported: Entity 3 (3) is invalid
L 11/06/2019 - 01:24:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 01:24:11: [SM] Call stack trace:
L 11/06/2019 - 01:24:11: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 01:24:11: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 01:24:11: [SM] Exception reported: Entity 2 (2) is invalid
L 11/06/2019 - 01:24:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 01:24:11: [SM] Call stack trace:
L 11/06/2019 - 01:24:11: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 01:24:11: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 01:24:13: Error log file session closed.
L 11/06/2019 - 01:24:20: SourceMod error session started
L 11/06/2019 - 01:24:20: Info (map "c11m1_greenhouse") (file "errors_20191106.log")
L 11/06/2019 - 01:24:20: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:20: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:20: [SM] Call stack trace:
L 11/06/2019 - 01:24:20: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:20: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:21: [SM] Call stack trace:
L 11/06/2019 - 01:24:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:24: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:24: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:24: [SM] Call stack trace:
L 11/06/2019 - 01:24:24: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:24: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:25: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:25: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:25: [SM] Call stack trace:
L 11/06/2019 - 01:24:25: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:25: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:25: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:25: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:25: [SM] Call stack trace:
L 11/06/2019 - 01:24:25: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:25: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:26: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:26: [SM] Call stack trace:
L 11/06/2019 - 01:24:26: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:29: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:29: [SM] Call stack trace:
L 11/06/2019 - 01:24:29: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:34: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:34: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:34: [SM] Call stack trace:
L 11/06/2019 - 01:24:34: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:34: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:24:57: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:24:57: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:24:57: [SM] Call stack trace:
L 11/06/2019 - 01:24:57: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:24:57: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:27:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 01:27:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 01:27:57: [SM] Call stack trace:
L 11/06/2019 - 01:27:57: [SM]   [0] SetEntProp
L 11/06/2019 - 01:27:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 01:30:02: [SM] Exception reported: Client index 160 is invalid
L 11/06/2019 - 01:30:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 01:30:02: [SM] Call stack trace:
L 11/06/2019 - 01:30:02: [SM]   [0] IsClientInGame
L 11/06/2019 - 01:30:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 01:30:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 01:30:12: [SM] Exception reported: Client index 160 is invalid
L 11/06/2019 - 01:30:12: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 01:30:12: [SM] Call stack trace:
L 11/06/2019 - 01:30:12: [SM]   [0] IsClientInGame
L 11/06/2019 - 01:30:12: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 01:30:12: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 01:31:24: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:31:24: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:31:24: [SM] Call stack trace:
L 11/06/2019 - 01:31:24: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:31:24: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:31:36: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:31:36: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:31:36: [SM] Call stack trace:
L 11/06/2019 - 01:31:36: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:31:36: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:31:38: [SM] Exception reported: Client 5 is not in game
L 11/06/2019 - 01:31:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 01:31:38: [SM] Call stack trace:
L 11/06/2019 - 01:31:38: [SM]   [0] GetClientTeam
L 11/06/2019 - 01:31:38: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 01:31:55: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:31:55: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:31:55: [SM] Call stack trace:
L 11/06/2019 - 01:31:55: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:31:55: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:24: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:24: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:24: [SM] Call stack trace:
L 11/06/2019 - 01:32:24: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:24: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:33: Error log file session closed.
L 11/06/2019 - 01:32:40: SourceMod error session started
L 11/06/2019 - 01:32:40: Info (map "c11m2_offices") (file "errors_20191106.log")
L 11/06/2019 - 01:32:40: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:40: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:40: [SM] Call stack trace:
L 11/06/2019 - 01:32:40: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:40: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:40: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:40: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:40: [SM] Call stack trace:
L 11/06/2019 - 01:32:40: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:40: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:40: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:40: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:40: [SM] Call stack trace:
L 11/06/2019 - 01:32:40: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:40: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:41: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:41: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:41: [SM] Call stack trace:
L 11/06/2019 - 01:32:41: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:41: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:43: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:43: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:43: [SM] Call stack trace:
L 11/06/2019 - 01:32:43: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:43: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:43: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:43: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:43: [SM] Call stack trace:
L 11/06/2019 - 01:32:43: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:43: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:43: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:43: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:43: [SM] Call stack trace:
L 11/06/2019 - 01:32:43: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:43: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:44: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:44: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:44: [SM] Call stack trace:
L 11/06/2019 - 01:32:44: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:44: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:32:45: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:32:45: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:32:45: [SM] Call stack trace:
L 11/06/2019 - 01:32:45: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:32:45: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:43:21: [SM] Exception reported: Client index 267 is invalid
L 11/06/2019 - 01:43:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 01:43:21: [SM] Call stack trace:
L 11/06/2019 - 01:43:21: [SM]   [0] IsClientInGame
L 11/06/2019 - 01:43:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 01:43:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 01:48:13: [SM] Exception reported: Entity 3 (3) is invalid
L 11/06/2019 - 01:48:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 01:48:13: [SM] Call stack trace:
L 11/06/2019 - 01:48:13: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 01:48:13: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 01:48:15: Error log file session closed.
L 11/06/2019 - 01:48:22: SourceMod error session started
L 11/06/2019 - 01:48:22: Info (map "c11m3_garage") (file "errors_20191106.log")
L 11/06/2019 - 01:48:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:48:22: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:48:22: [SM] Call stack trace:
L 11/06/2019 - 01:48:22: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:48:22: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:48:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:48:22: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:48:22: [SM] Call stack trace:
L 11/06/2019 - 01:48:22: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:48:22: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:48:23: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:48:23: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:48:23: [SM] Call stack trace:
L 11/06/2019 - 01:48:23: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:48:23: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:48:23: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:48:23: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:48:23: [SM] Call stack trace:
L 11/06/2019 - 01:48:23: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:48:23: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:48:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:48:26: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:48:26: [SM] Call stack trace:
L 11/06/2019 - 01:48:26: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:48:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:48:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:48:26: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:48:26: [SM] Call stack trace:
L 11/06/2019 - 01:48:26: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:48:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:48:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:48:27: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:48:27: [SM] Call stack trace:
L 11/06/2019 - 01:48:27: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:48:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:49:37: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:49:37: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:49:37: [SM] Call stack trace:
L 11/06/2019 - 01:49:37: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:49:37: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:50:55: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:50:55: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:50:55: [SM] Call stack trace:
L 11/06/2019 - 01:50:55: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:50:55: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:51:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:51:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:51:32: [SM] Call stack trace:
L 11/06/2019 - 01:51:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:51:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:52:03: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:52:03: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:52:03: [SM] Call stack trace:
L 11/06/2019 - 01:52:03: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:52:03: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:52:36: [SM] Exception reported: Client index 622 is invalid
L 11/06/2019 - 01:52:36: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 01:52:36: [SM] Call stack trace:
L 11/06/2019 - 01:52:36: [SM]   [0] IsClientInGame
L 11/06/2019 - 01:52:36: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 01:52:36: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 01:52:45: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:52:45: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:52:45: [SM] Call stack trace:
L 11/06/2019 - 01:52:45: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:52:45: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:53:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:53:00: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:53:00: [SM] Call stack trace:
L 11/06/2019 - 01:53:00: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:53:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:53:25: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:53:25: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:53:25: [SM] Call stack trace:
L 11/06/2019 - 01:53:25: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:53:25: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:55:06: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 01:55:06: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 01:55:06: [SM] Call stack trace:
L 11/06/2019 - 01:55:06: [SM]   [0] SetEntProp
L 11/06/2019 - 01:55:06: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 01:58:35: [SM] Exception reported: Entity 2 (2) is invalid
L 11/06/2019 - 01:58:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 01:58:35: [SM] Call stack trace:
L 11/06/2019 - 01:58:35: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 01:58:35: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 01:58:35: [SM] Exception reported: Entity 4 (4) is invalid
L 11/06/2019 - 01:58:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 01:58:35: [SM] Call stack trace:
L 11/06/2019 - 01:58:35: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 01:58:35: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 01:58:37: Error log file session closed.
L 11/06/2019 - 01:58:44: SourceMod error session started
L 11/06/2019 - 01:58:44: Info (map "c8m1_apartment") (file "errors_20191106.log")
L 11/06/2019 - 01:58:44: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:58:44: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:58:44: [SM] Call stack trace:
L 11/06/2019 - 01:58:44: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:58:44: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:58:45: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:58:45: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:58:45: [SM] Call stack trace:
L 11/06/2019 - 01:58:45: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:58:45: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:58:45: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:58:45: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:58:45: [SM] Call stack trace:
L 11/06/2019 - 01:58:45: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:58:45: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:58:48: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:58:48: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:58:48: [SM] Call stack trace:
L 11/06/2019 - 01:58:48: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:58:48: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:58:49: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:58:49: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:58:49: [SM] Call stack trace:
L 11/06/2019 - 01:58:49: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:58:49: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:58:49: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:58:49: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:58:49: [SM] Call stack trace:
L 11/06/2019 - 01:58:49: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:58:49: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:59:01: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:59:01: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:59:01: [SM] Call stack trace:
L 11/06/2019 - 01:59:01: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:59:01: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 01:59:27: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 01:59:27: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 01:59:27: [SM] Call stack trace:
L 11/06/2019 - 01:59:27: [SM]   [0] SQL_TQuery
L 11/06/2019 - 01:59:27: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:02:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 02:02:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 02:02:01: [SM] Call stack trace:
L 11/06/2019 - 02:02:01: [SM]   [0] SetEntProp
L 11/06/2019 - 02:02:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 02:02:06: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 02:02:06: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 02:02:06: [SM] Call stack trace:
L 11/06/2019 - 02:02:06: [SM]   [0] SetEntProp
L 11/06/2019 - 02:02:06: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 02:02:31: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:02:31: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:02:31: [SM] Call stack trace:
L 11/06/2019 - 02:02:31: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:02:31: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:04:46: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 02:04:46: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 02:04:46: [SM] Call stack trace:
L 11/06/2019 - 02:04:46: [SM]   [0] SetEntProp
L 11/06/2019 - 02:04:46: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 02:05:11: Error log file session closed.
L 11/06/2019 - 02:05:19: SourceMod error session started
L 11/06/2019 - 02:05:19: Info (map "c8m2_subway") (file "errors_20191106.log")
L 11/06/2019 - 02:05:19: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:05:19: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:05:19: [SM] Call stack trace:
L 11/06/2019 - 02:05:19: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:05:19: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:05:19: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:05:19: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:05:19: [SM] Call stack trace:
L 11/06/2019 - 02:05:19: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:05:19: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:05:20: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:05:20: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:05:20: [SM] Call stack trace:
L 11/06/2019 - 02:05:20: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:05:20: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:05:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:05:22: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:05:22: [SM] Call stack trace:
L 11/06/2019 - 02:05:22: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:05:22: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:05:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:05:22: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:05:22: [SM] Call stack trace:
L 11/06/2019 - 02:05:22: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:05:22: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:05:34: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:05:34: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:05:34: [SM] Call stack trace:
L 11/06/2019 - 02:05:34: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:05:34: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:06:01: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:06:01: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:06:01: [SM] Call stack trace:
L 11/06/2019 - 02:06:01: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:06:01: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:06:06: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:06:06: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:06:06: [SM] Call stack trace:
L 11/06/2019 - 02:06:06: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:06:06: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:08:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:08:26: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:08:26: [SM] Call stack trace:
L 11/06/2019 - 02:08:26: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:08:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:09:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:09:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:09:04: [SM] Call stack trace:
L 11/06/2019 - 02:09:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:09:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:09:12: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:09:12: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:09:12: [SM] Call stack trace:
L 11/06/2019 - 02:09:12: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:09:12: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:09:53: [SM] Exception reported: Client 6 is not in game
L 11/06/2019 - 02:09:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 02:09:53: [SM] Call stack trace:
L 11/06/2019 - 02:09:53: [SM]   [0] GetClientTeam
L 11/06/2019 - 02:09:53: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 02:10:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:10:22: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:10:22: [SM] Call stack trace:
L 11/06/2019 - 02:10:22: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:10:22: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:10:57: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:10:57: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:10:57: [SM] Call stack trace:
L 11/06/2019 - 02:10:57: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:10:57: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:12:53: [SM] Exception reported: Client 2 is not in game
L 11/06/2019 - 02:12:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 02:12:53: [SM] Call stack trace:
L 11/06/2019 - 02:12:53: [SM]   [0] GetClientTeam
L 11/06/2019 - 02:12:53: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 02:13:51: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:13:51: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:13:51: [SM] Call stack trace:
L 11/06/2019 - 02:13:51: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:13:51: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:14:06: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:14:06: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:14:06: [SM] Call stack trace:
L 11/06/2019 - 02:14:06: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:14:06: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:16:13: [SM] Exception reported: Entity 6 (6) is invalid
L 11/06/2019 - 02:16:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 02:16:13: [SM] Call stack trace:
L 11/06/2019 - 02:16:13: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 02:16:13: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 02:16:20: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:16:20: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:16:20: [SM] Call stack trace:
L 11/06/2019 - 02:16:20: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:16:20: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:19:29: Error log file session closed.
L 11/06/2019 - 02:19:37: SourceMod error session started
L 11/06/2019 - 02:19:37: Info (map "c8m3_sewers") (file "errors_20191106.log")
L 11/06/2019 - 02:19:37: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:19:37: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:19:37: [SM] Call stack trace:
L 11/06/2019 - 02:19:37: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:19:37: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:19:39: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:19:39: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:19:39: [SM] Call stack trace:
L 11/06/2019 - 02:19:39: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:19:39: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:19:39: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:19:39: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:19:39: [SM] Call stack trace:
L 11/06/2019 - 02:19:39: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:19:39: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:19:40: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:19:40: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:19:40: [SM] Call stack trace:
L 11/06/2019 - 02:19:40: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:19:40: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:19:41: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:19:41: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:19:41: [SM] Call stack trace:
L 11/06/2019 - 02:19:41: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:19:41: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:19:44: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:19:44: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:19:44: [SM] Call stack trace:
L 11/06/2019 - 02:19:44: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:19:44: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:19:48: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:19:48: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:19:48: [SM] Call stack trace:
L 11/06/2019 - 02:19:48: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:19:48: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:20:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:20:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:20:04: [SM] Call stack trace:
L 11/06/2019 - 02:20:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:20:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:22:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:22:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:22:32: [SM] Call stack trace:
L 11/06/2019 - 02:22:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:22:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:26:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:26:05: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:26:05: [SM] Call stack trace:
L 11/06/2019 - 02:26:05: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:26:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:26:48: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:26:48: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:26:48: [SM] Call stack trace:
L 11/06/2019 - 02:26:48: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:26:48: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:27:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:27:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:27:21: [SM] Call stack trace:
L 11/06/2019 - 02:27:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:27:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:29:47: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 02:29:47: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 02:29:47: [SM] Call stack trace:
L 11/06/2019 - 02:29:47: [SM]   [0] SetEntProp
L 11/06/2019 - 02:29:47: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 02:30:54: Error log file session closed.
L 11/06/2019 - 02:31:04: SourceMod error session started
L 11/06/2019 - 02:31:04: Info (map "c8m4_interior") (file "errors_20191106.log")
L 11/06/2019 - 02:31:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:31:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:31:04: [SM] Call stack trace:
L 11/06/2019 - 02:31:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:31:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:31:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:31:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:31:04: [SM] Call stack trace:
L 11/06/2019 - 02:31:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:31:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:31:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:31:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:31:04: [SM] Call stack trace:
L 11/06/2019 - 02:31:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:31:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:31:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:31:05: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:31:05: [SM] Call stack trace:
L 11/06/2019 - 02:31:05: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:31:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:31:06: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:31:06: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:31:06: [SM] Call stack trace:
L 11/06/2019 - 02:31:06: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:31:06: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:31:13: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:31:13: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:31:13: [SM] Call stack trace:
L 11/06/2019 - 02:31:13: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:31:13: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:31:20: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:31:20: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:31:20: [SM] Call stack trace:
L 11/06/2019 - 02:31:20: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:31:20: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:34:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:34:22: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:34:22: [SM] Call stack trace:
L 11/06/2019 - 02:34:22: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:34:22: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:35:30: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:35:30: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:35:30: [SM] Call stack trace:
L 11/06/2019 - 02:35:30: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:35:30: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:35:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 02:35:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 02:35:55: [SM] Call stack trace:
L 11/06/2019 - 02:35:55: [SM]   [0] SetEntProp
L 11/06/2019 - 02:35:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 02:36:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:36:33: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:36:33: [SM] Call stack trace:
L 11/06/2019 - 02:36:33: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:36:33: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:38:46: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:38:46: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:38:46: [SM] Call stack trace:
L 11/06/2019 - 02:38:46: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:38:46: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:40:50: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:40:50: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:40:50: [SM] Call stack trace:
L 11/06/2019 - 02:40:50: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:40:50: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:41:39: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:41:39: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:41:39: [SM] Call stack trace:
L 11/06/2019 - 02:41:39: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:41:39: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:42:26: [SM] Exception reported: Entity 4 (4) is invalid
L 11/06/2019 - 02:42:26: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 02:42:26: [SM] Call stack trace:
L 11/06/2019 - 02:42:26: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 02:42:26: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 02:42:26: [SM] Exception reported: Client 4 is not in game
L 11/06/2019 - 02:42:26: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 02:42:26: [SM] Call stack trace:
L 11/06/2019 - 02:42:26: [SM]   [0] GetClientTeam
L 11/06/2019 - 02:42:26: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 02:42:27: Error log file session closed.
L 11/06/2019 - 02:42:34: SourceMod error session started
L 11/06/2019 - 02:42:34: Info (map "c8m5_rooftop") (file "errors_20191106.log")
L 11/06/2019 - 02:42:34: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:42:34: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:42:34: [SM] Call stack trace:
L 11/06/2019 - 02:42:34: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:42:34: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:42:34: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:42:34: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:42:34: [SM] Call stack trace:
L 11/06/2019 - 02:42:34: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:42:34: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:42:37: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:42:37: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:42:37: [SM] Call stack trace:
L 11/06/2019 - 02:42:37: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:42:37: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:42:38: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:42:38: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:42:38: [SM] Call stack trace:
L 11/06/2019 - 02:42:38: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:42:38: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:42:53: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:42:53: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:42:53: [SM] Call stack trace:
L 11/06/2019 - 02:42:53: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:42:53: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:43:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:43:26: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:43:26: [SM] Call stack trace:
L 11/06/2019 - 02:43:26: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:43:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:43:56: [SM] Exception reported: Client index 420 is invalid
L 11/06/2019 - 02:43:56: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 02:43:56: [SM] Call stack trace:
L 11/06/2019 - 02:43:56: [SM]   [0] IsClientInGame
L 11/06/2019 - 02:43:56: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 02:43:56: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 02:43:56: [SM] Exception reported: Client index 420 is invalid
L 11/06/2019 - 02:43:56: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 02:43:56: [SM] Call stack trace:
L 11/06/2019 - 02:43:56: [SM]   [0] IsClientInGame
L 11/06/2019 - 02:43:56: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 02:43:56: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 02:46:01: [SM] Exception reported: Client index 96 is invalid
L 11/06/2019 - 02:46:01: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 02:46:01: [SM] Call stack trace:
L 11/06/2019 - 02:46:01: [SM]   [0] IsClientInGame
L 11/06/2019 - 02:46:01: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 02:46:01: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 02:47:15: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 02:47:15: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 02:47:15: [SM] Call stack trace:
L 11/06/2019 - 02:47:15: [SM]   [0] SetEntProp
L 11/06/2019 - 02:47:15: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 02:48:00: Error log file session closed.
L 11/06/2019 - 02:48:15: SourceMod error session started
L 11/06/2019 - 02:48:15: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 02:48:15: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:48:15: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:48:15: [SM] Call stack trace:
L 11/06/2019 - 02:48:15: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:48:15: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:48:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:48:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:48:32: [SM] Call stack trace:
L 11/06/2019 - 02:48:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:48:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:48:46: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:48:46: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:48:46: [SM] Call stack trace:
L 11/06/2019 - 02:48:46: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:48:46: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:49:06: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:49:06: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:49:06: [SM] Call stack trace:
L 11/06/2019 - 02:49:06: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:49:06: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:49:10: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:49:10: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:49:10: [SM] Call stack trace:
L 11/06/2019 - 02:49:10: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:49:10: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:49:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:49:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:49:32: [SM] Call stack trace:
L 11/06/2019 - 02:49:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:49:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:50:19: [SM] Exception reported: Client index 281 is invalid
L 11/06/2019 - 02:50:19: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 02:50:19: [SM] Call stack trace:
L 11/06/2019 - 02:50:19: [SM]   [0] IsClientInGame
L 11/06/2019 - 02:50:19: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 02:50:19: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 02:50:21: [SM] Exception reported: Client index 281 is invalid
L 11/06/2019 - 02:50:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 02:50:21: [SM] Call stack trace:
L 11/06/2019 - 02:50:21: [SM]   [0] IsClientInGame
L 11/06/2019 - 02:50:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 02:50:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 02:53:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:53:29: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:53:29: [SM] Call stack trace:
L 11/06/2019 - 02:53:29: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:53:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:54:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 02:54:00: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 02:54:00: [SM] Call stack trace:
L 11/06/2019 - 02:54:00: [SM]   [0] SQL_TQuery
L 11/06/2019 - 02:54:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 02:56:02: [SM] Exception reported: Client index 251 is invalid
L 11/06/2019 - 02:56:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 02:56:02: [SM] Call stack trace:
L 11/06/2019 - 02:56:02: [SM]   [0] IsClientInGame
L 11/06/2019 - 02:56:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 02:56:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 03:00:19: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:00:19: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:00:19: [SM] Call stack trace:
L 11/06/2019 - 03:00:19: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:00:19: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:00:53: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:00:53: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:00:53: [SM] Call stack trace:
L 11/06/2019 - 03:00:53: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:00:53: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:01:23: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:01:23: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:01:23: [SM] Call stack trace:
L 11/06/2019 - 03:01:23: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:01:23: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:01:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:01:35: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:01:35: [SM] Call stack trace:
L 11/06/2019 - 03:01:35: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:01:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:02:06: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:02:06: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:02:06: [SM] Call stack trace:
L 11/06/2019 - 03:02:06: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:02:06: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:02:24: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:02:24: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:02:24: [SM] Call stack trace:
L 11/06/2019 - 03:02:24: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:02:24: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:02:51: Error log file session closed.
L 11/06/2019 - 03:02:59: SourceMod error session started
L 11/06/2019 - 03:02:59: Info (map "c2m2_fairgrounds") (file "errors_20191106.log")
L 11/06/2019 - 03:02:59: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:02:59: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:02:59: [SM] Call stack trace:
L 11/06/2019 - 03:02:59: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:02:59: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:03:02: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:03:02: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:03:02: [SM] Call stack trace:
L 11/06/2019 - 03:03:02: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:03:02: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:03:02: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:03:02: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:03:02: [SM] Call stack trace:
L 11/06/2019 - 03:03:02: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:03:02: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:03:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:03:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:03:04: [SM] Call stack trace:
L 11/06/2019 - 03:03:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:03:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:03:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:03:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:03:04: [SM] Call stack trace:
L 11/06/2019 - 03:03:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:03:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:03:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:03:04: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:03:04: [SM] Call stack trace:
L 11/06/2019 - 03:03:04: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:03:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:03:15: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:03:15: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:03:15: [SM] Call stack trace:
L 11/06/2019 - 03:03:15: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:03:15: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:04:39: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:04:39: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:04:39: [SM] Call stack trace:
L 11/06/2019 - 03:04:39: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:04:39: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:05:59: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:05:59: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:05:59: [SM] Call stack trace:
L 11/06/2019 - 03:05:59: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:05:59: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:06:52: [SM] Exception reported: Client index 181 is invalid
L 11/06/2019 - 03:06:52: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 03:06:52: [SM] Call stack trace:
L 11/06/2019 - 03:06:52: [SM]   [0] IsClientInGame
L 11/06/2019 - 03:06:52: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 03:06:52: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 03:06:53: [SM] Exception reported: Client index 181 is invalid
L 11/06/2019 - 03:06:53: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 03:06:53: [SM] Call stack trace:
L 11/06/2019 - 03:06:53: [SM]   [0] IsClientInGame
L 11/06/2019 - 03:06:53: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 03:06:53: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 03:07:01: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:07:01: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:07:01: [SM] Call stack trace:
L 11/06/2019 - 03:07:01: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:07:01: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:09:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:09:00: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:09:00: [SM] Call stack trace:
L 11/06/2019 - 03:09:00: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:09:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:09:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:09:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:09:21: [SM] Call stack trace:
L 11/06/2019 - 03:09:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:09:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:09:25: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:09:25: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:09:25: [SM] Call stack trace:
L 11/06/2019 - 03:09:25: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:09:25: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:10:01: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:10:01: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:10:01: [SM] Call stack trace:
L 11/06/2019 - 03:10:01: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:10:01: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:10:16: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:10:16: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:10:16: [SM] Call stack trace:
L 11/06/2019 - 03:10:16: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:10:16: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:11:56: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:11:56: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:11:56: [SM] Call stack trace:
L 11/06/2019 - 03:11:56: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:11:56: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:15:53: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:15:53: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:15:53: [SM] Call stack trace:
L 11/06/2019 - 03:15:53: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:15:53: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:16:07: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:16:07: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:16:07: [SM] Call stack trace:
L 11/06/2019 - 03:16:07: [SM]   [0] SetEntProp
L 11/06/2019 - 03:16:07: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:16:37: Error log file session closed.
L 11/06/2019 - 03:16:44: SourceMod error session started
L 11/06/2019 - 03:16:44: Info (map "c2m3_coaster") (file "errors_20191106.log")
L 11/06/2019 - 03:16:44: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:16:44: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:16:44: [SM] Call stack trace:
L 11/06/2019 - 03:16:44: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:16:44: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:16:44: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:16:44: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:16:44: [SM] Call stack trace:
L 11/06/2019 - 03:16:44: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:16:44: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:16:46: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:16:46: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:16:46: [SM] Call stack trace:
L 11/06/2019 - 03:16:46: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:16:46: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:16:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:16:47: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:16:47: [SM] Call stack trace:
L 11/06/2019 - 03:16:47: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:16:47: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:16:48: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:16:48: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:16:48: [SM] Call stack trace:
L 11/06/2019 - 03:16:48: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:16:48: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:16:49: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:16:49: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:16:49: [SM] Call stack trace:
L 11/06/2019 - 03:16:49: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:16:49: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:16:58: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:16:58: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:16:58: [SM] Call stack trace:
L 11/06/2019 - 03:16:58: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:16:58: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:17:13: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:17:13: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:17:13: [SM] Call stack trace:
L 11/06/2019 - 03:17:13: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:17:13: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:17:14: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:17:14: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:17:14: [SM] Call stack trace:
L 11/06/2019 - 03:17:14: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:17:14: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:18:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:18:00: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:18:00: [SM] Call stack trace:
L 11/06/2019 - 03:18:00: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:18:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:18:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:18:21: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:18:21: [SM] Call stack trace:
L 11/06/2019 - 03:18:21: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:18:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:27:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:27:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:27:24: [SM] Call stack trace:
L 11/06/2019 - 03:27:24: [SM]   [0] SetEntProp
L 11/06/2019 - 03:27:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:32:21: Error log file session closed.
L 11/06/2019 - 03:32:32: SourceMod error session started
L 11/06/2019 - 03:32:32: Info (map "c2m4_barns") (file "errors_20191106.log")
L 11/06/2019 - 03:32:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:32: [SM] Call stack trace:
L 11/06/2019 - 03:32:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:32:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:33: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:33: [SM] Call stack trace:
L 11/06/2019 - 03:32:33: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:33: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:32:34: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:34: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:34: [SM] Call stack trace:
L 11/06/2019 - 03:32:34: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:34: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:32:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:35: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:35: [SM] Call stack trace:
L 11/06/2019 - 03:32:35: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:32:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:35: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:35: [SM] Call stack trace:
L 11/06/2019 - 03:32:35: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:32:36: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:36: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:36: [SM] Call stack trace:
L 11/06/2019 - 03:32:36: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:36: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:32:45: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:45: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:45: [SM] Call stack trace:
L 11/06/2019 - 03:32:45: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:45: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:32:58: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:32:58: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:32:58: [SM] Call stack trace:
L 11/06/2019 - 03:32:58: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:32:58: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:33:23: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:33:23: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:33:23: [SM] Call stack trace:
L 11/06/2019 - 03:33:23: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:33:23: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:34:51: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:34:51: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:34:51: [SM] Call stack trace:
L 11/06/2019 - 03:34:51: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:34:51: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:36:23: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:36:23: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:36:23: [SM] Call stack trace:
L 11/06/2019 - 03:36:23: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:36:23: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:36:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:36:47: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:36:47: [SM] Call stack trace:
L 11/06/2019 - 03:36:47: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:36:47: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:39:46: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:39:46: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:39:46: [SM] Call stack trace:
L 11/06/2019 - 03:39:46: [SM]   [0] SetEntProp
L 11/06/2019 - 03:39:46: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:39:48: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:39:48: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:39:48: [SM] Call stack trace:
L 11/06/2019 - 03:39:48: [SM]   [0] SetEntProp
L 11/06/2019 - 03:39:48: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:39:58: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:39:58: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:39:58: [SM] Call stack trace:
L 11/06/2019 - 03:39:58: [SM]   [0] SetEntProp
L 11/06/2019 - 03:39:58: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:44:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:44:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:44:24: [SM] Call stack trace:
L 11/06/2019 - 03:44:24: [SM]   [0] SetEntProp
L 11/06/2019 - 03:44:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:45:55: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:45:55: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:45:55: [SM] Call stack trace:
L 11/06/2019 - 03:45:55: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:45:55: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:22: [SM] Exception reported: Client 5 is not in game
L 11/06/2019 - 03:47:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 03:47:22: [SM] Call stack trace:
L 11/06/2019 - 03:47:22: [SM]   [0] GetClientTeam
L 11/06/2019 - 03:47:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 03:47:23: Error log file session closed.
L 11/06/2019 - 03:47:29: SourceMod error session started
L 11/06/2019 - 03:47:29: Info (map "c2m5_concert") (file "errors_20191106.log")
L 11/06/2019 - 03:47:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:29: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:29: [SM] Call stack trace:
L 11/06/2019 - 03:47:29: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:32: [SM] Call stack trace:
L 11/06/2019 - 03:47:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:32: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:32: [SM] Call stack trace:
L 11/06/2019 - 03:47:32: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:33: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:33: [SM] Call stack trace:
L 11/06/2019 - 03:47:33: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:33: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:35: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:35: [SM] Call stack trace:
L 11/06/2019 - 03:47:35: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:40: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:40: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:40: [SM] Call stack trace:
L 11/06/2019 - 03:47:40: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:40: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:42: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:42: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:42: [SM] Call stack trace:
L 11/06/2019 - 03:47:42: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:42: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:47:51: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:47:51: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:47:51: [SM] Call stack trace:
L 11/06/2019 - 03:47:51: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:47:51: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:50:13: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:50:13: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:50:13: [SM] Call stack trace:
L 11/06/2019 - 03:50:13: [SM]   [0] SetEntProp
L 11/06/2019 - 03:50:13: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:50:44: [SM] Exception reported: Entity 5 (5) is invalid
L 11/06/2019 - 03:50:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 03:50:44: [SM] Call stack trace:
L 11/06/2019 - 03:50:44: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 03:50:44: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 03:51:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 03:51:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 03:51:55: [SM] Call stack trace:
L 11/06/2019 - 03:51:55: [SM]   [0] SetEntProp
L 11/06/2019 - 03:51:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 03:52:03: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:52:03: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:52:03: [SM] Call stack trace:
L 11/06/2019 - 03:52:03: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:52:03: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:56:52: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:56:52: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:56:52: [SM] Call stack trace:
L 11/06/2019 - 03:56:52: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:56:52: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:59:21: [SM] Exception reported: Entity 7 (7) is invalid
L 11/06/2019 - 03:59:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 03:59:21: [SM] Call stack trace:
L 11/06/2019 - 03:59:21: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 03:59:21: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 03:59:21: [SM] Exception reported: Entity 7 (7) is invalid
L 11/06/2019 - 03:59:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 03:59:21: [SM] Call stack trace:
L 11/06/2019 - 03:59:21: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 03:59:21: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 03:59:21: [SM] Exception reported: Entity 7 (7) is invalid
L 11/06/2019 - 03:59:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 03:59:21: [SM] Call stack trace:
L 11/06/2019 - 03:59:21: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 03:59:21: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 03:59:21: [SM] Exception reported: Entity 2 (2) is invalid
L 11/06/2019 - 03:59:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 03:59:21: [SM] Call stack trace:
L 11/06/2019 - 03:59:21: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 03:59:21: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 03:59:24: Error log file session closed.
L 11/06/2019 - 03:59:39: SourceMod error session started
L 11/06/2019 - 03:59:39: Info (map "c3m1_plankcountry") (file "errors_20191106.log")
L 11/06/2019 - 03:59:39: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:59:39: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:59:39: [SM] Call stack trace:
L 11/06/2019 - 03:59:39: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:59:39: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 03:59:43: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 03:59:43: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 03:59:43: [SM] Call stack trace:
L 11/06/2019 - 03:59:43: [SM]   [0] SQL_TQuery
L 11/06/2019 - 03:59:43: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 04:00:09: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/06/2019 - 04:00:09: [SM] Blaming: sbpp_sleuth.smx
L 11/06/2019 - 04:00:09: [SM] Call stack trace:
L 11/06/2019 - 04:00:09: [SM]   [0] SQL_TQuery
L 11/06/2019 - 04:00:09: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/06/2019 - 04:04:14: SourceMod error session started
L 11/06/2019 - 04:04:14: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 04:04:14: [CRASH] Accelerator uploaded crash dump: Crash ID: CMIA-AMUR-Z7SY
L 11/06/2019 - 04:05:09: Error log file session closed.
L 11/06/2019 - 04:07:57: SourceMod error session started
L 11/06/2019 - 04:07:57: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 04:07:57: [CRASH] Accelerator uploaded crash dump: Crash ID: KO6J-NACU-BV7U
L 11/06/2019 - 04:57:10: Error log file session closed.
L 11/06/2019 - 05:03:30: SourceMod error session started
L 11/06/2019 - 05:03:30: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 05:03:30: [SM] Exception reported: Client index 246 is invalid
L 11/06/2019 - 05:03:30: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 05:03:30: [SM] Call stack trace:
L 11/06/2019 - 05:03:30: [SM]   [0] IsClientInGame
L 11/06/2019 - 05:03:30: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 05:03:30: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 05:03:31: [SM] Exception reported: Client index 246 is invalid
L 11/06/2019 - 05:03:31: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 05:03:31: [SM] Call stack trace:
L 11/06/2019 - 05:03:31: [SM]   [0] IsClientInGame
L 11/06/2019 - 05:03:31: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 05:03:31: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 05:07:31: [SM] Exception reported: Client 10 is not in game
L 11/06/2019 - 05:07:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 05:07:31: [SM] Call stack trace:
L 11/06/2019 - 05:07:31: [SM]   [0] GetClientTeam
L 11/06/2019 - 05:07:31: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 05:11:58: SourceMod error session started
L 11/06/2019 - 05:11:58: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 05:11:58: [CRASH] Accelerator uploaded crash dump: Crash ID: 5QL4-XMRV-4WH3
L 11/06/2019 - 13:46:43: Error log file session closed.
L 11/06/2019 - 13:53:21: SourceMod error session started
L 11/06/2019 - 13:53:21: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 13:53:21: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 13:53:21: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 13:53:21: [SM] Call stack trace:
L 11/06/2019 - 13:53:21: [SM]   [0] SetEntProp
L 11/06/2019 - 13:53:21: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 13:56:54: [SM] Exception reported: Client index 392 is invalid
L 11/06/2019 - 13:56:54: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 13:56:54: [SM] Call stack trace:
L 11/06/2019 - 13:56:54: [SM]   [0] IsClientInGame
L 11/06/2019 - 13:56:54: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 13:56:54: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 13:56:55: [SM] Exception reported: Client index 392 is invalid
L 11/06/2019 - 13:56:55: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 13:56:55: [SM] Call stack trace:
L 11/06/2019 - 13:56:55: [SM]   [0] IsClientInGame
L 11/06/2019 - 13:56:55: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 13:56:55: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 13:57:02: [SM] Exception reported: Client index 392 is invalid
L 11/06/2019 - 13:57:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 13:57:02: [SM] Call stack trace:
L 11/06/2019 - 13:57:02: [SM]   [0] IsClientInGame
L 11/06/2019 - 13:57:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 13:57:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 13:57:02: [SM] Exception reported: Client index 392 is invalid
L 11/06/2019 - 13:57:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 13:57:02: [SM] Call stack trace:
L 11/06/2019 - 13:57:02: [SM]   [0] IsClientInGame
L 11/06/2019 - 13:57:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 13:57:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 13:57:04: [SM] Exception reported: Client index 392 is invalid
L 11/06/2019 - 13:57:04: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 13:57:04: [SM] Call stack trace:
L 11/06/2019 - 13:57:04: [SM]   [0] IsClientInGame
L 11/06/2019 - 13:57:04: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 13:57:04: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 13:57:04: [SM] Exception reported: Client index 392 is invalid
L 11/06/2019 - 13:57:04: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 13:57:04: [SM] Call stack trace:
L 11/06/2019 - 13:57:04: [SM]   [0] IsClientInGame
L 11/06/2019 - 13:57:04: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 13:57:04: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 13:57:08: [SM] Exception reported: Client index 392 is invalid
L 11/06/2019 - 13:57:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 13:57:08: [SM] Call stack trace:
L 11/06/2019 - 13:57:08: [SM]   [0] IsClientInGame
L 11/06/2019 - 13:57:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 13:57:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 13:57:47: Error log file session closed.
L 11/06/2019 - 14:13:18: SourceMod error session started
L 11/06/2019 - 14:13:18: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 14:13:18: [UPDATER] --- BEGIN ERRORS FROM AUTOMATIC UPDATER ---
L 11/06/2019 - 14:13:18: [UPDATER] Parse error in update manifest: Line contained too many invalid tokens
L 11/06/2019 - 14:13:18: [UPDATER] --- END ERRORS FROM AUTOMATIC UPDATER ---
L 11/06/2019 - 18:09:56: Error log file session closed.
L 11/06/2019 - 18:21:00: SourceMod error session started
L 11/06/2019 - 18:21:00: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 18:21:00: [SM] Exception reported: Client 5 is not in game
L 11/06/2019 - 18:21:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 18:21:00: [SM] Call stack trace:
L 11/06/2019 - 18:21:00: [SM]   [0] GetClientTeam
L 11/06/2019 - 18:21:00: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 18:21:01: Error log file session closed.
L 11/06/2019 - 18:35:16: SourceMod error session started
L 11/06/2019 - 18:35:16: Info (map "c5m2_park") (file "errors_20191106.log")
L 11/06/2019 - 18:35:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 18:35:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 18:35:16: [SM] Call stack trace:
L 11/06/2019 - 18:35:16: [SM]   [0] SetEntProp
L 11/06/2019 - 18:35:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 18:35:30: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 18:35:30: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 18:35:30: [SM] Call stack trace:
L 11/06/2019 - 18:35:30: [SM]   [0] SetEntProp
L 11/06/2019 - 18:35:30: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 18:36:52: [SM] Exception reported: Entity 3 (3) is invalid
L 11/06/2019 - 18:36:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 18:36:52: [SM] Call stack trace:
L 11/06/2019 - 18:36:52: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 18:36:52: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 18:43:17: [SM] Exception reported: Entity 5 (5) is invalid
L 11/06/2019 - 18:43:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 18:43:17: [SM] Call stack trace:
L 11/06/2019 - 18:43:17: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 18:43:17: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 18:43:30: [SM] Exception reported: Entity 5 (5) is invalid
L 11/06/2019 - 18:43:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 18:43:30: [SM] Call stack trace:
L 11/06/2019 - 18:43:30: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 18:43:30: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 18:43:33: Error log file session closed.
L 11/06/2019 - 18:50:18: SourceMod error session started
L 11/06/2019 - 18:50:18: Info (map "c5m3_cemetery") (file "errors_20191106.log")
L 11/06/2019 - 18:50:18: [SM] Exception reported: Client index 651 is invalid
L 11/06/2019 - 18:50:18: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 18:50:18: [SM] Call stack trace:
L 11/06/2019 - 18:50:18: [SM]   [0] IsClientInGame
L 11/06/2019 - 18:50:18: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 18:50:18: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 18:50:20: [SM] Exception reported: Client index 651 is invalid
L 11/06/2019 - 18:50:20: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 18:50:20: [SM] Call stack trace:
L 11/06/2019 - 18:50:20: [SM]   [0] IsClientInGame
L 11/06/2019 - 18:50:20: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 18:50:20: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 18:51:34: [SM] Exception reported: Entity 10 (10) is invalid
L 11/06/2019 - 18:51:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 18:51:34: [SM] Call stack trace:
L 11/06/2019 - 18:51:34: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 18:51:34: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 18:55:07: [SM] Exception reported: Entity 5 (5) is invalid
L 11/06/2019 - 18:55:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 18:55:07: [SM] Call stack trace:
L 11/06/2019 - 18:55:07: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 18:55:07: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 18:55:09: Error log file session closed.
L 11/06/2019 - 19:07:15: SourceMod error session started
L 11/06/2019 - 19:07:15: Info (map "c5m4_quarter") (file "errors_20191106.log")
L 11/06/2019 - 19:07:15: [SM] Exception reported: Client index 100 is invalid
L 11/06/2019 - 19:07:15: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 19:07:15: [SM] Call stack trace:
L 11/06/2019 - 19:07:15: [SM]   [0] IsClientInGame
L 11/06/2019 - 19:07:15: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 19:07:15: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 19:08:31: Error log file session closed.
L 11/06/2019 - 19:10:16: SourceMod error session started
L 11/06/2019 - 19:10:16: Info (map "c5m5_bridge") (file "errors_20191106.log")
L 11/06/2019 - 19:10:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 19:10:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 19:10:16: [SM] Call stack trace:
L 11/06/2019 - 19:10:16: [SM]   [0] SetEntProp
L 11/06/2019 - 19:10:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 19:14:22: [SM] Exception reported: Client 3 is not in game
L 11/06/2019 - 19:14:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:14:22: [SM] Call stack trace:
L 11/06/2019 - 19:14:22: [SM]   [0] GetClientTeam
L 11/06/2019 - 19:14:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:14:24: Error log file session closed.
L 11/06/2019 - 19:17:14: SourceMod error session started
L 11/06/2019 - 19:17:14: Info (map "c11m1_greenhouse") (file "errors_20191106.log")
L 11/06/2019 - 19:17:14: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 19:17:14: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 19:17:14: [SM] Call stack trace:
L 11/06/2019 - 19:17:14: [SM]   [0] SetEntProp
L 11/06/2019 - 19:17:14: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 19:17:32: [SM] Exception reported: Entity 6 (6) is invalid
L 11/06/2019 - 19:17:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:17:32: [SM] Call stack trace:
L 11/06/2019 - 19:17:32: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 19:17:32: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:22:22: [SM] Exception reported: Client 6 is not in game
L 11/06/2019 - 19:22:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:22:22: [SM] Call stack trace:
L 11/06/2019 - 19:22:22: [SM]   [0] GetClientTeam
L 11/06/2019 - 19:22:22: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:22:22: [SM] Exception reported: Entity 3 (3) is invalid
L 11/06/2019 - 19:22:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:22:22: [SM] Call stack trace:
L 11/06/2019 - 19:22:22: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 19:22:22: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:22:24: Error log file session closed.
L 11/06/2019 - 19:30:13: SourceMod error session started
L 11/06/2019 - 19:30:13: Info (map "c11m2_offices") (file "errors_20191106.log")
L 11/06/2019 - 19:30:13: [SM] Exception reported: Client 6 is not in game
L 11/06/2019 - 19:30:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:30:13: [SM] Call stack trace:
L 11/06/2019 - 19:30:13: [SM]   [0] GetClientTeam
L 11/06/2019 - 19:30:13: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:33:29: [SM] Exception reported: Entity 1 (1) is invalid
L 11/06/2019 - 19:33:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:33:29: [SM] Call stack trace:
L 11/06/2019 - 19:33:29: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 19:33:29: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:33:31: Error log file session closed.
L 11/06/2019 - 19:41:39: SourceMod error session started
L 11/06/2019 - 19:41:39: Info (map "c11m3_garage") (file "errors_20191106.log")
L 11/06/2019 - 19:41:39: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 19:41:39: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 19:41:39: [SM] Call stack trace:
L 11/06/2019 - 19:41:39: [SM]   [0] SetEntProp
L 11/06/2019 - 19:41:39: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 19:46:46: [SM] Exception reported: Entity 2 (2) is invalid
L 11/06/2019 - 19:46:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:46:46: [SM] Call stack trace:
L 11/06/2019 - 19:46:46: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 19:46:46: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/06/2019 - 19:46:48: Error log file session closed.
L 11/06/2019 - 19:58:14: SourceMod error session started
L 11/06/2019 - 19:58:14: Info (map "c11m4_terminal") (file "errors_20191106.log")
L 11/06/2019 - 19:58:14: [SM] Exception reported: Client 1 is not in game
L 11/06/2019 - 19:58:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:58:14: [SM] Call stack trace:
L 11/06/2019 - 19:58:14: [SM]   [0] GetClientTeam
L 11/06/2019 - 19:58:14: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:58:14: [SM] Exception reported: Entity 3 (3) is invalid
L 11/06/2019 - 19:58:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 19:58:14: [SM] Call stack trace:
L 11/06/2019 - 19:58:14: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 19:58:14: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 19:58:14: Error log file session closed.
L 11/06/2019 - 20:06:22: SourceMod error session started
L 11/06/2019 - 20:06:22: Info (map "c11m5_runway") (file "errors_20191106.log")
L 11/06/2019 - 20:06:22: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:06:22: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:06:22: [SM] Call stack trace:
L 11/06/2019 - 20:06:22: [SM]   [0] SetEntProp
L 11/06/2019 - 20:06:22: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:06:30: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:06:30: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:06:30: [SM] Call stack trace:
L 11/06/2019 - 20:06:30: [SM]   [0] SetEntProp
L 11/06/2019 - 20:06:30: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:06:57: [SM] Exception reported: Entity 1 (1) is invalid
L 11/06/2019 - 20:06:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 20:06:57: [SM] Call stack trace:
L 11/06/2019 - 20:06:57: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 20:06:57: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 20:06:58: Error log file session closed.
L 11/06/2019 - 20:07:03: SourceMod error session started
L 11/06/2019 - 20:07:03: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 20:07:03: [SM] Exception reported: Client 4 is not in game
L 11/06/2019 - 20:07:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 20:07:03: [SM] Call stack trace:
L 11/06/2019 - 20:07:03: [SM]   [0] GetClientTeam
L 11/06/2019 - 20:07:03: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 20:09:29: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:09:29: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:09:29: [SM] Call stack trace:
L 11/06/2019 - 20:09:29: [SM]   [0] SetEntProp
L 11/06/2019 - 20:09:29: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:12:05: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:12:05: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:12:05: [SM] Call stack trace:
L 11/06/2019 - 20:12:05: [SM]   [0] SetEntProp
L 11/06/2019 - 20:12:05: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:12:48: [SM] Exception reported: Entity 3 (3) is invalid
L 11/06/2019 - 20:12:48: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 20:12:48: [SM] Call stack trace:
L 11/06/2019 - 20:12:48: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 20:12:48: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 20:12:50: Error log file session closed.
L 11/06/2019 - 20:20:28: SourceMod error session started
L 11/06/2019 - 20:20:28: Info (map "c2m2_fairgrounds") (file "errors_20191106.log")
L 11/06/2019 - 20:20:28: [SM] Exception reported: Client index 388 is invalid
L 11/06/2019 - 20:20:28: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:20:28: [SM] Call stack trace:
L 11/06/2019 - 20:20:28: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:20:28: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:20:28: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:22:18: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:22:18: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:22:18: [SM] Call stack trace:
L 11/06/2019 - 20:22:18: [SM]   [0] SetEntProp
L 11/06/2019 - 20:22:18: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:23:06: Error log file session closed.
L 11/06/2019 - 20:26:08: SourceMod error session started
L 11/06/2019 - 20:26:08: Info (map "c2m3_coaster") (file "errors_20191106.log")
L 11/06/2019 - 20:26:08: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:26:08: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:26:08: [SM] Call stack trace:
L 11/06/2019 - 20:26:08: [SM]   [0] SetEntProp
L 11/06/2019 - 20:26:08: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:35:06: Error log file session closed.
L 11/06/2019 - 20:48:02: SourceMod error session started
L 11/06/2019 - 20:48:02: Info (map "c2m4_barns") (file "errors_20191106.log")
L 11/06/2019 - 20:48:02: [SM] Exception reported: Client index 196 is invalid
L 11/06/2019 - 20:48:02: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:48:02: [SM] Call stack trace:
L 11/06/2019 - 20:48:02: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:48:02: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:48:02: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:48:56: [SM] Exception reported: Client 10 is not in game
L 11/06/2019 - 20:48:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 20:48:56: [SM] Call stack trace:
L 11/06/2019 - 20:48:56: [SM]   [0] GetClientTeam
L 11/06/2019 - 20:48:56: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 20:50:29: Error log file session closed.
L 11/06/2019 - 20:51:24: SourceMod error session started
L 11/06/2019 - 20:51:24: Info (map "c2m5_concert") (file "errors_20191106.log")
L 11/06/2019 - 20:51:24: [SM] Exception reported: Client index 298 is invalid
L 11/06/2019 - 20:51:24: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:51:24: [SM] Call stack trace:
L 11/06/2019 - 20:51:24: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:51:24: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:51:24: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:51:24: [SM] Exception reported: Client index 298 is invalid
L 11/06/2019 - 20:51:24: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:51:24: [SM] Call stack trace:
L 11/06/2019 - 20:51:24: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:51:24: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:51:24: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:51:28: [SM] Exception reported: Client index 298 is invalid
L 11/06/2019 - 20:51:28: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:51:28: [SM] Call stack trace:
L 11/06/2019 - 20:51:28: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:51:28: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:51:28: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:53:42: [SM] Exception reported: Client index 512 is invalid
L 11/06/2019 - 20:53:42: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:53:42: [SM] Call stack trace:
L 11/06/2019 - 20:53:42: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:53:42: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:53:42: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:53:43: [SM] Exception reported: Client index 512 is invalid
L 11/06/2019 - 20:53:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:53:43: [SM] Call stack trace:
L 11/06/2019 - 20:53:43: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:53:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:53:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:53:45: [SM] Exception reported: Client index 512 is invalid
L 11/06/2019 - 20:53:45: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 20:53:45: [SM] Call stack trace:
L 11/06/2019 - 20:53:45: [SM]   [0] IsClientInGame
L 11/06/2019 - 20:53:45: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 20:53:45: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 20:58:37: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:58:37: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:58:37: [SM] Call stack trace:
L 11/06/2019 - 20:58:37: [SM]   [0] SetEntProp
L 11/06/2019 - 20:58:37: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:58:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:58:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:58:41: [SM] Call stack trace:
L 11/06/2019 - 20:58:41: [SM]   [0] SetEntProp
L 11/06/2019 - 20:58:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:59:37: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 20:59:37: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 20:59:37: [SM] Call stack trace:
L 11/06/2019 - 20:59:37: [SM]   [0] SetEntProp
L 11/06/2019 - 20:59:37: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 20:59:55: [SM] Exception reported: Entity 2 (2) is invalid
L 11/06/2019 - 20:59:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 20:59:55: [SM] Call stack trace:
L 11/06/2019 - 20:59:55: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 20:59:55: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 20:59:57: Error log file session closed.
L 11/06/2019 - 21:08:51: SourceMod error session started
L 11/06/2019 - 21:08:51: Info (map "c4m1_milltown_a") (file "errors_20191106.log")
L 11/06/2019 - 21:08:51: [SM] Exception reported: Entity 1 (1) is invalid
L 11/06/2019 - 21:08:51: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 21:08:51: [SM] Call stack trace:
L 11/06/2019 - 21:08:51: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 21:08:51: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 21:08:53: Error log file session closed.
L 11/06/2019 - 21:12:43: SourceMod error session started
L 11/06/2019 - 21:12:43: Info (map "c4m2_sugarmill_a") (file "errors_20191106.log")
L 11/06/2019 - 21:12:43: [SM] Exception reported: Client index 91 is invalid
L 11/06/2019 - 21:12:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 21:12:43: [SM] Call stack trace:
L 11/06/2019 - 21:12:43: [SM]   [0] IsClientInGame
L 11/06/2019 - 21:12:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 21:12:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 21:14:20: [SM] Exception reported: Client index 107 is invalid
L 11/06/2019 - 21:14:20: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 21:14:20: [SM] Call stack trace:
L 11/06/2019 - 21:14:20: [SM]   [0] IsClientInGame
L 11/06/2019 - 21:14:20: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 21:14:20: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 21:14:21: [SM] Exception reported: Client index 107 is invalid
L 11/06/2019 - 21:14:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/06/2019 - 21:14:21: [SM] Call stack trace:
L 11/06/2019 - 21:14:21: [SM]   [0] IsClientInGame
L 11/06/2019 - 21:14:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/06/2019 - 21:14:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/06/2019 - 21:20:56: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 21:20:56: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 21:20:56: [SM] Call stack trace:
L 11/06/2019 - 21:20:56: [SM]   [0] SetEntProp
L 11/06/2019 - 21:20:56: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 21:21:55: Error log file session closed.
L 11/06/2019 - 21:26:02: SourceMod error session started
L 11/06/2019 - 21:26:02: Info (map "c5m1_waterfront") (file "errors_20191106.log")
L 11/06/2019 - 21:26:02: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 21:26:02: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 21:26:02: [SM] Call stack trace:
L 11/06/2019 - 21:26:02: [SM]   [0] SetEntProp
L 11/06/2019 - 21:26:02: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 21:29:34: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 21:29:34: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 21:29:34: [SM] Call stack trace:
L 11/06/2019 - 21:29:34: [SM]   [0] SetEntProp
L 11/06/2019 - 21:29:34: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 21:31:52: [SM] Exception reported: Entity 4 (4) is invalid
L 11/06/2019 - 21:31:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 21:31:52: [SM] Call stack trace:
L 11/06/2019 - 21:31:52: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 21:31:52: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 21:31:52: [SM] Exception reported: Entity 7 (7) is invalid
L 11/06/2019 - 21:31:52: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 21:31:52: [SM] Call stack trace:
L 11/06/2019 - 21:31:52: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 21:31:52: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 21:31:53: Error log file session closed.
L 11/06/2019 - 21:43:41: SourceMod error session started
L 11/06/2019 - 21:43:41: Info (map "c5m2_park") (file "errors_20191106.log")
L 11/06/2019 - 21:43:41: [SM] Exception reported: Client 3 is not in game
L 11/06/2019 - 21:43:41: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 21:43:41: [SM] Call stack trace:
L 11/06/2019 - 21:43:41: [SM]   [0] GetClientTeam
L 11/06/2019 - 21:43:41: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 21:43:47: Error log file session closed.
L 11/06/2019 - 21:48:26: SourceMod error session started
L 11/06/2019 - 21:48:26: Info (map "c5m3_cemetery") (file "errors_20191106.log")
L 11/06/2019 - 21:48:26: [SM] Exception reported: Client 1 is not in game
L 11/06/2019 - 21:48:26: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 21:48:26: [SM] Call stack trace:
L 11/06/2019 - 21:48:26: [SM]   [0] GetClientTeam
L 11/06/2019 - 21:48:26: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 21:49:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 21:49:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 21:49:57: [SM] Call stack trace:
L 11/06/2019 - 21:49:57: [SM]   [0] SetEntProp
L 11/06/2019 - 21:49:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 21:54:05: SourceMod error session started
L 11/06/2019 - 21:54:05: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 21:54:05: [CRASH] Accelerator uploaded crash dump: Crash ID: N7N6-T6F3-6OBE
L 11/06/2019 - 21:57:28: Error log file session closed.
L 11/06/2019 - 22:03:52: SourceMod error session started
L 11/06/2019 - 22:03:52: Info (map "c8m1_apartment") (file "errors_20191106.log")
L 11/06/2019 - 22:03:52: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 22:03:52: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 22:03:52: [SM] Call stack trace:
L 11/06/2019 - 22:03:52: [SM]   [0] SetEntProp
L 11/06/2019 - 22:03:52: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 22:03:54: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 22:03:54: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 22:03:54: [SM] Call stack trace:
L 11/06/2019 - 22:03:54: [SM]   [0] SetEntProp
L 11/06/2019 - 22:03:54: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 22:04:00: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 22:04:00: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 22:04:00: [SM] Call stack trace:
L 11/06/2019 - 22:04:00: [SM]   [0] SetEntProp
L 11/06/2019 - 22:04:00: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 22:04:34: [SM] Exception reported: Entity 2 (2) is invalid
L 11/06/2019 - 22:04:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 22:04:34: [SM] Call stack trace:
L 11/06/2019 - 22:04:34: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 22:04:34: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 22:04:49: Error log file session closed.
L 11/06/2019 - 22:10:53: SourceMod error session started
L 11/06/2019 - 22:10:53: Info (map "c8m2_subway") (file "errors_20191106.log")
L 11/06/2019 - 22:10:53: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 22:10:53: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 22:10:53: [SM] Call stack trace:
L 11/06/2019 - 22:10:53: [SM]   [0] SetEntProp
L 11/06/2019 - 22:10:53: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 22:12:50: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 22:12:50: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 22:12:50: [SM] Call stack trace:
L 11/06/2019 - 22:12:50: [SM]   [0] SetEntProp
L 11/06/2019 - 22:12:50: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 22:13:34: [SM] Exception reported: Entity 1 (1) is invalid
L 11/06/2019 - 22:13:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/06/2019 - 22:13:34: [SM] Call stack trace:
L 11/06/2019 - 22:13:34: [SM]   [0] GetEntDataEnt2
L 11/06/2019 - 22:13:34: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/06/2019 - 22:13:36: Error log file session closed.
L 11/06/2019 - 22:16:13: SourceMod error session started
L 11/06/2019 - 22:16:13: Info (map "c8m3_sewers") (file "errors_20191106.log")
L 11/06/2019 - 22:16:13: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/06/2019 - 22:16:13: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/06/2019 - 22:16:13: [SM] Call stack trace:
L 11/06/2019 - 22:16:13: [SM]   [0] SetEntProp
L 11/06/2019 - 22:16:13: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/06/2019 - 22:22:57: SourceMod error session started
L 11/06/2019 - 22:22:57: Info (map "c2m1_highway") (file "errors_20191106.log")
L 11/06/2019 - 22:22:57: [UPDATER] --- BEGIN ERRORS FROM AUTOMATIC UPDATER ---
L 11/06/2019 - 22:22:57: [UPDATER] Parse error in update manifest: Line contained too many invalid tokens
L 11/06/2019 - 22:22:57: [UPDATER] --- END ERRORS FROM AUTOMATIC UPDATER ---
