L 10/12/2019 - 15:25:27: SourceMod error session started
L 10/12/2019 - 15:25:27: Info (map "c5m2_park") (file "errors_20191012.log")
L 10/12/2019 - 15:25:27: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 15:25:27: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 15:25:27: [SM] Call stack trace:
L 10/12/2019 - 15:25:27: [SM]   [0] SetEntProp
L 10/12/2019 - 15:25:27: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 15:26:00: [SM] Exception reported: Entity 6 (6) is invalid
L 10/12/2019 - 15:26:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 15:26:00: [SM] Call stack trace:
L 10/12/2019 - 15:26:00: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 15:26:00: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 15:26:00: [SM] Exception reported: Entity 10 (10) is invalid
L 10/12/2019 - 15:26:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 15:26:00: [SM] Call stack trace:
L 10/12/2019 - 15:26:00: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 15:26:00: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 15:26:01: Error log file session closed.
L 10/12/2019 - 15:31:12: SourceMod error session started
L 10/12/2019 - 15:31:12: Info (map "c5m3_cemetery") (file "errors_20191012.log")
L 10/12/2019 - 15:31:12: [SM] Exception reported: Client 7 is not in game
L 10/12/2019 - 15:31:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 15:31:12: [SM] Call stack trace:
L 10/12/2019 - 15:31:12: [SM]   [0] GetClientTeam
L 10/12/2019 - 15:31:12: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 15:31:50: [SM] Exception reported: Entity 7 (7) is invalid
L 10/12/2019 - 15:31:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 15:31:50: [SM] Call stack trace:
L 10/12/2019 - 15:31:50: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 15:31:50: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 15:37:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 15:37:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 15:37:25: [SM] Call stack trace:
L 10/12/2019 - 15:37:25: [SM]   [0] SetEntProp
L 10/12/2019 - 15:37:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 15:38:00: [SM] Exception reported: Entity 10 (10) is invalid
L 10/12/2019 - 15:38:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 15:38:00: [SM] Call stack trace:
L 10/12/2019 - 15:38:00: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 15:38:00: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 15:38:01: Error log file session closed.
L 10/12/2019 - 15:46:41: SourceMod error session started
L 10/12/2019 - 15:46:41: Info (map "c5m4_quarter") (file "errors_20191012.log")
L 10/12/2019 - 15:46:41: [SM] Exception reported: Client 4 is not in game
L 10/12/2019 - 15:46:41: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 15:46:41: [SM] Call stack trace:
L 10/12/2019 - 15:46:41: [SM]   [0] GetClientTeam
L 10/12/2019 - 15:46:41: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 15:51:01: [SM] Exception reported: Client 6 is not in game
L 10/12/2019 - 15:51:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 15:51:01: [SM] Call stack trace:
L 10/12/2019 - 15:51:01: [SM]   [0] GetClientTeam
L 10/12/2019 - 15:51:01: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 15:53:49: Error log file session closed.
L 10/12/2019 - 15:55:29: SourceMod error session started
L 10/12/2019 - 15:55:29: Info (map "c5m5_bridge") (file "errors_20191012.log")
L 10/12/2019 - 15:55:29: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 15:55:29: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 15:55:29: [SM] Call stack trace:
L 10/12/2019 - 15:55:29: [SM]   [0] SetEntProp
L 10/12/2019 - 15:55:29: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 15:55:43: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 15:55:43: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 15:55:43: [SM] Call stack trace:
L 10/12/2019 - 15:55:43: [SM]   [0] SetEntProp
L 10/12/2019 - 15:55:43: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 16:02:16: [SM] Exception reported: Entity 3 (3) is invalid
L 10/12/2019 - 16:02:16: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:02:16: [SM] Call stack trace:
L 10/12/2019 - 16:02:16: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:02:16: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 16:02:16: Error log file session closed.
L 10/12/2019 - 16:14:44: SourceMod error session started
L 10/12/2019 - 16:14:44: Info (map "c2m1_highway") (file "errors_20191012.log")
L 10/12/2019 - 16:14:44: [SM] Exception reported: Entity 1 (1) is invalid
L 10/12/2019 - 16:14:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:14:44: [SM] Call stack trace:
L 10/12/2019 - 16:14:44: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:14:44: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 16:14:45: Error log file session closed.
L 10/12/2019 - 16:20:32: SourceMod error session started
L 10/12/2019 - 16:20:32: Info (map "c2m2_fairgrounds") (file "errors_20191012.log")
L 10/12/2019 - 16:20:32: [SM] Exception reported: Entity 7 (7) is invalid
L 10/12/2019 - 16:20:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:20:32: [SM] Call stack trace:
L 10/12/2019 - 16:20:32: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:20:32: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 16:25:31: [SM] Exception reported: Entity 9 (9) is invalid
L 10/12/2019 - 16:25:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:25:31: [SM] Call stack trace:
L 10/12/2019 - 16:25:31: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:25:31: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 16:25:32: Error log file session closed.
L 10/12/2019 - 16:35:51: SourceMod error session started
L 10/12/2019 - 16:35:51: Info (map "c2m4_barns") (file "errors_20191012.log")
L 10/12/2019 - 16:35:51: [SM] Exception reported: Client index 369 is invalid
L 10/12/2019 - 16:35:51: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 16:35:51: [SM] Call stack trace:
L 10/12/2019 - 16:35:51: [SM]   [0] IsClientInGame
L 10/12/2019 - 16:35:51: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 16:35:51: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 16:35:58: [SM] Exception reported: Client index 369 is invalid
L 10/12/2019 - 16:35:58: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 16:35:58: [SM] Call stack trace:
L 10/12/2019 - 16:35:58: [SM]   [0] IsClientInGame
L 10/12/2019 - 16:35:58: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 16:35:58: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 16:40:01: [SM] Exception reported: Client index 160 is invalid
L 10/12/2019 - 16:40:01: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 16:40:01: [SM] Call stack trace:
L 10/12/2019 - 16:40:01: [SM]   [0] IsClientInGame
L 10/12/2019 - 16:40:01: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 16:40:01: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 16:40:13: [SM] Exception reported: Client index 160 is invalid
L 10/12/2019 - 16:40:13: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 16:40:13: [SM] Call stack trace:
L 10/12/2019 - 16:40:13: [SM]   [0] IsClientInGame
L 10/12/2019 - 16:40:13: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 16:40:13: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 16:40:13: [SM] Exception reported: Client index 160 is invalid
L 10/12/2019 - 16:40:13: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 16:40:13: [SM] Call stack trace:
L 10/12/2019 - 16:40:13: [SM]   [0] IsClientInGame
L 10/12/2019 - 16:40:13: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 16:40:13: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 16:40:13: [SM] Exception reported: Client index 160 is invalid
L 10/12/2019 - 16:40:13: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 16:40:13: [SM] Call stack trace:
L 10/12/2019 - 16:40:13: [SM]   [0] IsClientInGame
L 10/12/2019 - 16:40:13: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 16:40:13: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 16:42:12: Error log file session closed.
L 10/12/2019 - 16:44:01: SourceMod error session started
L 10/12/2019 - 16:44:01: Info (map "c2m5_concert") (file "errors_20191012.log")
L 10/12/2019 - 16:44:01: [SM] Exception reported: Entity 7 (7) is invalid
L 10/12/2019 - 16:44:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:44:01: [SM] Call stack trace:
L 10/12/2019 - 16:44:01: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:44:01: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 16:44:24: [SM] Exception reported: Entity 1 (1) is invalid
L 10/12/2019 - 16:44:24: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:44:24: [SM] Call stack trace:
L 10/12/2019 - 16:44:24: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:44:24: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 16:45:05: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 16:45:05: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 16:45:05: [SM] Call stack trace:
L 10/12/2019 - 16:45:05: [SM]   [0] SetEntProp
L 10/12/2019 - 16:45:05: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 16:46:30: [SM] Exception reported: Client index 593 is invalid
L 10/12/2019 - 16:46:30: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 16:46:30: [SM] Call stack trace:
L 10/12/2019 - 16:46:30: [SM]   [0] IsClientInGame
L 10/12/2019 - 16:46:30: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 16:46:30: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 16:52:28: [SM] Exception reported: Entity 6 (6) is invalid
L 10/12/2019 - 16:52:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:52:28: [SM] Call stack trace:
L 10/12/2019 - 16:52:28: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:52:28: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 16:52:29: Error log file session closed.
L 10/12/2019 - 16:52:31: SourceMod error session started
L 10/12/2019 - 16:52:31: Info (map "c1m1_hotel") (file "errors_20191012.log")
L 10/12/2019 - 16:52:31: [SM] Exception reported: Client 5 is not in game
L 10/12/2019 - 16:52:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:52:31: [SM] Call stack trace:
L 10/12/2019 - 16:52:31: [SM]   [0] GetClientTeam
L 10/12/2019 - 16:52:31: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 16:55:28: [SM] Exception reported: Entity 6 (6) is invalid
L 10/12/2019 - 16:55:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:55:28: [SM] Call stack trace:
L 10/12/2019 - 16:55:28: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:55:28: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 16:57:19: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 16:57:19: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 16:57:19: [SM] Call stack trace:
L 10/12/2019 - 16:57:19: [SM]   [0] SetEntProp
L 10/12/2019 - 16:57:19: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 16:59:04: [SM] Exception reported: Entity 2 (2) is invalid
L 10/12/2019 - 16:59:04: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 16:59:04: [SM] Call stack trace:
L 10/12/2019 - 16:59:04: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 16:59:04: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 16:59:05: Error log file session closed.
L 10/12/2019 - 17:02:43: SourceMod error session started
L 10/12/2019 - 17:02:43: Info (map "c1m2_streets") (file "errors_20191012.log")
L 10/12/2019 - 17:02:43: [SM] Exception reported: Client 6 is not in game
L 10/12/2019 - 17:02:43: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 17:02:43: [SM] Call stack trace:
L 10/12/2019 - 17:02:43: [SM]   [0] GetClientTeam
L 10/12/2019 - 17:02:43: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 17:14:03: [SM] Exception reported: Entity 5 (5) is invalid
L 10/12/2019 - 17:14:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 17:14:03: [SM] Call stack trace:
L 10/12/2019 - 17:14:03: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 17:14:03: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 17:14:03: [SM] Exception reported: Entity 5 (5) is invalid
L 10/12/2019 - 17:14:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 17:14:03: [SM] Call stack trace:
L 10/12/2019 - 17:14:03: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 17:14:03: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 17:14:54: [SM] Exception reported: Entity 4 (4) is invalid
L 10/12/2019 - 17:14:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 17:14:54: [SM] Call stack trace:
L 10/12/2019 - 17:14:54: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 17:14:54: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 17:18:53: [SM] Exception reported: Entity 10 (10) is invalid
L 10/12/2019 - 17:18:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 17:18:53: [SM] Call stack trace:
L 10/12/2019 - 17:18:53: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 17:18:53: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 17:18:55: Error log file session closed.
L 10/12/2019 - 17:34:04: SourceMod error session started
L 10/12/2019 - 17:34:04: Info (map "c1m4_atrium") (file "errors_20191012.log")
L 10/12/2019 - 17:34:04: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 17:34:04: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 17:34:04: [SM] Call stack trace:
L 10/12/2019 - 17:34:04: [SM]   [0] SetEntProp
L 10/12/2019 - 17:34:04: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 17:40:10: [SM] Exception reported: Entity 9 (9) is invalid
L 10/12/2019 - 17:40:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 17:40:10: [SM] Call stack trace:
L 10/12/2019 - 17:40:10: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 17:40:10: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 17:40:11: Error log file session closed.
L 10/12/2019 - 17:45:23: SourceMod error session started
L 10/12/2019 - 17:45:23: Info (map "c2m1_highway") (file "errors_20191012.log")
L 10/12/2019 - 17:45:23: [CRASH] Accelerator uploaded crash dump: Crash ID: MTOU-LIFU-DQPX
L 10/12/2019 - 19:37:20: Error log file session closed.
L 10/12/2019 - 19:48:41: SourceMod error session started
L 10/12/2019 - 19:48:41: Info (map "c2m1_highway") (file "errors_20191012.log")
L 10/12/2019 - 19:48:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 19:48:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 19:48:41: [SM] Call stack trace:
L 10/12/2019 - 19:48:41: [SM]   [0] SetEntProp
L 10/12/2019 - 19:48:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 19:56:27: [SM] Exception reported: Entity 8 (8) is invalid
L 10/12/2019 - 19:56:27: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 19:56:27: [SM] Call stack trace:
L 10/12/2019 - 19:56:27: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 19:56:27: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 19:56:27: [SM] Exception reported: Entity 8 (8) is invalid
L 10/12/2019 - 19:56:27: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 19:56:27: [SM] Call stack trace:
L 10/12/2019 - 19:56:27: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 19:56:27: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 19:56:44: [SM] Exception reported: Client 8 is not in game
L 10/12/2019 - 19:56:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 19:56:44: [SM] Call stack trace:
L 10/12/2019 - 19:56:44: [SM]   [0] GetClientTeam
L 10/12/2019 - 19:56:44: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 19:56:44: [SM] Exception reported: Client 9 is not in game
L 10/12/2019 - 19:56:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 19:56:44: [SM] Call stack trace:
L 10/12/2019 - 19:56:44: [SM]   [0] GetClientTeam
L 10/12/2019 - 19:56:44: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 19:56:44: Error log file session closed.
L 10/12/2019 - 20:13:02: SourceMod error session started
L 10/12/2019 - 20:13:02: Info (map "c2m2_fairgrounds") (file "errors_20191012.log")
L 10/12/2019 - 20:13:02: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 20:13:02: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 20:13:02: [SM] Call stack trace:
L 10/12/2019 - 20:13:02: [SM]   [0] SetEntProp
L 10/12/2019 - 20:13:02: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 20:14:51: Error log file session closed.
L 10/12/2019 - 20:17:25: SourceMod error session started
L 10/12/2019 - 20:17:25: Info (map "c2m3_coaster") (file "errors_20191012.log")
L 10/12/2019 - 20:17:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 20:17:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 20:17:25: [SM] Call stack trace:
L 10/12/2019 - 20:17:25: [SM]   [0] SetEntProp
L 10/12/2019 - 20:17:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 20:17:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 20:17:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 20:17:41: [SM] Call stack trace:
L 10/12/2019 - 20:17:41: [SM]   [0] SetEntProp
L 10/12/2019 - 20:17:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 20:27:40: [SM] Exception reported: Entity 11 (11) is invalid
L 10/12/2019 - 20:27:40: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 20:27:40: [SM] Call stack trace:
L 10/12/2019 - 20:27:40: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 20:27:40: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 20:27:40: Error log file session closed.
L 10/12/2019 - 20:31:24: SourceMod error session started
L 10/12/2019 - 20:31:24: Info (map "c2m4_barns") (file "errors_20191012.log")
L 10/12/2019 - 20:31:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 20:31:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 20:31:24: [SM] Call stack trace:
L 10/12/2019 - 20:31:24: [SM]   [0] SetEntProp
L 10/12/2019 - 20:31:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 20:40:39: [SM] Exception reported: Entity 4 (4) is invalid
L 10/12/2019 - 20:40:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 20:40:39: [SM] Call stack trace:
L 10/12/2019 - 20:40:39: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 20:40:39: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 20:40:39: [SM] Exception reported: Client 4 is not in game
L 10/12/2019 - 20:40:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 20:40:39: [SM] Call stack trace:
L 10/12/2019 - 20:40:39: [SM]   [0] GetClientTeam
L 10/12/2019 - 20:40:39: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 20:40:40: Error log file session closed.
L 10/12/2019 - 20:46:31: SourceMod error session started
L 10/12/2019 - 20:46:31: Info (map "c2m5_concert") (file "errors_20191012.log")
L 10/12/2019 - 20:46:31: [SM] Exception reported: Client index 170 is invalid
L 10/12/2019 - 20:46:31: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 20:46:31: [SM] Call stack trace:
L 10/12/2019 - 20:46:31: [SM]   [0] IsClientInGame
L 10/12/2019 - 20:46:31: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 20:46:31: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 20:46:33: [SM] Exception reported: Client index 170 is invalid
L 10/12/2019 - 20:46:33: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/12/2019 - 20:46:33: [SM] Call stack trace:
L 10/12/2019 - 20:46:33: [SM]   [0] IsClientInGame
L 10/12/2019 - 20:46:33: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/12/2019 - 20:46:33: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/12/2019 - 20:52:02: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 20:52:02: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 20:52:02: [SM] Call stack trace:
L 10/12/2019 - 20:52:02: [SM]   [0] SetEntProp
L 10/12/2019 - 20:52:02: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 20:52:07: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 20:52:07: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 20:52:07: [SM] Call stack trace:
L 10/12/2019 - 20:52:07: [SM]   [0] SetEntProp
L 10/12/2019 - 20:52:07: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 20:52:59: [SM] Exception reported: Entity 3 (3) is invalid
L 10/12/2019 - 20:52:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 20:52:59: [SM] Call stack trace:
L 10/12/2019 - 20:52:59: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 20:52:59: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 20:52:59: [SM] Exception reported: Client 8 is not in game
L 10/12/2019 - 20:52:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 20:52:59: [SM] Call stack trace:
L 10/12/2019 - 20:52:59: [SM]   [0] GetClientTeam
L 10/12/2019 - 20:52:59: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 20:52:59: [SM] Exception reported: Entity 7 (7) is invalid
L 10/12/2019 - 20:52:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 20:52:59: [SM] Call stack trace:
L 10/12/2019 - 20:52:59: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 20:52:59: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 20:53:00: Error log file session closed.
L 10/12/2019 - 21:00:07: SourceMod error session started
L 10/12/2019 - 21:00:07: Info (map "c3m1_plankcountry") (file "errors_20191012.log")
L 10/12/2019 - 21:00:07: [SM] Exception reported: Client 1 is not in game
L 10/12/2019 - 21:00:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:00:07: [SM] Call stack trace:
L 10/12/2019 - 21:00:07: [SM]   [0] GetClientTeam
L 10/12/2019 - 21:00:07: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 21:07:56: [SM] Exception reported: Entity 3 (3) is invalid
L 10/12/2019 - 21:07:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:07:56: [SM] Call stack trace:
L 10/12/2019 - 21:07:56: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 21:07:56: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 21:07:56: [SM] Exception reported: Entity 4 (4) is invalid
L 10/12/2019 - 21:07:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:07:56: [SM] Call stack trace:
L 10/12/2019 - 21:07:56: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 21:07:56: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 21:07:57: Error log file session closed.
L 10/12/2019 - 21:11:20: SourceMod error session started
L 10/12/2019 - 21:11:20: Info (map "c3m2_swamp") (file "errors_20191012.log")
L 10/12/2019 - 21:11:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 21:11:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 21:11:20: [SM] Call stack trace:
L 10/12/2019 - 21:11:20: [SM]   [0] SetEntProp
L 10/12/2019 - 21:11:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 21:11:38: [SM] Exception reported: Entity 3 (3) is invalid
L 10/12/2019 - 21:11:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:11:38: [SM] Call stack trace:
L 10/12/2019 - 21:11:38: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 21:11:38: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 21:11:49: [SM] Exception reported: Entity 10 (10) is invalid
L 10/12/2019 - 21:11:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:11:49: [SM] Call stack trace:
L 10/12/2019 - 21:11:49: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 21:11:49: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 21:21:49: [SM] Exception reported: Entity 6 (6) is invalid
L 10/12/2019 - 21:21:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:21:49: [SM] Call stack trace:
L 10/12/2019 - 21:21:49: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 21:21:49: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 21:21:50: Error log file session closed.
L 10/12/2019 - 21:28:08: SourceMod error session started
L 10/12/2019 - 21:28:08: Info (map "c3m3_shantytown") (file "errors_20191012.log")
L 10/12/2019 - 21:28:08: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 21:28:08: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 21:28:08: [SM] Call stack trace:
L 10/12/2019 - 21:28:08: [SM]   [0] SetEntProp
L 10/12/2019 - 21:28:08: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 21:36:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 21:36:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 21:36:01: [SM] Call stack trace:
L 10/12/2019 - 21:36:01: [SM]   [0] SetEntProp
L 10/12/2019 - 21:36:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 21:39:50: [SM] Exception reported: Entity 1 (1) is invalid
L 10/12/2019 - 21:39:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:39:50: [SM] Call stack trace:
L 10/12/2019 - 21:39:50: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 21:39:50: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 21:39:51: Error log file session closed.
L 10/12/2019 - 21:42:55: SourceMod error session started
L 10/12/2019 - 21:42:55: Info (map "c3m4_plantation") (file "errors_20191012.log")
L 10/12/2019 - 21:42:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 21:42:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 21:42:55: [SM] Call stack trace:
L 10/12/2019 - 21:42:55: [SM]   [0] SetEntProp
L 10/12/2019 - 21:42:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 21:50:59: Error log file session closed.
L 10/12/2019 - 21:52:36: SourceMod error session started
L 10/12/2019 - 21:52:36: Info (map "c2m1_highway") (file "errors_20191012.log")
L 10/12/2019 - 21:52:36: [SM] Exception reported: Client 9 is not in game
L 10/12/2019 - 21:52:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 21:52:36: [SM] Call stack trace:
L 10/12/2019 - 21:52:36: [SM]   [0] GetClientTeam
L 10/12/2019 - 21:52:36: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 22:00:04: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/12/2019 - 22:00:04: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/12/2019 - 22:00:04: [SM] Call stack trace:
L 10/12/2019 - 22:00:04: [SM]   [0] SetEntProp
L 10/12/2019 - 22:00:04: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/12/2019 - 22:00:36: [SM] Exception reported: Entity 1 (1) is invalid
L 10/12/2019 - 22:00:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 22:00:36: [SM] Call stack trace:
L 10/12/2019 - 22:00:36: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 22:00:36: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 22:00:36: [SM] Exception reported: Entity 1 (1) is invalid
L 10/12/2019 - 22:00:36: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 22:00:36: [SM] Call stack trace:
L 10/12/2019 - 22:00:36: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 22:00:36: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 22:05:40: Error log file session closed.
L 10/12/2019 - 22:06:58: SourceMod error session started
L 10/12/2019 - 22:06:58: Info (map "c2m2_fairgrounds") (file "errors_20191012.log")
L 10/12/2019 - 22:06:58: [SM] Exception reported: Entity 4 (4) is invalid
L 10/12/2019 - 22:06:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 22:06:58: [SM] Call stack trace:
L 10/12/2019 - 22:06:58: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 22:06:58: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/12/2019 - 22:06:58: Error log file session closed.
L 10/12/2019 - 22:14:57: SourceMod error session started
L 10/12/2019 - 22:14:57: Info (map "c2m2_fairgrounds") (file "errors_20191012.log")
L 10/12/2019 - 22:14:57: [SM] Exception reported: Entity 6 (6) is invalid
L 10/12/2019 - 22:14:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/12/2019 - 22:14:57: [SM] Call stack trace:
L 10/12/2019 - 22:14:57: [SM]   [0] GetEntDataEnt2
L 10/12/2019 - 22:14:57: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/12/2019 - 22:16:07: SourceMod error session started
L 10/12/2019 - 22:16:07: Info (map "c2m1_highway") (file "errors_20191012.log")
L 10/12/2019 - 22:16:07: [CRASH] Accelerator uploaded crash dump: Crash ID: MFNO-23PH-CXJU
